force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <label>Bloco</label>
    <nameField>
        <label>Nome do Bloco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Deve ser preenchido com o empreeendimento corespondente.</description>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Blocos</relationshipLabel>
    <relationshipName>Blocos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Quote/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Cotações</relationshipLabel>
    <relationshipName>Cota_es</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteDA.cls
public with sharing class QuoteDA { 
    public static Map<Id, Quote> getQuotesMapByIds(List<Id> quoteIds) {
        return new Map<Id, Quote>([SELECT Id, OpportunityId, GrandTotal FROM Quote WHERE Id IN :quoteIds]);
    }

    // Função para obter o primeiro produto da cotação
    public static Product2 getProductByQuoteId(Id quoteId) {
        QuoteLineItem lineItem = getFirstQuoteLineItemByQuoteId(quoteId);
        if (lineItem != null) {
            return [SELECT Id, Bloco__c, Empreendimento__c, Name FROM Product2 WHERE Id = :lineItem.Product2Id];
        }
        return null;
    }

    // Função para obter as linhas de itens da cotação
    public static List<QuoteLineItem> getQuoteLineItemsByQuoteId(Id quoteId) {
        return [SELECT Id, QuoteId, Product2Id, Quantity, UnitPrice, Quote.OpportunityId, PricebookEntryId FROM QuoteLineItem WHERE QuoteId = :quoteId];
    } 

    // Função para obter ou criar uma entrada no catálogo de preços
    public static Id getOrCreatePricebookEntryId(Id productId, Id pricebookEntryId) {
        if (pricebookEntryId != null) {
            return pricebookEntryId;
        }

        System.debug('PricebookId:' + Test.getStandardPricebookId());
        
        PricebookEntry newPBE = new PricebookEntry(
            Product2Id = productId,
            Pricebook2Id = Test.getStandardPricebookId(),
            UnitPrice = 0.0,
            IsActive = true
        );
        
        insert newPBE;
        return newPBE.Id;
    }

    // Função privada para obter o primeiro item da cotação
    private static QuoteLineItem getFirstQuoteLineItemByQuoteId(Id quoteId) {
        List<QuoteLineItem> lineItems = [SELECT Id, Product2Id FROM QuoteLineItem WHERE QuoteId = :quoteId LIMIT 1];
        return lineItems.isEmpty() ? null : lineItems[0];
    }
}