force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <label>Bloco</label>
    <nameField>
        <label>Nome do Bloco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Bloco__c/fields/DataEntrega__c.field-meta.xml
<CustomField>
    <fullName>DataEntrega__c</fullName>
    <label>Data de Entrega</label>
    <type>Date</type>
</CustomField>

you/force-app/main/default/objects/Bloco__c/fields/DataLancamento__c.field-meta.xml
<CustomField>
    <fullName>DataLancamento__c</fullName>
    <label>Data de Lançamento</label>
    <type>Date</type>
</CustomField>

you/force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Deve ser preenchido com o empreeendimento corespondente.</description>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Blocos</relationshipLabel>
    <relationshipName>Blocos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/QuantidadeAndares__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAndares__c</fullName>
    <description>Deve ser preenchido 
 com a quantidade
  de andares da Torre.</description>
    <label>Quantidade de Andares</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/TotalUnidades__c.field-meta.xml
<CustomField>
    <fullName>TotalUnidades__c</fullName>
    <description>Deve ser preenchido com a quantidade de andares por Torre.</description>
    <label>Total de Unidades</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecionar se for corretor.</description>
    <label>Corretor</label>
    <type>Checkbox</type>
</CustomField>

you/force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

you/force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Empreendimento__c/fields/SPE__c.field-meta.xml
<CustomField>
    <fullName>SPE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SPE (Sociedade de Propósito Específico)</description>
    <label>SPE</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPE</relationshipLabel>
    <relationshipName>Empreendimentos</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/StatusObra__c.field-meta.xml
<CustomField>
    <fullName>StatusObra__c</fullName>
    <description>Status da obra do empreendimento</description>
    <label>Status da Obra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em construção</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Lançamento</fullName>
            </value>
            <value>
                <fullName>Pré-Lançamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/TipoEmpreendimento__c.field-meta.xml
<CustomField>
    <fullName>TipoEmpreendimento__c</fullName>
    <label>Tipo de Empreendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Lote</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Opportunity/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <infoMessage>Corretor: Tipo de registro do contato igual a Corretor</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>OportunidadesCorretor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Opportunity/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo De Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negócio existente</fullName>
            </value>
            <value>
                <fullName>Negócio novo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/ValorM2__c.field-meta.xml
<CustomField>
    <fullName>ValorM2__c</fullName>
    <label>Valor (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

you/force-app/main/default/objects/Product2/recordTypes/Apartamento.recordType-meta.xml
<RecordType>
    <fullName>Apartamento</fullName>
    <active>true</active>
    <label>Apartamento</label>
</RecordType>

you/force-app/main/default/objects/Product2/recordTypes/Casa.recordType-meta.xml
<RecordType>
    <fullName>Casa</fullName>
    <active>true</active>
    <label>Casa</label>
</RecordType>

you/force-app/main/default/objects/Quote/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Cotações</relationshipLabel>
    <relationshipName>Cota_es</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/classes/OpportunityHelperTest.cls
@isTest
private class OpportunityHelperTest {

    @isTest
    static void testSetDefaultCloseDate() {
        Opportunity opp = new Opportunity();
        opp.Name = 'Nova Oportunidade';
        opp.StageName = 'Negociação';
        opp.CloseDate = null;

        List<Opportunity> opps = new List<Opportunity>{ opp };
        OpportunityHelper.addDaysToCloseDateOnCreation(opps);

        for (Opportunity o : opps) {
            System.assertEquals(Date.today().addDays(5), o.CloseDate, 'CloseDate should be set to today + 5 days');
        }
    }

    @isTest
    static void testValidateTransitionToFichaCadastral_AllFieldsFilled() {
        Account acc = createTestAccount();
        Contact corretorContact = createTestCorretorContact(); // Cria e insere o usuário
        Empreendimento__c empreendimento = createTestEnterprise(acc);
        Bloco__c bloco = createTestBloco(empreendimento);
        Product2 unidade = createTestProduct(empreendimento, bloco);

        Opportunity opp = new Opportunity(
            Name = 'Nova Oportunidade',
            StageName = 'Negociação',
            CloseDate = Date.today().addDays(5),
            Amount = 1000,
            AccountId = acc.Id,
            CanalAtendimento__c = 'WhatsApp',
            Probability = 20,
            TipoVenda__c = 'Negócio novo',
            Corretor__c = corretorContact.Id // Atribui o ID do usuário ao campo Corretor__c
        );
        insert opp;

        Quote quote = new Quote(
            OpportunityId = opp.Id,
            Name = 'Nova Cotação',
            Status = 'Aprovada',
            Pricebook2Id = Test.getStandardPricebookId()
        );
        insert quote;

        opp.SyncedQuoteId = quote.Id;
        update opp;

        Product2 product = createTestProduct('Produto de Teste');
        PricebookEntry pricebookEntry = createTestPricebookEntry(product, quote.Pricebook2Id);

        QuoteLineItem quoteLineItem = new QuoteLineItem(
            QuoteId = quote.Id,
            PricebookEntryId = pricebookEntry.Id,
            Quantity = 1,
            UnitPrice = 100
        );
        insert quoteLineItem;

        OpportunityContactRole ocr = new OpportunityContactRole(
            OpportunityId = quote.OpportunityId,
            ContactId = createTestCorretorContact().Id,
            Role = 'Fiador'
        );
        insert ocr;

        opp.StageName = 'Ficha Cadastral';
        update opp;

        List<Opportunity> opps = new List<Opportunity>{ opp };

        Test.startTest();
        OpportunityHelper.validateTransitionToFichaCadastral(opps, new Map<Id, Opportunity>{ opp.Id => opp });
        Test.stopTest();

        for (Opportunity o : opps) {
            System.assert(o.getErrors().isEmpty(), 'There should be no errors if all required fields are filled');
        }
    }

    @isTest
    static void testValidateTransitionToFichaCadastral_MissingRequiredFields() {
        Opportunity opp = new Opportunity();
        opp.Name = 'Nova Oportunidade';
        opp.StageName = 'Negociação';
        opp.CloseDate = Date.today();
        
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'Nova Oportunidade';
        opp2.StageName = 'Ficha Cadastral';
        opp2.CloseDate = Date.today();

        List<Opportunity> opps = new List<Opportunity>{ opp, opp2 };
        
        Test.startTest();
        OpportunityHelper.validateTransitionToFichaCadastral(opps, new Map<Id, Opportunity>{ opp.Id => opp });
        Test.stopTest();
    }
    
    private static Account createTestAccount() {
        Account acc = new Account(Name = 'first five');
        insert acc;
        return acc;
    }


    private static Contact createTestCorretorContact() {
      
        Account acc = new Account(Name = 'first ss', Type = 'HouseImobiliaria');
        insert acc;
    
        
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Contact' AND Name = 'Corretor' LIMIT 1];
        if (rt == null) {
          System.debug('O tipo de registro "Corretor" não foi encontrado.');
        }
    
      
        Contact contact = new Contact(
            FirstName = 'fernandes',
            LastName = 'dantas',
            Email = 'dantas@elera.io',
            AccountId = acc.Id,
            RecordTypeId = rt.Id 
        );
    
        insert contact;
        return contact;
    }
    

    private static Empreendimento__c createTestEnterprise(Account acc) {
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Nome do Empreendimento',
            SPE__c = acc.Id,
            CNPJEmpreendimento__c = '25790394000150',
            TipoEmpreendimento__c = 'Casa',
            StatusObra__c = 'Entregue',
            MetragemPrivativaTotal__c = 5000,
            MetragemTerreno__c = 10000,
            MetragemConstruIdaM__c = 7000
        );
        insert empreendimento;
        return empreendimento;
    }

    private static Bloco__c createTestBloco(Empreendimento__c empreendimento) {
        Bloco__c bloco = new Bloco__c(
            Name = 'Nome do Bloco',
            DataLancamento__c = Date.today(),
            DataEntrega__c = Date.today().addMonths(12),
            Empreendimento__c = empreendimento.Id,
            QuantidadeAndares__c = 10,
            TotalUnidades__c = 50
        );
        insert bloco;
        return bloco;
    }

    private static Product2 createTestProduct(String productName) {
        Product2 product = new Product2(
            Name = productName,
            ProductCode = 'TestCode' + System.currentTimeMillis(),
            NumeroDaUnidade__c = 8,
            IsActive = true
        );
        insert product;
        return product;
    }

    private static Product2 createTestProduct(Empreendimento__c empreendimento, Bloco__c bloco) {
        Product2 unidade = new Product2(
            Name = 'Nome do Produto do Apartamento',
            ProductCode = '854785964',
            ExternalId = '10',
            Empreendimento__c = empreendimento.Id,
            Bloco__c = bloco.Id,
            NumeroDaUnidade__c = 10,
            ValorM2__c = 8
        );
        insert unidade;
        return unidade;
    }

    private static PricebookEntry createTestPricebookEntry(Product2 product, Id pricebookId) {
        PricebookEntry pricebookEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = product.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert pricebookEntry;
        return pricebookEntry;
    }
}