force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/DentroHorarioFuncionamento__c.field-meta.xml
<CustomField>
    <fullName>DentroHorarioFuncionamento__c</fullName>
    <description>Indica se a roleta está dentro do horário de funcionamento ou não, considerando
		dias da semana.</description>
    <formula>AND(
		OR(
		AND(WEEKDAY(TODAY()) = 1, INCLUDES(DiasSemana__c, &apos;Domingo&apos;)),
		AND(WEEKDAY(TODAY()) = 2, INCLUDES(DiasSemana__c, &apos;Segunda-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 3, INCLUDES(DiasSemana__c, &apos;Terça-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 4, INCLUDES(DiasSemana__c, &apos;Quarta-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 5, INCLUDES(DiasSemana__c, &apos;Quinta-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 6, INCLUDES(DiasSemana__c, &apos;Sexta-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 7, INCLUDES(DiasSemana__c, &apos;Sábado&apos;))
		),
		(NOW() - (3/24)) &gt;= (DATETIMEVALUE(TEXT(YEAR(TODAY())) + &apos;-&apos; + TEXT(MONTH(TODAY())) + &apos;-&apos; + TEXT(DAY(TODAY())) + &apos; &apos; + TEXT(HOUR(HoraInicio__c)) + &apos;:&apos; + TEXT(MINUTE(HoraInicio__c)) + &apos;:00&apos;)),
		(NOW() - (3/24)) &lt;= (DATETIMEVALUE(TEXT(YEAR(TODAY())) + &apos;-&apos; + TEXT(MONTH(TODAY())) + &apos;-&apos; + TEXT(DAY(TODAY())) + &apos; &apos; + TEXT(HOUR(HoraFim__c)) + &apos;:&apos; + TEXT(MINUTE(HoraFim__c)) + &apos;:00&apos;))
		)</formula>
    <inlineHelpText>Indica se a roleta está dentro do horário de funcionamento ou não, considerando
		dias da semana.</inlineHelpText>
    <label>Dentro do horário de funcionamento?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/DiasSemana__c.field-meta.xml
<CustomField>
    <fullName>DiasSemana__c</fullName>
    <description>Indica em quais dias da semana podem ser realizadas distribuições de lead para a
        roleta</description>
    <inlineHelpText>Selecione os dias da semana para a distribuição de leads na roleta.</inlineHelpText>
    <label>Dias da semana</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiasSemana</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/HoraFim__c.field-meta.xml
<CustomField>
    <fullName>HoraFim__c</fullName>
    <description>Indica o horário de término das distribuições de lead para a roleta.</description>
    <label>Hora de fim</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>HoraInicio__c</fullName>
    <description>Indica o horário de início para as distribuições de lead para a roleta.</description>
    <label>Hora de início</label>
    <type>Time</type>
</CustomField>

force-app/main/default/globalValueSets/DiasSemana.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domingo</fullName>
    </customValue>
    <customValue>
        <fullName>Segunda-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Terça-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quarta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quinta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sexta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sábado</fullName>
    </customValue>
    <masterLabel>Dias da semana</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RoletaLeadsHelperTest.cls
@isTest
public class RoletaLeadsHelperTest {
    
    @testSetup
    static void setup() {
        // Configuração das roletas com horários que garantem estar dentro do horário de funcionamento
        RoletaLeads__c roleta1 = new RoletaLeads__c(
            Name = 'Roleta Teste 1',
            HoraInicio__c = Time.newInstance(0, 0, 0, 0),
            HoraFim__c = Time.newInstance(23, 59, 0, 0),
            Ativa__c = true,
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira;Sábado'
        );

        RoletaLeads__c roleta2 = new RoletaLeads__c(
            Name = 'Roleta Teste 2',
            HoraInicio__c = Time.newInstance(0, 0, 0, 0),
            HoraFim__c = Time.newInstance(23, 59, 0, 0),
            Ativa__c = true,
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira;Sábado'
        );

        // Roleta inativa, que não deverá ter job agendado
        RoletaLeads__c roleta3 = new RoletaLeads__c(
            Name = 'Roleta Teste 3',
            HoraInicio__c = Time.newInstance(0, 0, 0, 0),
            HoraFim__c = Time.newInstance(23, 59, 0, 0),
            Ativa__c = false,
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira;Sábado'
        );

        insert new List<RoletaLeads__c>{roleta1, roleta2, roleta3};
    }

    @isTest
    static void testScheduleRoletaCleanUp() {
        // Buscar os registros de roleta criados no setup
        List<RoletaLeads__c> roletaList = [SELECT Id, Name, HoraFim__c, Ativa__c, DentroHorarioFuncionamento__c 
                                           FROM RoletaLeads__c];

       
        for (RoletaLeads__c roleta : roletaList) {
            System.debug('Roleta: ' + roleta.Name + ', DentroHorarioFuncionamento__c: ' + roleta.DentroHorarioFuncionamento__c);
        }

       
        System.assertEquals(3, roletaList.size(), 'A quantidade de registros de roleta criados deveria ser 3.');

        
        Test.startTest();
        RoletaLeadsHelper.scheduleRoletaCleanUp(roletaList);
        Test.stopTest();

        
        Integer scheduledJobsCount = [SELECT COUNT() FROM CronTrigger WHERE CronJobDetail.Name LIKE 'Limpar Participantes da Roleta%'];
        
    
    }
}