force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>HoraInicio__c</fullName>
    <description>Indica o horário de início para as distribuições de lead para a roleta.</description>
    <label>Hora de início</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/LeadsBolsaoScheduler.cls
public class LeadsBolsaoScheduler implements Schedulable {
    public void execute(SchedulableContext sc) {
        List<RoletaLeads__c> listaRoletas = [SELECT Id, HoraInicio__c FROM RoletaLeads__c WHERE Ativa__c = true];
        
        Time horaInicio = System.now().time(); 
        RoletaLeadsHelper.LeadsBolsaoHorarioAgendado(listaRoletas, horaInicio);
    }

    public static void scheduleDailyJobs() {
        String[] jobNames = new String[]{
            'DailyLeadsBolsaoJob_0915','DailyLeadsBolsaoJob_1500',
            'DailyLeadsBolsaoJob_1800'
        };

        String[] cronExpressions = new String[]{
            '0 15 9 * * ?','0 0 15 * * ?',
            '0 0 18 * * ?'
        };

        for (Integer i = 0; i < jobNames.size(); i++) {
            List<CronTrigger> existingJobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :jobNames[i]];

            if (existingJobs.isEmpty()) {
                try {
                    System.schedule(jobNames[i], cronExpressions[i], new LeadsBolsaoScheduler());
                } catch (Exception e) {
                    System.debug('Erro ao agendar o job: ' + jobNames[i] + ' - ' + e.getMessage());
                }
            }
        }

        String cleanUpJobName = 'DailyRoletaCleanUpJob';
        String cleanUpCronExpression = '0 55 23 * * ?';

        List<CronTrigger> existingCleanUpJobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :cleanUpJobName];
        if (existingCleanUpJobs.isEmpty()) {
            try {
                System.schedule(cleanUpJobName, cleanUpCronExpression, new RoletaCleanUpScheduler());
            } catch (Exception e) {
                System.debug('Erro ao agendar o job de limpeza: ' + e.getMessage());
            }
        }
    }
}