force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/DiasSemana__c.field-meta.xml
<CustomField>
    <fullName>DiasSemana__c</fullName>
    <description>Indica em quais dias da semana podem ser realizadas distribuições de lead para a
        roleta</description>
    <inlineHelpText>Selecione os dias da semana para a distribuição de leads na roleta.</inlineHelpText>
    <label>Dias da semana</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiasSemana</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/HoraFim__c.field-meta.xml
<CustomField>
    <fullName>HoraFim__c</fullName>
    <description>Indica o horário de término das distribuições de lead para a roleta.</description>
    <label>Hora de fim</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>HoraInicio__c</fullName>
    <description>Indica o horário de início para as distribuições de lead para a roleta.</description>
    <label>Hora de início</label>
    <type>Time</type>
</CustomField>

force-app/main/default/globalValueSets/DiasSemana.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domingo</fullName>
    </customValue>
    <customValue>
        <fullName>Segunda-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Terça-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quarta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quinta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sexta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sábado</fullName>
    </customValue>
    <masterLabel>Dias da semana</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RoletaLeadsDATest.cls
@isTest
private class RoletaLeadsDATest {
    
    @isTest
    static void testLimparParticipantesRoleta() {
      
          RoletaLeads__c roleta = new RoletaLeads__c(
            Name = 'Roleta Teste Limpar Participantes',
            HoraInicio__c = Time.newInstance(0, 0, 0, 0),
            HoraFim__c = Time.newInstance(23, 59, 0, 0),
            Ativa__c = false,
            DiasSemana__c = 'Domingo;Segunda-feira;Segunda-feira;Quarta-feira;Quinta-feira;Sexta-feira;Sábado'
        );
  
        insert roleta;
        
        
        List<ParticipanteRoleta__c> participantes = new List<ParticipanteRoleta__c>();
        participantes.add(new ParticipanteRoleta__c(RoletaLeads__c = roleta.Id));
        participantes.add(new ParticipanteRoleta__c(RoletaLeads__c = roleta.Id));
        insert participantes;
        
        Test.startTest();
       
        RoletaLeadsDA.limparParticipantesRoleta(roleta.Id);
        Test.stopTest();
        
     
        List<ParticipanteRoleta__c> participantesExistentes = [SELECT Id FROM ParticipanteRoleta__c WHERE RoletaLeads__c = :roleta.Id];
        System.assertEquals(0, participantesExistentes.size(), 'Deveria ter excluído todos os participantes associados à roleta.');
    }
}