you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>UsuarioCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário do Corretor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Equipe__c/Equipe__c.object-meta.xml
<CustomObject>
    <description>Agrupa os responsáveis pelo atendimento dos leads distribuídos por
        roleta</description>
    <label>Equipe</label>
    <nameField>
        <label>Nome da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipe__c/fields/CargaMaxima__c.field-meta.xml
<CustomField>
    <fullName>CargaMaxima__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Carga máxima</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/MembroEquipe__c.object-meta.xml
<CustomObject>
    <description>Vincula um usuário responsável pelo atendimento dos leads a uma equipe de roleta de
        leads</description>
    <label>Membro da equipe</label>
    <nameField>
        <label>Nome do membro da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros da equipe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

you/force-app/main/default/objects/MembroEquipe__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipLabel>Membros da equipe</relationshipLabel>
    <relationshipName>MembrosEquipe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MembrosEquipe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/MembroEquipe__c.field-meta.xml
<CustomField>
    <fullName>MembroEquipe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica qual membro da equipe participou da roleta.</description>
    <label>Membro da equipe</label>
    <referenceTo>MembroEquipe__c</referenceTo>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/ParticipanteRoleta__c/fields/Posicao__c.field-meta.xml
<CustomField>
    <fullName>Posicao__c</fullName>
    <description>Indica a posição do participante na fila para distribuição de leads.</description>
    <inlineHelpText>Indica a posição do participante na fila para distribuição de leads.</inlineHelpText>
    <label>Posição</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <description>Indica a situação do usuário no Omnichannel.</description>
    <formula>TEXT(MembroEquipe__r.Usuario__r.Situacao__c)</formula>
    <inlineHelpText>Indica a situação do usuário no Omnichannel.</inlineHelpText>
    <label>Situação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/UsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>UsuarioCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>Participantes_da_roleta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/DiasSemana__c.field-meta.xml
<CustomField>
    <fullName>DiasSemana__c</fullName>
    <description>Indica em quais dias da semana podem ser realizadas distribuições de lead para a
        roleta</description>
    <inlineHelpText>Selecione os dias da semana para a distribuição de leads na roleta.</inlineHelpText>
    <label>Dias da semana</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiasSemana</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Indica a equipe responsável pelo atendimento dos leads distribuídos para a roleta.</description>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipName>RoletasLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>HoraInicio__c</fullName>
    <description>Indica o horário de início para as distribuições de lead para a roleta.</description>
    <label>Hora de início</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/User/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <defaultValue>&apos;Offline&apos;</defaultValue>
    <label>Situação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SituacoesParticipantes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CanaisAtendimento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fale conosco</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Telefone</fullName>
    </customValue>
    <customValue>
        <fullName>Loja</fullName>
    </customValue>
    <customValue>
        <fullName>Stand</fullName>
    </customValue>
    <masterLabel>Canais de atendimento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DiasSemana.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domingo</fullName>
    </customValue>
    <customValue>
        <fullName>Segunda-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Terça-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quarta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quinta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sexta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sábado</fullName>
    </customValue>
    <masterLabel>Dias da semana</masterLabel>
</GlobalValueSet>

you/force-app/main/default/globalValueSets/SituacoesParticipantes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Indisponível</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Situações dos participantes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RoletaCleanUpSchedulerTest.cls
@isTest
public class RoletaCleanUpSchedulerTest {
    @testSetup
    static void setup() {
        // Criar usuários
        User user1 = new User(Alias = 'user1', Email = 'user1@test.com', 
            EmailEncodingKey = 'UTF-8', LastName = 'Test', LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', ProfileId = UserInfo.getProfileId(), 
            TimeZoneSidKey = 'America/Los_Angeles', 
            CompanyName = 'You',
            Username = 'user1_' + System.currentTimeMillis() + '@test.com',
            Situacao__c = 'Online');
                
        User user2 = new User(Alias = 'user2', Email = 'user2@test.com', 
            EmailEncodingKey = 'UTF-8', LastName = 'Test', LanguageLocaleKey = 'en_US', 
            LocaleSidKey = 'en_US', ProfileId = UserInfo.getProfileId(), 
            TimeZoneSidKey = 'America/Los_Angeles', 
            Username = 'user2_' + System.currentTimeMillis() + '@test.com',
            CompanyName = 'You',
            Situacao__c = 'Offline');
        
        insert new List<User>{user1, user2};

        // Criar equipes
        Equipe__c equipe1 = new Equipe__c(Name = 'Equipe 1', CargaMaxima__c = 100);
        Equipe__c equipe2 = new Equipe__c(Name = 'Equipe 2', CargaMaxima__c = 100);
        insert new List<Equipe__c>{equipe1, equipe2};

        // Criar membros da equipe
        MembroEquipe__c membro1 = new MembroEquipe__c(Name = 'Jéssica BM', Equipe__c = equipe1.Id, Usuario__c = user1.Id);
        MembroEquipe__c membro2 = new MembroEquipe__c(Name = 'Corretor 1', Equipe__c = equipe2.Id, Usuario__c = user2.Id);
        MembroEquipe__c membro3 = new MembroEquipe__c(Name = 'Teste Corretor', Equipe__c = equipe1.Id, Usuario__c = user1.Id);
        insert new List<MembroEquipe__c>{membro1, membro2, membro3};

        // Criar roleta
        RoletaLeads__c roletaLeads = new RoletaLeads__c(
            Name = 'Roleta - Equipe 0',
            Ativa__c = true,
            HoraInicio__c = Datetime.now().time(),
            CanaisAtendimento__c = 'WhatsApp',
            Equipe__c = equipe1.Id,
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira;Sábado'
        );
        insert roletaLeads;

        // Criar contato
        Contact corretor1 = new Contact(
            FirstName = 'Pereira Lucas', 
            LastName = 'Silva',
            CPF__c = '10695957058'
        );
        insert corretor1;

        // Criar participantes da roleta
        ParticipanteRoleta__c participante1 = new ParticipanteRoleta__c(
            Name = 'Lucas',
            MembroEquipe__c = membro1.Id,
            RoletaLeads__c = roletaLeads.Id,
            Posicao__c = 1,
            UsuarioCorretor__c = corretor1.Id 
        );
        ParticipanteRoleta__c participante2 = new ParticipanteRoleta__c(
            Name = 'Ewerton',
            MembroEquipe__c = membro1.Id,
            RoletaLeads__c = roletaLeads.Id,
            Posicao__c = 5,
            UsuarioCorretor__c = corretor1.Id 
        );
        ParticipanteRoleta__c participante3 = new ParticipanteRoleta__c(
            Name = 'Luan',
            MembroEquipe__c = membro2.Id,
            RoletaLeads__c = roletaLeads.Id,
            Posicao__c = 5,
            UsuarioCorretor__c = corretor1.Id 
        );
        insert new List<ParticipanteRoleta__c>{participante1, participante2, participante3};
    }

    @isTest
    static void testExecute() {
        // Verificar se os participantes foram criados
        List<ParticipanteRoleta__c> participantesAntes = [SELECT Id FROM ParticipanteRoleta__c];
      //	  System.assert(participantesAntes.size() > 0, 'Os participantes devem estar presentes antes da execução do job.');

        // Agendar o job
        String cronExp = '0 0 0 1 1 ? 2050'; // Agendando para uma data futura para simular o job
        System.schedule('Test RoletaCleanUpScheduler', cronExp, new RoletaCleanUpScheduler());

        // Executar o job
        Test.startTest();
        // Executa o job que foi agendado
        CronTrigger ct = [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name = 'Test RoletaCleanUpScheduler'];
        System.abortJob(ct.Id);
        Test.stopTest();

        // Verificar se os participantes foram excluídos
    //    List<ParticipanteRoleta__c> participantesDepois = [SELECT Id FROM ParticipanteRoleta__c];
        //System.assertEquals(0, participantesDepois.size(), 'Os participantes devem ser excluídos após a execução do job.');
    }
}