you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DatadeVencimento__c.field-meta.xml
<CustomField>
    <fullName>DatadeVencimento__c</fullName>
    <description>Deve ser preenchido
com a data de vencimento do
CRECI.</description>
    <label>Data de Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipe__c/Equipe__c.object-meta.xml
<CustomObject>
    <description>Agrupa os responsáveis pelo atendimento dos leads distribuídos por
        roleta</description>
    <label>Equipe</label>
    <nameField>
        <label>Nome da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a roleta de leads para onde o lead foi distribuído.</description>
    <inlineHelpText>Indica a roleta de leads para onde o lead foi distribuído.</inlineHelpText>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/MembroEquipe__c.object-meta.xml
<CustomObject>
    <description>Vincula um usuário responsável pelo atendimento dos leads a uma equipe de roleta de
        leads</description>
    <label>Membro da equipe</label>
    <nameField>
        <label>Nome do membro da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros da equipe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

you/force-app/main/default/objects/MembroEquipe__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipLabel>Membros da equipe</relationshipLabel>
    <relationshipName>MembrosEquipe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MembrosEquipe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Entrada__c.field-meta.xml
<CustomField>
    <fullName>Entrada__c</fullName>
    <description>Indica o momento de entrada do participante da roleta.</description>
    <label>Entrada</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/MembroEquipe__c.field-meta.xml
<CustomField>
    <fullName>MembroEquipe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica qual membro da equipe participou da roleta.</description>
    <label>Membro da equipe</label>
    <referenceTo>MembroEquipe__c</referenceTo>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <description>Indica a situação do usuário no Omnichannel.</description>
    <formula>TEXT(MembroEquipe__r.Usuario__r.Situacao__c)</formula>
    <inlineHelpText>Indica a situação do usuário no Omnichannel.</inlineHelpText>
    <label>Situação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/DiasSemana__c.field-meta.xml
<CustomField>
    <fullName>DiasSemana__c</fullName>
    <description>Indica em quais dias da semana podem ser realizadas distribuições de lead para a
        roleta</description>
    <inlineHelpText>Selecione os dias da semana para a distribuição de leads na roleta.</inlineHelpText>
    <label>Dias da semana</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiasSemana</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Indica a equipe responsável pelo atendimento dos leads distribuídos para a roleta.</description>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipName>RoletasLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>HoraInicio__c</fullName>
    <description>Indica o horário de início para as distribuições de lead para a roleta.</description>
    <label>Hora de início</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/User/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <defaultValue>&apos;Offline&apos;</defaultValue>
    <label>Situação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SituacoesParticipantes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CanaisAtendimento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fale conosco</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Telefone</fullName>
    </customValue>
    <customValue>
        <fullName>Loja</fullName>
    </customValue>
    <customValue>
        <fullName>Stand</fullName>
    </customValue>
    <masterLabel>Canais de atendimento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DiasSemana.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domingo</fullName>
    </customValue>
    <customValue>
        <fullName>Segunda-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Terça-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quarta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quinta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sexta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sábado</fullName>
    </customValue>
    <masterLabel>Dias da semana</masterLabel>
</GlobalValueSet>

you/force-app/main/default/globalValueSets/SituacoesParticipantes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Indisponível</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Situações dos participantes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AtualizarLeadBolsaoJobTest.cls
@isTest
public class AtualizarLeadBolsaoJobTest {

    @isTest
    static void testLeadClonagem() {
        // Criando um Empreendimento
        Empreendimento__c empreendimento = new Empreendimento__c();  
        empreendimento.Name = 'Teste empreendimento';  
        empreendimento.CNPJEmpreendimento__c = '12345678000195';  
        insert empreendimento;

        // Criando um Lead para teste
        Lead testLead = new Lead(
            LastName = 'Ewerton Lima',
            Company = 'Ewerton Empresa',
            Email = 'ewertonzorolima@gmail.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Telefone',
            MobilePhone = '5511989062680',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id
        );
        insert testLead;

        // Criando o Lead duplicado para testar clonagem
        Lead duplicateLead = new Lead(
            LastName = 'Silva',
            Company = 'Empresa XYZ',
            Email = 'silva@xyz.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Telefone',
            MobilePhone = '5511987654321',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id
        );
        insert duplicateLead;

        // Criando a instância de RoletaLeads com a estrutura fornecida
        RecordType recordTypeCorretor = [SELECT Id, Name FROM RecordType WHERE Name = 'Corretor' LIMIT 1];
        Id perfilAdministradorSistema = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator'].id;
        
        // Criando e inserindo um Contact
        Contact ctt = new Contact(
            LastName = 'Jorge',
            DatadeVencimento__c = Date.today(),
            Cpf__c = '18875199043',
            RecordTypeId = recordTypeCorretor.Id
        );
        insert ctt;

        // Atualizando o Contact (seguindo a estrutura fornecida)
        update ctt;

        // Criando usuários para a roleta
        List<User> usuarios = new List<User>{
            new User(
                Alias = 'usuario1',
                Email = 'usuario1@example.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'User1',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'novoteste@example.com',
                ProfileId = perfilAdministradorSistema,
                Situacao__c = 'Online'
            ),
            new User(
                Alias = 'usuario2',
                Email = 'usuario2@example.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'User2',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'salada1@example.com',
                ProfileId = perfilAdministradorSistema,
                Situacao__c = 'Online'
            )
        };
        insert usuarios;

        // Criando e inserindo a Equipe
        Equipe__c equipe = new Equipe__c();
        insert equipe;

        // Criando membros para a Equipe
        List<MembroEquipe__c> membrosEquipes = new List<MembroEquipe__c>{
            new MembroEquipe__c(
                Name = 'Equipe A',
                Equipe__c = equipe.Id,
                Usuario__c = usuarios.get(0).Id
            ),
            new MembroEquipe__c(
                Name = 'Equipe B',
                Equipe__c = equipe.Id,
                Usuario__c = usuarios.get(1).Id
            )
        };
        insert membrosEquipes;

        // Criando a RoletaLeads
        RoletaLeads__c roletaLeads = new RoletaLeads__c(
            Name = 'Roleta - Equipe 0',
            Ativa__c = true,
            HoraInicio__c = Datetime.now().time(),
            CanaisAtendimento__c = 'WhatsApp',
            Equipe__c = equipe.Id,
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira;Sábado'
        );
        insert roletaLeads;

        // Criando o participante da roleta
        ParticipanteRoleta__c participante = new ParticipanteRoleta__c(
            Entrada__c = System.now(),
            MembroEquipe__c = membrosEquipes.get(0).Id,
            RoletaLeads__c = roletaLeads.Id
        );
        insert participante;

        // Atualizando o campo RoletaLeads__c nos Leads
        testLead.RoletaLeads__c = roletaLeads.Id;
        duplicateLead.RoletaLeads__c = roletaLeads.Id;
        update new List<Lead>{testLead, duplicateLead};

        // Executando o job
        Test.startTest();
        AtualizarLeadBolsaoJob job = new AtualizarLeadBolsaoJob(roletaLeads.Id);
        System.schedule('Test Lead Clonagem Job', '0 0 0 1 1 ?', job);
        Test.stopTest();

    }

    @isTest
    static void testLeadsSemDuplicidade() {
        // Criando um Empreendimento
        Empreendimento__c empreendimento = new Empreendimento__c();  
        empreendimento.Name = 'Teste empreendimento 2';  
        empreendimento.CNPJEmpreendimento__c = '98765432000195';  
        insert empreendimento;

        // Criando um Lead sem duplicidade
        Lead testLead = new Lead(
            LastName = 'Souza',
            Company = 'Empresa ABC',
            Email = 'souza@abc.com',
            LeadSource = 'WhatsApp',
            CanalAtendimento__c = 'WhatsApp',
            MobilePhone = '5511987654322',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id
        );
        insert testLead;

        // Criando a instância de RoletaLeads para a busca
        RecordType recordTypeCorretor = [SELECT Id, Name FROM RecordType WHERE Name = 'Corretor' LIMIT 1];
        Id perfilAdministradorSistema = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator'].id;
        
        // Criando o Lead para a roleta
        Contact ctt = new Contact(
            LastName = 'Maria',
            DatadeVencimento__c = Date.today(),
            Cpf__c = '12345678901',
            RecordTypeId = recordTypeCorretor.Id
        );
        insert ctt;

        // Atualizando o Contact
        update ctt;

        // Criando usuários para a roleta
        List<User> usuarios = new List<User>{
            new User(
                Alias = 'testesal',
                Email = 'testesalada@example.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'User1',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'salad3nha@gmail.com',
                ProfileId = perfilAdministradorSistema,
                Situacao__c = 'Online'
            )
        };
        insert usuarios;

        // Criando a Equipe e a Roleta
        Equipe__c equipe = new Equipe__c();
        insert equipe;

        // Criando o membro da Equipe
        MembroEquipe__c membroEquipe = new MembroEquipe__c(
            Name = 'Equipe 1',
            Equipe__c = equipe.Id,
            Usuario__c = usuarios.get(0).Id
        );
        insert membroEquipe;

        RoletaLeads__c roletaLeads = new RoletaLeads__c(
            Name = 'Roleta - Equipe 1',
            Ativa__c = true,
            HoraInicio__c = Datetime.now().time(),
            CanaisAtendimento__c = 'WhatsApp',
            Equipe__c = equipe.Id,
            DiasSemana__c = 'Segunda-feira;Terça-feira'
        );
        insert roletaLeads;

        // Criando o participante da roleta
        ParticipanteRoleta__c participante = new ParticipanteRoleta__c(
            Entrada__c = System.now(),
            MembroEquipe__c = membroEquipe.Id,
            RoletaLeads__c = roletaLeads.Id
        );
        insert participante;

        // Atualizando o campo RoletaLeads__c no Lead
        testLead.RoletaLeads__c = roletaLeads.Id;
        update testLead;

        // Executando o job
        Test.startTest();
        AtualizarLeadBolsaoJob job = new AtualizarLeadBolsaoJob(roletaLeads.Id);
        System.schedule('Test Lead Clonagem Job', '0 0 0 1 1 ?', job);
        Test.stopTest();
    }
}