you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CRECIAtivo__c.field-meta.xml
<CustomField>
    <fullName>CRECIAtivo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CRECI Ativo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DatadeVencimento__c.field-meta.xml
<CustomField>
    <fullName>DatadeVencimento__c</fullName>
    <description>Deve ser preenchido
com a data de vencimento do
CRECI.</description>
    <label>Data de Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusCorretor__c.field-meta.xml
<CustomField>
    <fullName>StatusCorretor__c</fullName>
    <label>Status Corretor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Desligado</fullName>
            </value>
            <value>
                <fullName>Em processo</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusUsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>StatusUsuarioCorretor__c</fullName>
    <label>Status usuário do corretor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Desativado</fullName>
            </value>
            <value>
                <fullName>Congelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Cliente.recordType-meta.xml
<RecordType>
    <fullName>Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/classes/ContatoHelper.cls
public with sharing class ContatoHelper{

    public static void verifyCPF(List<Contact> contacts) {

        Id recordTypeCliente = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Cliente').getRecordTypeId();
    
        for (Contact contact : contacts) {
            if (contact.RecordTypeId == recordTypeCliente) {
                if (String.isNotBlank(contact.CPF__c) && !ValidarCPF.validarCPF(contact.CPF__c)) {
                    contact.addError('CPF inválido. Por favor, insira um CPF válido. O CPF deve ser preenchido com 11 dígitos corridos');
                }
            } else {
                System.debug('Não é um cliente, portanto não valida o CPF.');
            }
        }
    }
    
    

    public static void handleStatusCorretor(List<Contact> contacts) {
        for (Contact contact : contacts) {
            if (contact.StatusUsuarioCorretor__c == 'Congelado') {
                contact.StatusCorretor__c = 'Suspenso';
            } else if (contact.StatusUsuarioCorretor__c == 'Desativado') {
                contact.StatusCorretor__c = 'Desligado';
            }
        }
    }

    public static void handleCRECIStatus(List<Contact> contacts) {
        Date dataAtual = Date.today();
        
        for (Contact contact : contacts) {
            if (contact.DatadeVencimento__c != null) {                
                if (contact.DatadeVencimento__c >= dataAtual) {
                    contact.CRECIAtivo__c = true;
                } else {
                    contact.CRECIAtivo__c = false;
                }
            }
        }
    }
}