you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusCorretor__c.field-meta.xml
<CustomField>
    <fullName>StatusCorretor__c</fullName>
    <label>Status Corretor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Desligado</fullName>
            </value>
            <value>
                <fullName>Em processo</fullName>
            </value>
            <value>
                <fullName>Suspenso</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/StatusUsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>StatusUsuarioCorretor__c</fullName>
    <label>Status usuário do corretor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Desativado</fullName>
            </value>
            <value>
                <fullName>Congelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateStatusCorretorTest.cls
@isTest
public class UpdateStatusCorretorTest {

    @isTest
    static void testUpdateStatusCorretor() {
        Contact contact1 = new Contact(LastName = 'Teste1', StatusUsuarioCorretor__c = 'Congelado' , CPF__c = '54092472056');
        insert contact1;
        contact1 = [SELECT StatusCorretor__c FROM Contact WHERE Id = :contact1.Id];

        Contact contact2 = new Contact(LastName = 'Teste2', StatusUsuarioCorretor__c = 'Desativado' , CPF__c = '83519292041');
        insert contact2;
        contact2 = [SELECT StatusCorretor__c FROM Contact WHERE Id = :contact2.Id];

        Contact contact3 = new Contact(LastName = 'Teste3', StatusUsuarioCorretor__c = 'Ativo' , CPF__c = '75644131076');
        insert contact3;
        contact3 = [SELECT StatusCorretor__c FROM Contact WHERE Id = :contact3.Id];

        contact3.StatusUsuarioCorretor__c = 'Congelado';
        update contact3;
        contact3 = [SELECT StatusCorretor__c FROM Contact WHERE Id = :contact3.Id];

        contact3.StatusUsuarioCorretor__c = 'Desativado';
        update contact3;
        contact3 = [SELECT StatusCorretor__c FROM Contact WHERE Id = :contact3.Id];
    }
}