force-app/main/default/objects/Quote/fields/DiferencaNominalPorcentagem__c.field-meta.xml
<CustomField>
    <fullName>DiferencaNominalPorcentagem__c</fullName>
    <label>Diferença Nominal (%)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DiferencaNominalReal__c.field-meta.xml
<CustomField>
    <fullName>DiferencaNominalReal__c</fullName>
    <label>Diferença Nominal (R$)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DiferencaVPLPorcentagem__c.field-meta.xml
<CustomField>
    <fullName>DiferencaVPLPorcentagem__c</fullName>
    <label>Diferença VPL (%)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DiferencaVPLReal__c.field-meta.xml
<CustomField>
    <fullName>DiferencaVPLReal__c</fullName>
    <label>Diferença VPL (R$)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PorcentagemCaptacaoProposta__c.field-meta.xml
<CustomField>
    <fullName>PorcentagemCaptacaoProposta__c</fullName>
    <label>Porcentagem Captação à vista Proposta</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/Quote/fields/ValorNominalProposta__c.field-meta.xml
<CustomField>
    <fullName>ValorNominalProposta__c</fullName>
    <label>Valor Nominal Proposta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ValorNominalTabela__c.field-meta.xml
<CustomField>
    <fullName>ValorNominalTabela__c</fullName>
    <label>Valor Nominal Tabela</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ValorVPLProposta__c.field-meta.xml
<CustomField>
    <fullName>ValorVPLProposta__c</fullName>
    <label>Valor VPL Proposta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

you/force-app/main/default/objects/Quote/fields/ValorVPLTabela__c.field-meta.xml
<CustomField>
    <fullName>ValorVPLTabela__c</fullName>
    <label>Valor VPL Tabela</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CotacaoService.cls
public with sharing class CotacaoService {
    public static Quote atualizarCotacaoDaSimulacao(Quote cotacao){
        Quote cotacaoExistente = CotacaoSelector.getQuoteById(cotacao.Id);

        if(cotacaoExistente != null){
            cotacaoExistente.PorcentagemCaptacaoProposta__c = cotacao.PorcentagemCaptacaoProposta__c;
            cotacaoExistente.ValorNominalTabela__c = cotacao.ValorNominalTabela__c;
            cotacaoExistente.ValorNominalProposta__c = cotacao.ValorNominalProposta__c;
            cotacaoExistente.ValorVPLTabela__c = cotacao.ValorVPLTabela__c;
            cotacaoExistente.ValorVPLProposta__c = cotacao.ValorVPLProposta__c;
            cotacaoExistente.DiferencaNominalReal__c = cotacao.DiferencaNominalReal__c;
            cotacaoExistente.DiferencaNominalPorcentagem__c = cotacao.DiferencaNominalPorcentagem__c;
            cotacaoExistente.DiferencaVPLReal__c = cotacao.DiferencaVPLReal__c;
            cotacaoExistente.DiferencaVPLPorcentagem__c = cotacao.DiferencaVPLPorcentagem__c;
            update cotacaoExistente;
        }

        return cotacaoExistente;
    }
}