force-app/main/default/objects/MembroEquipe__c/MembroEquipe__c.object-meta.xml
<CustomObject>
    <description>Vincula um usuário responsável pelo atendimento dos leads a uma equipe de roleta de
        leads</description>
    <label>Membro da equipe</label>
    <nameField>
        <label>Nome do membro da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros da equipe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

you/force-app/main/default/objects/MembroEquipe__c/fields/ExigeValidacaoCoordenador__c.field-meta.xml
<CustomField>
    <fullName>ExigeValidacaoCoordenador__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica necessidade de validação de presença do corretor pelo coordenador para recepção de novos leads.</description>
    <inlineHelpText>Indica necessidade de validação de presença do corretor pelo coordenador para recepção de novos leads.</inlineHelpText>
    <label>Exige validação do coordenador?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MembrosEquipe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/CargaRestante__c.field-meta.xml
<CustomField>
    <fullName>CargaRestante__c</fullName>
    <formula>MembroEquipe__r.Equipe__r.CargaMaxima__c - OcupacaoAtual__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Carga restante</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/MembroEquipe__c.field-meta.xml
<CustomField>
    <fullName>MembroEquipe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica qual membro da equipe participou da roleta.</description>
    <label>Membro da equipe</label>
    <referenceTo>MembroEquipe__c</referenceTo>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/PausarDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>PausarDistribuicao__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se a distribuição de leads está pausada para este participante ou não.</description>
    <inlineHelpText>Indique se a distribuição de leads está pausada para este participante ou não.</inlineHelpText>
    <label>Pausar distribuição</label>
    <type>Checkbox</type>
</CustomField>

you/force-app/main/default/objects/ParticipanteRoleta__c/fields/Posicao__c.field-meta.xml
<CustomField>
    <fullName>Posicao__c</fullName>
    <description>Indica a posição do participante na fila para distribuição de leads.</description>
    <inlineHelpText>Indica a posição do participante na fila para distribuição de leads.</inlineHelpText>
    <label>Posição</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/PresencaValidada__c.field-meta.xml
<CustomField>
    <fullName>PresencaValidada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se a presença do corretor foi validada pelo coordenador para recepção de leads.</description>
    <inlineHelpText>Indica se a presença do corretor foi validada pelo coordenador para recepção de leads.</inlineHelpText>
    <label>Presença validada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RegistroIndisponibilidade__c.field-meta.xml
<CustomField>
    <fullName>RegistroIndisponibilidade__c</fullName>
    <description>Registra a data e hora que o status do participante foi alterado para &quot;Indisponível&apos;.</description>
    <label>Registro de indisponibilidade</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Saida__c.field-meta.xml
<CustomField>
    <fullName>Saida__c</fullName>
    <description>Indica o momento de saída do participante da roleta.</description>
    <label>Saída</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <description>Indica a situação do usuário no Omnichannel.</description>
    <formula>TEXT(MembroEquipe__r.Usuario__r.Situacao__c)</formula>
    <inlineHelpText>Indica a situação do usuário no Omnichannel.</inlineHelpText>
    <label>Situação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/DentroHorarioFuncionamento__c.field-meta.xml
<CustomField>
    <fullName>DentroHorarioFuncionamento__c</fullName>
    <description>Indica se a roleta está dentro do horário de funcionamento ou não, considerando
		dias da semana.</description>
    <formula>AND(
		OR(
		AND(WEEKDAY(TODAY()) = 1, INCLUDES(DiasSemana__c, &apos;Domingo&apos;)),
		AND(WEEKDAY(TODAY()) = 2, INCLUDES(DiasSemana__c, &apos;Segunda-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 3, INCLUDES(DiasSemana__c, &apos;Terça-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 4, INCLUDES(DiasSemana__c, &apos;Quarta-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 5, INCLUDES(DiasSemana__c, &apos;Quinta-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 6, INCLUDES(DiasSemana__c, &apos;Sexta-feira&apos;)),
		AND(WEEKDAY(TODAY()) = 7, INCLUDES(DiasSemana__c, &apos;Sábado&apos;))
		),
		(NOW() - (3/24)) &gt;= (DATETIMEVALUE(TEXT(YEAR(TODAY())) + &apos;-&apos; + TEXT(MONTH(TODAY())) + &apos;-&apos; + TEXT(DAY(TODAY())) + &apos; &apos; + TEXT(HOUR(HoraInicio__c)) + &apos;:&apos; + TEXT(MINUTE(HoraInicio__c)) + &apos;:00&apos;)),
		(NOW() - (3/24)) &lt;= (DATETIMEVALUE(TEXT(YEAR(TODAY())) + &apos;-&apos; + TEXT(MONTH(TODAY())) + &apos;-&apos; + TEXT(DAY(TODAY())) + &apos; &apos; + TEXT(HOUR(HoraFim__c)) + &apos;:&apos; + TEXT(MINUTE(HoraFim__c)) + &apos;:00&apos;))
		)</formula>
    <inlineHelpText>Indica se a roleta está dentro do horário de funcionamento ou não, considerando
		dias da semana.</inlineHelpText>
    <label>Dentro do horário de funcionamento?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <defaultValue>&apos;Offline&apos;</defaultValue>
    <label>Situação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SituacoesParticipantes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CanaisAtendimento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fale conosco</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Telefone</fullName>
    </customValue>
    <customValue>
        <fullName>Loja</fullName>
    </customValue>
    <customValue>
        <fullName>Stand</fullName>
    </customValue>
    <masterLabel>Canais de atendimento</masterLabel>
</GlobalValueSet>

you/force-app/main/default/globalValueSets/SituacoesParticipantes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Indisponível</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Situações dos participantes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ParticipanteRoletaSelector.cls
public without sharing class ParticipanteRoletaSelector {
    public static List<ParticipanteRoleta__c> obterParticipantesPorIdsMembros(Set<Id> idsMembros) {
        return [
            SELECT 
                MembroEquipe__c, 
                MembroEquipe__r.Usuario__r.Situacao__c,
                RegistroIndisponibilidade__c,
                RoletaLeads__c,
                Saida__c 
            FROM ParticipanteRoleta__c 
            WHERE 
                RoletaLeads__r.Ativa__c = true AND 
                RoletaLeads__r.DentroHorarioFuncionamento__c = true AND 
                MembroEquipe__c IN :idsMembros
        ];
    }
    public static List<ParticipanteRoleta__c> obterParticipantesPorIdsRoleta(Set<Id> idsRoletas) {
        if (idsRoletas == null || idsRoletas.isEmpty()) {
            return new List<ParticipanteRoleta__c>(); 
        }
    
        List<ParticipanteRoleta__c> participantes = [
            SELECT RoletaLeads__c, Posicao__c, MembroEquipe__c, Saida__c, RegistroIndisponibilidade__c 
            FROM ParticipanteRoleta__c 
            WHERE RoletaLeads__c IN :idsRoletas
        ];
    
        return participantes;
    }
    
    public static List<ParticipanteRoleta__c> obterParticipantesPorIds(Set<Id> idsParticipantes) {
        if (idsParticipantes == null || idsParticipantes.isEmpty()) {
            return new List<ParticipanteRoleta__c>(); // Retorna uma lista vazia se não houver IDs
        }
    
        List<ParticipanteRoleta__c> participantes = [
            SELECT 
                MembroEquipe__c, 
                MembroEquipe__r.ExigeValidacaoCoordenador__c, 
                MembroEquipe__r.Usuario__r.CanaisAtendimento__c, 
                Situacao__c, 
                MembroEquipe__r.Usuario__c,
                MembroEquipe__r.Usuario__r.ContactId,
                CargaRestante__c, 
                PausarDistribuicao__c, 
                PresencaValidada__c, 
                RoletaLeads__c 
            FROM ParticipanteRoleta__c 
            WHERE Id IN :idsParticipantes
        ];
    
        return participantes;
    }
    

    public static List<ParticipanteRoleta__c> obterParticipantesPorUserID(Id userId) {
        return [SELECT  RoletaLeads__c, Posicao__c, MembroEquipe__c,MembroEquipe__r.Usuario__c FROM ParticipanteRoleta__c WHERE MembroEquipe__r.Usuario__c =: userId];
    }
}