force-app/main/default/objects/Checklist_de_Documentos__c/Checklist_de_Documentos__c.object-meta.xml
<CustomObject>
    <label>Checklist de Documentos</label>
    <nameField>
        <label>Nome de Checklist de Documentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Documenta_o__c.field-meta.xml
<CustomField>
    <fullName>Documenta_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentação</label>
    <referenceTo>Documentacao__c</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Nome_do_Documento__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Documento__c</fullName>
    <label>Nome do Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>UsuarioCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário do Corretor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <description>Documentação de contato</description>
    <label>Documentação</label>
    <nameField>
        <label>Nome de Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Documentacao__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Documentações</relationshipLabel>
    <relationshipName>Documentacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Entregue__c.field-meta.xml
<CustomField>
    <fullName>Entregue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entregue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__mdt/Documento__mdt.object-meta.xml
<CustomObject>
    <label>Documento (Configuracao)</label>
    <pluralLabel>Documentacao</pluralLabel>
</CustomObject>

force-app/main/default/objects/Documento__mdt/fields/Nome_do_Documento__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Documento__c</fullName>
    <label>Nome do Documento</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Documento__mdt/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatorio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__mdt/fields/Papel__c.field-meta.xml
<CustomField>
    <fullName>Papel__c</fullName>
    <label>Papel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprador</fullName>
                <default>true</default>
                <label>Comprador</label>
            </value>
            <value>
                <fullName>Fiador</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
            <value>
                <fullName>Procurador</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor (Contato)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Id</field>
            <operation>equals</operation>
            <value>012bL0000003bkfQAA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Data_Assinatura_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Data_Assinatura_Contrato__c</fullName>
    <label>Data Assinatura Contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FarolChecklistDocumento__c.field-meta.xml
<CustomField>
    <fullName>FarolChecklistDocumento__c</fullName>
    <label>Farol Checklist Documentos</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MotivoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>MotivoCancelamento__c</fullName>
    <label>Motivo Do Cancelamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Motivo da desistência</fullName>
            </value>
            <value>
                <fullName>Aprovação de Crédito</fullName>
            </value>
            <value>
                <fullName>Oferta baixa</fullName>
            </value>
            <value>
                <fullName>Documentação incompleta</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Observacao__c.field-meta.xml
<CustomField>
    <fullName>Observacao__c</fullName>
    <label>Observação</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo De Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negócio existente</fullName>
                <default>true</default>
                <label>Negócio existente</label>
            </value>
            <value>
                <fullName>Negócio novo</fullName>
            </value>
            <value>
                <fullName>Financiamento Bancário</fullName>
                <isActive>false</isActive>
                <label>Financiamento Bancário</label>
            </value>
            <value>
                <fullName>Financiamento Direto</fullName>
                <isActive>false</isActive>
                <label>Financiamento Direto</label>
            </value>
            <value>
                <fullName>Venda a Vista</fullName>
                <isActive>false</isActive>
                <label>Venda a Vista</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DataDeReserva__c.field-meta.xml
<CustomField>
    <fullName>DataDeReserva__c</fullName>
    <description>Campo para estipular quantidade de tempo de reserva de um produto</description>
    <label>Data de reserva</label>
    <type>Date</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enquadramento__c.field-meta.xml
<CustomField>
    <fullName>Enquadramento__c</fullName>
    <label>Enquadramento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>HMP</fullName>
            </value>
            <value>
                <fullName>R2V</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
                <isActive>false</isActive>
                <label>Comercial</label>
            </value>
            <value>
                <fullName>Hotel</fullName>
                <isActive>false</isActive>
                <label>Hotel</label>
            </value>
            <value>
                <fullName>LJ</fullName>
                <isActive>false</isActive>
                <label>LJ</label>
            </value>
            <value>
                <fullName>NR</fullName>
                <isActive>false</isActive>
                <label>NR</label>
            </value>
            <value>
                <fullName>UH</fullName>
                <isActive>false</isActive>
                <label>UH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da unidade</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Disponivel</fullName>
            </value>
            <value>
                <fullName>&lt;&lt;LISTAR STATUS&gt;&gt;</fullName>
                <isActive>false</isActive>
                <label>&lt;&lt;LISTAR STATUS&gt;&gt;</label>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
                <isActive>false</isActive>
                <label>Contrato Assinado</label>
            </value>
            <value>
                <fullName>Contrato Emitido</fullName>
                <isActive>false</isActive>
                <label>Contrato Emitido</label>
            </value>
            <value>
                <fullName>Negociação</fullName>
                <isActive>false</isActive>
                <label>Negociação</label>
            </value>
            <value>
                <fullName>Permuta</fullName>
                <isActive>false</isActive>
                <label>Permuta</label>
            </value>
            <value>
                <fullName>Reserva condicional</fullName>
                <isActive>false</isActive>
                <label>Reserva condicional</label>
            </value>
            <value>
                <fullName>SD Fora de Venda</fullName>
                <isActive>false</isActive>
                <label>SD Fora de Venda</label>
            </value>
            <value>
                <fullName>Venda Integrada</fullName>
                <isActive>false</isActive>
                <label>Venda Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Reportase__c.field-meta.xml
<CustomField>
    <fullName>Reportase__c</fullName>
    <label>Reporta-se à</label>
    <relationshipName>HierarquiaCargo</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/OpportunityHelper.cls
public with sharing class OpportunityHelper {

    private static Map<String, String> mandatoryFields = new Map<String, String>{
        'Amount' => 'Valor da Oportunidade',
        'AccountId' => 'Conta',
        'Name' => 'Nome da Oportunidade',
        'Probability' => 'Probabilidade',
        'CanalAtendimento__c' => 'Canal de Atendimento',
        'TipoVenda__c' => 'Tipo de Venda'
    };

    private static Set<String> validStagesAfterFichaCadastral = new Set<String>{
        'Pré-análise',
        'Geração de Contrato',
        'Conferência',
        'Pagadoria',
        'Ganho'
    };

    

    public static List<Opportunity> getByIds(Set<Id> ids) {
        if (ids == null) throw new IllegalArgumentException('A lista de ids não deve null.');

        List<Opportunity> opps = OpportunityDA.getAllById(ids);
        
        if (opps == null || opps.isEmpty()) throw new IllegalArgumentException('Nenhum registro de opportunidade encontrado.');
        
        return opps;
    }


    public static void addDaysToCloseDateOnCreation(List<Opportunity> newOpps) {
            for (Opportunity opp : newOpps) {
                opp.CloseDate = Date.today().addDays(5);
            }
        }


        public static void validateTransitionToFichaCadastral(List<Opportunity> newOpportunities, Map<Id, Opportunity> oldOpportunitiesMap) {
            for (Opportunity newOpp : newOpportunities) {
                Opportunity oldOpp = oldOpportunitiesMap.get(newOpp.Id);
                
                if (oldOpp.StageName != 'Negociação' || newOpp.StageName != 'Ficha Cadastral') continue;
    
                boolean hasSyncedQuote = OpportunityDA.hasSyncedQuote(newOpp.Id);
                boolean hasProducts = hasProducts(newOpp.Id);
                boolean hasBuyers = hasBuyers(newOpp.Id);
    
                for (String fieldName : mandatoryFields.keySet()) {
                    if (newOpp.get(fieldName) == null || String.isBlank(String.valueOf(newOpp.get(fieldName)))) {
                        newOpp.addError(mandatoryFields.get(fieldName) + ' é um campo obrigatório.');
                    }
                }
    
                if (!hasSyncedQuote || !hasProducts || !hasBuyers) {
                    String errorMessage = 'Não é possível avançar para a Ficha Cadastral:';
                    if (!hasSyncedQuote) {
                        errorMessage += '\n- Favor sincronizar uma cotação com a oportunidade.';
                    }
                    if (!hasProducts) {
                        errorMessage += '\n- Pelo menos um produto da oportunidade deve ser adicionado.';
                    }
                    if (!hasBuyers) {
                        errorMessage += '\n- Pelo menos um comprador (papel de contato) deve ser especificado.';
                    }
                    newOpp.addError(errorMessage);
                }
            }
        }
    
        

    @TestVisible
    private static boolean hasProducts(Id opportunityId) {
        try {
            List<OpportunityLineItem> lineItems = OpportunityDA.getOpportunityLineItems(opportunityId);
            return !lineItems.isEmpty();
        } catch (Exception e) {
            return false;
        }
    }

    @TestVisible
    private static boolean hasBuyers(Id opportunityId) {
        try {
            List<OpportunityContactRole> contactRoles = OpportunityDA.getOpportunityContactRoles(opportunityId);
            return !contactRoles.isEmpty();
        } catch (Exception e) {
            return false;
        }
    }

    public static void handleBeforeUpdate(List<Opportunity> newOpps, Map<Id, Opportunity> oldOpps) {
        for (Opportunity newOpp : newOpps) {
            Opportunity oldOpp = oldOpps.get(newOpp.Id);

            if (!String.isBlank(newOpp.SyncedQuoteId)) {
                Boolean isEmpreendimentoChanged = newOpp.Empreendimento__c != oldOpp.Empreendimento__c;

                if (isEmpreendimentoChanged) {
                    newOpp.addError('Não é possível editar o campo Empreendimento enquanto a oportunidade está sincronizada com uma cotação. Desative a sincronização para editar.');
                }
            }
        }
        
    }
    
    public static void handleStageFichaCadastralChangeFarolColor(
        List<Opportunity> newOpps, Map<Id, Opportunity> oldOppMap
    ) {
        if (newOpps == null || newOpps.isEmpty() || oldOppMap == null || oldOppMap.isEmpty()) {
            throw new IllegalArgumentException('A lista de Oportunidades não deve ser nula ou vazia.');
        }

        Set<Id> oppIdsToProcess = new Set<Id>();
        for (Opportunity newOpp : newOpps) {
            Opportunity oldOpp = oldOppMap.get(newOpp.Id);
            if (oldOpp != null && 'Ficha Cadastral'.equals(oldOpp.StageName)) {
                oppIdsToProcess.add(newOpp.Id);
            }
        }
        if (oppIdsToProcess.isEmpty()) return;

        Map<Id, List<String>> oppToRolesMap = new Map<Id, List<String>>();
        for (OpportunityContactRole cr : [
            SELECT OpportunityId, Role FROM OpportunityContactRole 
            WHERE OpportunityId IN :oppIdsToProcess AND Role != null
        ]) {
            if (!oppToRolesMap.containsKey(cr.OpportunityId)) {
                oppToRolesMap.put(cr.OpportunityId, new List<String>());
            }
            oppToRolesMap.get(cr.OpportunityId).add(cr.Role);
        }

        if(oppToRolesMap.isEmpty()) {
            for (Opportunity opp : newOpps) {
                opp.FarolChecklistDocumento__c = 'Vermelho';
            }
        }


        Map<String, List<Documento__mdt>> roleToDocumentsMap = new Map<String, List<Documento__mdt>>();
        for (Documento__mdt doc : [
            SELECT Nome_do_Documento__c, Obrigatorio__c, Papel__c FROM Documento__mdt
        ]) {
            if (!roleToDocumentsMap.containsKey(doc.Papel__c)) {
                roleToDocumentsMap.put(doc.Papel__c, new List<Documento__mdt>());
            }
            roleToDocumentsMap.get(doc.Papel__c).add(doc);
        }

        Map<Id, List<Checklist_de_Documentos__c>> oppToDocumentsMap = new Map<Id, List<Checklist_de_Documentos__c>>();
        for (Checklist_de_Documentos__c checklistDoc : ChecklistDA.getWithDocumentsByOpportunity(oppIdsToProcess)) {
            if (!oppToDocumentsMap.containsKey(checklistDoc.Oportunidade__c)) {
                oppToDocumentsMap.put(checklistDoc.Oportunidade__c, new List<Checklist_de_Documentos__c>());
            }
            oppToDocumentsMap.get(checklistDoc.Oportunidade__c).add(checklistDoc);
        }
    
        for (Opportunity newOpp : newOpps) {
            if (!oppIdsToProcess.contains(newOpp.Id)) continue;
    
            Integer totalMandatoryCount = 0;
            Integer totalOptionalCount = 0;
    
            List<String> roles = oppToRolesMap.get(newOpp.Id);
            if (roles != null) {
                for (String role : roles) {
                    List<Documento__mdt> documents = roleToDocumentsMap.get(role);
                    if (documents != null) {
                        for (Documento__mdt doc : documents) {
                            if (doc.Obrigatorio__c) {
                                totalMandatoryCount++;
                            } else {
                                totalOptionalCount++;
                            }
                        }
                    }
                }
            }
    
            Integer deliveredMandatoryCount = 0;
            Integer deliveredOptionalCount = 0;
    
            List<Checklist_de_Documentos__c> documents = oppToDocumentsMap.get(newOpp.Id);
            if (documents != null) {
                for (Checklist_de_Documentos__c checklistDoc : documents) {
                    Documentacao__c doc = checklistDoc.Documenta_o__r;
                    if (doc != null && doc.Entregue__c) {
                        if (doc.Obrigatorio__c) {
                            deliveredMandatoryCount++;
                        } else {
                            deliveredOptionalCount++;
                        }
                    }
                }
            }
    
            if (deliveredMandatoryCount < totalMandatoryCount) {
                newOpp.FarolChecklistDocumento__c = 'Vermelho';
            } else if (deliveredMandatoryCount == totalMandatoryCount &&
                       deliveredMandatoryCount + deliveredOptionalCount < totalMandatoryCount + totalOptionalCount) {
                newOpp.FarolChecklistDocumento__c = 'Verde';
            } else if (deliveredMandatoryCount + deliveredOptionalCount == totalMandatoryCount + totalOptionalCount) {
                newOpp.FarolChecklistDocumento__c = 'Azul';
            }
        }
    }    

    public static void setDefaultChecklistStatus(List<Opportunity> opportunities) {
        for (Opportunity opp : opportunities) {
            opp.FarolChecklistDocumento__c = 'Vermelho';
        }
    }

    
    public static void handleStageFichaCadastral(List<Opportunity> newOpps) {
        if (newOpps == null || newOpps.isEmpty()) throw new IllegalArgumentException('A lista de Opportunidade não deve ser nula ou vazia.');

        Set<Id> setOppsId = new Set<Id>();
        for (Opportunity opp : newOpps) {
            if (opp.StageName == null ) throw new IllegalArgumentException('Stage de Oportunidade não deve ser null.');
            if (opp.StageName == 'Pré-análise' && opp.FarolChecklistDocumento__c == 'Vermelho') {
                opp.addError('Na fase de Ficha cadastral, precisamos preencher todos os documentos obrigatório no Checklist de documentos!');
            }
        }
    }

    public static List<Opportunity> getByAnaliseCreditoId(Set<Id> analisesCreditoId ) {
        List<Opportunity> opps = OpportunityDA.getAllByAnaliseCreditoId(analisesCreditoId);
        if (opps.isEmpty()) {
            throw new IllegalArgumentException('Nenhuma Oportunidade encontrada! Ids inválidos.');
        }
        return opps;
    }

    public static void handlePreAnalise(List<Opportunity> newOpps, Map<Id, Opportunity> oldOpps) {

        Set<Id> unidadeIds = new Set<Id>();
        Set<Id> opportunityIds = new Set<Id>();
    
        for (Opportunity newOpp : newOpps) {
            Opportunity oldOpp = oldOpps.get(newOpp.Id);
    
            if (oldOpp != null && oldOpp.StageName != 'Pré-análise' && newOpp.StageName == 'Pré-análise') {
                if (newOpp.Unidade__c != null) {
                    unidadeIds.add(newOpp.Unidade__c);
                }
                opportunityIds.add(newOpp.Id);
            }
        }
    
        List<Product2> oppsUnitys = ProdutoSelector.obterUnidadesPorSetId(unidadeIds);
        List<Checklist_de_Documentos__c> oppDocs = ChecklistDA.getWithDocumentsByOpportunity(opportunityIds);
    
        Map<Id, Product2> unidadeMap = new Map<Id, Product2>();
        for (Product2 unidade : oppsUnitys) {
            unidadeMap.put(unidade.Id, unidade);
        }
    
        Map<Id, List<Checklist_de_Documentos__c>> checklistMap = new Map<Id, List<Checklist_de_Documentos__c>>();
        for (Checklist_de_Documentos__c doc : oppDocs) {
            if (!checklistMap.containsKey(doc.Oportunidade__c)) {
                checklistMap.put(doc.Oportunidade__c, new List<Checklist_de_Documentos__c>());
            }
            checklistMap.get(doc.Oportunidade__c).add(doc);
        }
    
        List<Product2> updatedUnitys = new List<Product2>();
        List<FeedItem> postsChatter = new List<FeedItem>();

        for (Opportunity newOpp : newOpps) {
            Opportunity oldOpp = oldOpps.get(newOpp.Id);
    
            Product2 unity = unidadeMap.get(newOpp.Unidade__c);
    

            if (unity != null) {
                if (unity.Status__c == 'Reservada') {
                    Date dataDeReserva = (unity != null && unity.DataDeReserva__c != null) ? unity.DataDeReserva__c : null;

                    String mensagemChatter; 

                    if(dataDeReserva == null){
                        mensagemChatter = 
                        'A unidade da oportunidade esta reservada. Por favor, analise a situação.';
                    } else {
                        mensagemChatter = 
                        'A unidade permanece reservada até: ' + dataDeReserva.format() + 
                        '. Por favor, avalie a situação.';
                    } 

                    
                    FeedItem post = new FeedItem();
                    post.ParentId = newOpp.Id;
                    post.Body = mensagemChatter;

                    postsChatter.add(post);
                    continue;
                }

                unity.Status__c = 'Reservada';
                updatedUnitys.add(unity);
            }
    
            if (unity != null && unity.Enquadramento__c == 'HIS') {
                List<Checklist_de_Documentos__c> docs = checklistMap.get(newOpp.Id);
    
                if (docs != null && !docs.isEmpty()) {
                    for (Checklist_de_Documentos__c doc : docs) {
                        if (doc.Documenta_o__r.Obrigatorio__c && !doc.Documenta_o__r.Entregue__c) {
                                newOpp.addError('Para prosseguir para a fase de Pré-Análise, é necessário preencher todos os documentos obrigatórios.');
                        }
                    }
                }
            }
        }
 
        if (!postsChatter.isEmpty()) {
            try{
                insert postsChatter;    
            } catch (DmlException e) {
                System.debug('Erro ao inserir mensagem no chatter: ' + e.getMessage());
            }
        }

        
        if (!updatedUnitys.isEmpty()) {
            try {
                update updatedUnitys;
            } catch (DmlException e) {
                System.debug('Erro ao atualizar as unidades: ' + e.getMessage());
                
            }
        }
    }

       /**
 * Este método prepara e envia notificações de cancelamento de oportunidade.
 * As notificações incluem e-mails e mensagens no Chatter para os responsáveis e hierarquias relacionadas
 * quando se move para a fase cancelada na oportunidade.
 */
public static void handleOpportunityCancelation(List<Opportunity> newOpps, Map<Id, Opportunity> oldOpps) {
    List<Opportunity> opportunitiesToNotify = new List<Opportunity>();
    Set<Id> oppIds = new Set<Id>();

    for (Opportunity opp : newOpps) {
        Opportunity oldOpp = oldOpps.get(opp.Id);

        // Verifica se a oportunidade foi movida para a fase de "Cancelado"
        if (opp.StageName == 'Cancelado' && (oldOpp == null || oldOpp.StageName != 'Cancelado')) {
            if (String.isBlank(opp.MotivoCancelamento__c)) {
                opp.addError('O campo Motivo de Cancelamento é obrigatório.');
            } else if (opp.MotivoCancelamento__c == 'Outros' && String.isBlank(opp.Observacao__c)) {
                opp.addError('O campo Observação é obrigatório quando o motivo de cancelamento for "Outros".');
            } else {
                opportunitiesToNotify.add(opp);
                oppIds.add(opp.Id);
            }
        }
    }

    if (!opportunitiesToNotify.isEmpty()) {
        List<Opportunity> oppsWithDetails = [
            SELECT Id, Name, MotivoCancelamento__c, Unidade__c, Unidade__r.Name,
                   Contato__r.Name, Contato__r.Email, Contato__r.OwnerId,
                   Contato__r.UsuarioCorretor__r.Name, Contato__r.UsuarioCorretor__r.Email
             FROM Opportunity
            WHERE Id IN :oppIds
        ];

        Map<Id, Opportunity> oppDetailsMap = new Map<Id, Opportunity>(oppsWithDetails);

        for (Opportunity opp : opportunitiesToNotify) {
            if (oppDetailsMap.containsKey(opp.Id)) {
                Opportunity detailedOpp = oppDetailsMap.get(opp.Id);
                opp.Unidade__c = detailedOpp.Unidade__c;
                opp.Unidade__r = detailedOpp.Unidade__r;
                opp.Contato__r = detailedOpp.Contato__r;
            }
        }

        sendCancelNotification(opportunitiesToNotify);
    }
}




/**
* Este método prepara e envia notificações de cancelamento de oportunidade.
* As notificações incluem e-mails e mensagens no Chatter para os responsáveis e hierarquias relacionadas.
*/

public static void sendCancelNotification(List<Opportunity> opportunitiesToNotify) {
    List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
    List<FeedItem> chatterFeedItems = new List<FeedItem>();
    
  
    EmailTemplate emailTemplate = [SELECT Id, Name, HtmlValue 
                                   FROM EmailTemplate 
                                   WHERE Name = 'Template Cancelamento da Oportunidade' LIMIT 1];
    
    for (Opportunity opp : opportunitiesToNotify) {
        String subject = 'Notificação de Cancelamento da Oportunidade: ' + opp.Name;
        
      
        String htmlBody = emailTemplate.HtmlValue;
        if (htmlBody != null) {
            htmlBody = htmlBody.replace('{{{Opportunity.Name}}}', opp.Name != null ? opp.Name : 'N/A');
            htmlBody = htmlBody.replace('{{{Product2.Name}}}', opp.Unidade__r != null ? opp.Unidade__r.Name : 'N/A');
            htmlBody = htmlBody.replace('{{{Opportunity.MotivoCancelamento__c}}}', opp.MotivoCancelamento__c != null ? opp.MotivoCancelamento__c : 'N/A');
            htmlBody = htmlBody.replace('{{{Opportunity.Observacao__c}}}', opp.Observacao__c != null ? opp.Observacao__c : 'N/A');
        }
        
       
        String chatterMessage = 'Oportunidade Cancelada\n\n' +
                                'Oportunidade: ' + opp.Name + '\n' +
                                'Produto: ' + (opp.Unidade__r != null ? opp.Unidade__r.Name : 'N/A') + '\n' +
                                'Motivo do Cancelamento: ' + (opp.MotivoCancelamento__c != null ? opp.MotivoCancelamento__c : 'N/A') + '\n' +
                                'Observação: ' + (opp.Observacao__c != null ? opp.Observacao__c : 'N/A') + '\n\n' +
                                'Infelizmente, a oportunidade foi cancelada devido ao motivo acima.\n\n' +
                                'Atenciosamente,\nEquipe de Vendas';
        
        FeedItem opportunityChatter = new FeedItem();
        opportunityChatter.ParentId = opp.Id; 
        opportunityChatter.Body = chatterMessage;
        chatterFeedItems.add(opportunityChatter);
        
     
        if (opp.Contato__r != null && opp.Contato__r.OwnerId != null) {
            User contactOwner = [SELECT Id, Name, Email, Reportase__c 
                                 FROM User 
                                 WHERE Id = :opp.Contato__r.OwnerId LIMIT 1];
            if (contactOwner != null) {
             
                if (contactOwner.Email != null) {
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    email.setToAddresses(new String[] {contactOwner.Email});
                    email.setSubject(subject);
                    email.setHtmlBody(htmlBody);
                    emailsToSend.add(email);
                }

    
              
                notifyReportees(contactOwner, opp, subject, htmlBody, chatterFeedItems, emailsToSend);
            }
        }
    }
    
  
    if (!emailsToSend.isEmpty()) {
        try {
            Messaging.sendEmail(emailsToSend);
        } catch (Exception e) {
            System.debug('Erro ao enviar e-mails: ' + e.getMessage());
        }
    }
    
    
    if (!chatterFeedItems.isEmpty()) {
        try {
            insert chatterFeedItems;
        } catch (Exception e) {
            System.debug('Erro ao inserir mensagens no Chatter: ' + e.getMessage());
        }
    }
}



/**
* Este método notifica as hierarquias de usuários relacionadas (como "reportase") em relação ao cancelamento da oportunidade.
* É chamado recursivamente para notificar usuários hierárquicos.
*/
private static void notifyReportees(User currentUser, Opportunity opp, String subject, String htmlBody, 
                                    List<FeedItem> chatterFeedItems, List<Messaging.SingleEmailMessage> emailsToSend) {
  
    if (currentUser.Reportase__c != null) {
        User reportee = [SELECT Id, Name, Email, Reportase__c 
                         FROM User 
                         WHERE Id = :currentUser.Reportase__c LIMIT 1];
        if (reportee != null) {
        
            if (reportee.Email != null) {
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new String[] {reportee.Email});
                email.setSubject(subject);
                email.setHtmlBody(htmlBody);
                emailsToSend.add(email);
            }

    
          
            notifyReportees(reportee, opp, subject, htmlBody, chatterFeedItems, emailsToSend);
        }
    }
}






    /**
 * Este método prepara e envia notificações de cancelamento de oportunidade.
 * As notificações incluem e-mails e mensagens no Chatter para os responsáveis e hierarquias relacionadas
 * gando a oportunidade é movida para ganho de acordo com a parametrização.
 */

public static void handleOpportunityUpdate(List<Opportunity> updatedOpportunities) {
    List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
    Set<Id> oppIds = new Set<Id>();

    Date today = System.today();

    for (Opportunity opp : updatedOpportunities) {
        
        if (opp.StageName == 'Conferência') {
            if (opp.Data_Assinatura_Contrato__c != null && opp.Dias_Apos_Assinatura__c != null) {
                Date assinaturaData = opp.Data_Assinatura_Contrato__c;
                Integer diasAposAssinatura = Integer.valueOf(opp.Dias_Apos_Assinatura__c);  
                Date dataLimite = assinaturaData.addDays(diasAposAssinatura);

               
                if (dataLimite <= today) {
                    Opportunity oppToUpdate = new Opportunity(Id = opp.Id, StageName = 'Ganho');
                    opportunitiesToUpdate.add(oppToUpdate);
                    oppIds.add(opp.Id);
                }
            }
        }
    }

    
    if (!opportunitiesToUpdate.isEmpty()) {
      
        List<Opportunity> oppsWithDetails = [
            SELECT Id, Name, MotivoCancelamento__c, Unidade__c, Unidade__r.Name,
                Contato__r.Name, Contato__r.Email, Contato__r.OwnerId,
                Contato__r.UsuarioCorretor__r.Name, Contato__r.UsuarioCorretor__r.Email, Observacao__c
            FROM Opportunity
            WHERE Id IN :oppIds
        ];

        
        Map<Id, Opportunity> oppDetailsMap = new Map<Id, Opportunity>(oppsWithDetails);

      
        for (Opportunity opp : opportunitiesToUpdate) {
            if (oppDetailsMap.containsKey(opp.Id)) {
                Opportunity detailedOpp = oppDetailsMap.get(opp.Id);
                opp.Name = detailedOpp.Name;  
                opp.Unidade__c = detailedOpp.Unidade__c;
                opp.Unidade__r = detailedOpp.Unidade__r;
                opp.Contato__r = detailedOpp.Contato__r;
                opp.Observacao__c = detailedOpp.Observacao__c;
                
            }
        }

     
        try {
            update opportunitiesToUpdate;
            System.debug('Oportunidades movidas para "Ganho".');
            sendVictoryNotification(opportunitiesToUpdate);
        } catch (Exception e) {
            System.debug('Erro ao atualizar oportunidades: ' + e.getMessage());
        }
    }
}




/**
* Este método prepara e envia notificações do vencimento da oportunidade.
* As notificações incluem e-mails e mensagens no Chatter para os responsáveis e hierarquias relacionadas.
*/
public static void sendVictoryNotification(List<Opportunity> opportunitiesToUpdate) {
    List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();
    List<FeedItem> chatterFeedItems = new List<FeedItem>();

    EmailTemplate emailTemplate = [SELECT Id, Name, HtmlValue 
                                   FROM EmailTemplate 
                                   WHERE Name = 'Template Vitoria da Oportunidade' LIMIT 1];

    for (Opportunity opp : opportunitiesToUpdate) {
        String subject = 'Notificação de Vitória da Oportunidade: ' + opp.Name;

        String htmlBody = emailTemplate.HtmlValue;
        if (htmlBody != null) {
            htmlBody = htmlBody.replace('{{{Opportunity.Name}}}', opp.Name != null ? opp.Name : 'N/A');
            htmlBody = htmlBody.replace('{{{Product2.Name}}}', opp.Unidade__r != null ? opp.Unidade__r.Name : 'N/A');
            htmlBody = htmlBody.replace('{{{Opportunity.Observacao__c}}}', opp.Observacao__c != null ? opp.Observacao__c : 'N/A');
        }

        String chatterMessage = 'Notificação de Vitória da Oportunidade:Parábens! A oportunidade foi ganha.\n\n' +
                                'Oportunidade: ' + opp.Name + '\n' +
                                'Produto: ' + (opp.Unidade__r != null ? opp.Unidade__r.Name : 'N/A') + '\n' +
                                'Observação: ' + (opp.Observacao__c != null ? opp.Observacao__c : 'N/A') + '\n\n' +
                                'Parabéns, a oportunidade foi vencida com sucesso.\n\n' +
                                'Atenciosamente,\nEquipe de Vendas';

        FeedItem opportunityChatter = new FeedItem();
        opportunityChatter.ParentId = opp.Id; 
        opportunityChatter.Body = chatterMessage;
        chatterFeedItems.add(opportunityChatter);

        
        if (opp.Contato__r != null && opp.Contato__r.OwnerId != null) {
            User contactOwner = [SELECT Id, Name, Email, Reportase__c 
                                 FROM User 
                                 WHERE Id = :opp.Contato__r.OwnerId LIMIT 1];
            if (contactOwner != null) {
                if (contactOwner.Email != null) {
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    email.setToAddresses(new String[] {contactOwner.Email});
                    email.setSubject(subject);
                    email.setHtmlBody(htmlBody);
                    emailsToSend.add(email);
                }
              
                notifyReporteesRecursively(contactOwner, opp, subject, htmlBody, chatterFeedItems, emailsToSend);
            }
        }
    }

    
    if (!emailsToSend.isEmpty()) {
        try {
            Messaging.sendEmail(emailsToSend);
        } catch (Exception e) {
            System.debug('Erro ao enviar e-mails: ' + e.getMessage());
        }
    }

    
    if (!chatterFeedItems.isEmpty()) {
        try {
            insert chatterFeedItems;
        } catch (Exception e) {
            System.debug('Erro ao inserir mensagens no Chatter: ' + e.getMessage());
        }
    }
}







/**
* Este método notifica as hierarquias de usuários relacionadas (como "reportase") em relação a conferencia da oportunidade.
* É chamado recursivamente para notificar usuários hierárquicos quando a oportunidade é ganha.
*/
private static void notifyReporteesRecursively(User currentUser, Opportunity opp, String subject, String htmlBody, 
                                               List<FeedItem> chatterFeedItems, List<Messaging.SingleEmailMessage> emailsToSend) {
    if (currentUser.Reportase__c != null) {
        User reportee = [SELECT Id, Name, Email, Reportase__c 
                         FROM User 
                         WHERE Id = :currentUser.Reportase__c LIMIT 1];
        if (reportee != null) {
            if (reportee.Email != null) {
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new String[] {reportee.Email});
                email.setSubject(subject);
                email.setHtmlBody(htmlBody);
                emailsToSend.add(email);
            }

            
            notifyReporteesRecursively(reportee, opp, subject, htmlBody, chatterFeedItems, emailsToSend);
        }
    } 
  }
}