force-app/main/default/objects/Checklist_de_Documentos__c/Checklist_de_Documentos__c.object-meta.xml
<CustomObject>
    <label>Checklist de Documentos</label>
    <nameField>
        <label>Nome de Checklist de Documentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Documenta_o__c.field-meta.xml
<CustomField>
    <fullName>Documenta_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentação</label>
    <referenceTo>Documentacao__c</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <description>Documentação de contato</description>
    <label>Documentação</label>
    <nameField>
        <label>Nome de Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Documentacao__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Documentações</relationshipLabel>
    <relationshipName>Documentacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Entregue__c.field-meta.xml
<CustomField>
    <fullName>Entregue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entregue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Validado__c.field-meta.xml
<CustomField>
    <fullName>Validado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Descreve se o documento foi ou está validado ou não.</description>
    <label>Validado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__mdt/Documento__mdt.object-meta.xml
<CustomObject>
    <label>Documento (Configuracao)</label>
    <pluralLabel>Documentacao</pluralLabel>
</CustomObject>

force-app/main/default/objects/Documento__mdt/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatorio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor (Contato)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Id</field>
            <operation>equals</operation>
            <value>012bL0000003bkfQAA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo De Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negócio existente</fullName>
                <default>true</default>
                <label>Negócio existente</label>
            </value>
            <value>
                <fullName>Negócio novo</fullName>
            </value>
            <value>
                <fullName>Financiamento Bancário</fullName>
                <isActive>false</isActive>
                <label>Financiamento Bancário</label>
            </value>
            <value>
                <fullName>Financiamento Direto</fullName>
                <isActive>false</isActive>
                <label>Financiamento Direto</label>
            </value>
            <value>
                <fullName>Venda a Vista</fullName>
                <isActive>false</isActive>
                <label>Venda a Vista</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentacaoDATest.cls
@IsTest
public with sharing class DocumentacaoDATest {
    
    @TestSetup
    static void setup() {
        Documentacao__c doc1 = new Documentacao__c();
        doc1.Name = 'Documento test';
        doc1.Obrigatorio__c = true;
        doc1.Entregue__c = false;
        doc1.Validado__c = false;

        Documentacao__c doc2 = new Documentacao__c();
        doc2.Name = 'Documento test 2';
        doc2.Obrigatorio__c = true;
        doc2.Entregue__c = false;
        doc2.Validado__c = false;
        

        List<Opportunity> testOpps = new List<Opportunity>();

        for (Integer i = 0; i < 2; i++) {
            testOpps.add(new Opportunity(
                Name = 'Opp'+i,
                StageName = 'Negociação',
                Amount = 1000 + i,
                CanalAtendimento__c = 'WhatsApp',
                Probability = 20,
                TipoVenda__c = 'Negócio novo',
                CloseDate = System.today().addDays(15)
            ));
        }

        Contact ctt = new Contact();
        ctt.FirstName = 'Elera';
        ctt.LastName = 'Teste';
        ctt.Email = 'teste.dev@elera.io';

        doc1.Contato__c = ctt.Id;
        doc2.Contato__c = ctt.Id;

        insert ctt;

        insert testOpps;

        insert new List<Documentacao__c> { doc1, doc2 };     
    }


    @IsTest
    static void testGetAllById() {
        Documentacao__c doc = [
            SELECT Id
            FROM Documentacao__c
            LIMIT 1
        ];

        Test.startTest();
        List<Documentacao__c> results = DocumentacaoDA.getAllById(new Set<Id> { doc.Id });
        Test.stopTest();

        System.assert(!results.isEmpty(), 'Deveria ao menos retornar um registro de documentação.');
    }

    @IsTest
    static void testGetById() {
        Documentacao__c doc = [
            SELECT Id
            FROM Documentacao__c
            LIMIT 1
        ];

        Test.startTest();
            Documentacao__c docMethod = DocumentacaoDA.getById(doc.Id);
        Test.stopTest();

        System.assert(docMethod != null, 'Retornar registro');
    }

    @IsTest 
    static void testGetMetadasByName() {
        Set<String> names = new Set<String>{'RG'};

        Test.startTest();
            List<Documento__mdt> docsMdt = DocumentacaoDA.getMetadasByName(names);
        Test.stopTest();

        System.assert(docsMdt.size() > 0, 'Contem metadados de documentação');
    }


    @IsTest 
    static void testGetMetadasByPapers() {
        Set<String> papers = new Set<String>{'Comprador', 'Sócio'};

        Test.startTest();
            List<Documento__mdt> docsMdt = DocumentacaoDA.getMetadasByPapers(papers);
        Test.stopTest();

        System.assert(docsMdt.size() > 0, 'Contem metadados de documentação');
    }

    @IsTest 
    static void testGetAllDocumentsFromChecklist() {
        List<Opportunity> listOpps = [SELECT Id FROM Opportunity LIMIT 2];
        Contact ctt = [SELECT Id FROM Contact LIMIT 1];

        System.debug(ctt);
        
        Set<Id> idsOpps = new Set<Id>();

        for (Opportunity opp : listOpps) {
            idsOpps.add(opp.Id);
        }

        List<Checklist_de_Documentos__c> checklistDocs = new List<Checklist_de_Documentos__c>();
        for (Opportunity opp : listOpps) {
            checklistDocs.add(new Checklist_de_Documentos__c(
                Oportunidade__c = opp.Id,
                Contato__c = ctt.Id,
                Documenta_o__c = [SELECT Id FROM Documentacao__c LIMIT 1].Id
            ));
        }
        insert checklistDocs;
        
        Test.startTest();
            List<Documentacao__c> documents = DocumentacaoDA.getAllDocumentsFromChecklist(idsOpps);
        Test.stopTest();

        System.assert(!documents.isEmpty(), 'Retornar lista de documentos');
    }

    @IsTest 
    static void testGetAllDocumentsFromChecklistBlank() {
        Set<Id> idsOpps = new Set<Id>();
        Test.startTest();
            List<Documentacao__c> documents = DocumentacaoDA.getAllDocumentsFromChecklist(idsOpps);
        Test.stopTest();

        System.assert(documents.isEmpty(), 'Retornar lista vazia');
    }
}