you/force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecionar se for corretor.</description>
    <label>Corretor</label>
    <type>Checkbox</type>
</CustomField>

you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

you/force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

you/force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Lead/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica o corretor responsável pelo lead.</description>
    <inlineHelpText>Indique o corretor responsável pelo lead.</inlineHelpText>
    <label>Corretor (Roleta)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O corretor deve pertencer à roleta do lead.</errorMessage>
        <filterItems>
            <field>ParticipanteRoleta__c.RoletaLeads__c</field>
            <operation>equals</operation>
            <valueField>$Source.RoletaLeads__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ParticipanteRoleta__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Opportunity/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <infoMessage>Corretor: Tipo de registro do contato igual a Corretor</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>OportunidadesCorretor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Conta pessoal</label>
</RecordType>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <formula>ValorBase__c * Coeficiente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

you/force-app/main/default/objects/Quote/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Cotações</relationshipLabel>
    <relationshipName>Cota_es</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/SeriePagamentos__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>SeriesPagamentos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/SeriePagamentos__c/fields/TipoCondicao__c.field-meta.xml
<CustomField>
    <fullName>TipoCondicao__c</fullName>
    <label>Tipo de Condição</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TiposCondicoes</valueSetName>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor total (%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Cotacao__c.field-meta.xml
<CustomField>
    <fullName>Cotacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotação</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcela__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcela__c</fullName>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

you/force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcelaPos__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcelaPos__c</fullName>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

you/force-app/main/default/objects/UnidadeTabelaVendas__c/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Unidades da Tabela de Vendas</relationshipLabel>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {

    //Registros objetos padrão
    public static Account gerarConta(){
        Account conta = new Account();
        conta.Name = 'Conta de Teste';
        return conta;
    }

    // Instância conta com um tipo específico
    public static Account gerarConta(String tipo){
        Account conta = new Account();
        conta.Name = 'Conta de Teste';
        conta.Type = tipo;
        return conta;
    }

    public static Account gerarContaPessoal() {
        Account contaPessoal = new Account();
        contaPessoal.FirstName = 'John';
        contaPessoal.LastName = 'Doe';
        contaPessoal.PersonEmail = 'johndoe@example.com';
        contaPessoal.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        return contaPessoal;
    }

    public static Contact gerarContato(Account conta) {
        Contact contato = new Contact();
        contato.AccountId = conta.Id;
        contato.LastName = 'Teste';
        contato.CPF__c  = '67481558000';
        return contato;
    }

    public static Contact gerarContato(Account conta, Id recordTypeId) {
        Contact contato = new Contact();
        contato.AccountId = conta.Id;
        contato.LastName = 'Teste';
        contato.RecordTypeId = recordTypeId;
        return contato;
    }

    public static Quote gerarCotacao(Opportunity oportunidade) {
        Quote cotacao = new Quote();
        cotacao.Name = 'Teste';
        cotacao.OpportunityId = oportunidade.Id; 
        return cotacao;
    }

    public static Lead gerarLead() {
        Lead lead = new Lead();
        lead.FirstName = 'Test';
        lead.LastName = 'Lead';
        lead.Company = 'Elera';
        lead.Email = 'test.lead@elera.io';
        lead.LeadSource = 'Telefone';
        lead.CanalAtendimento__c = 'Chat';
        lead.MobilePhone = '11960387699';
        lead.Status = 'Novo';
        lead.CPF__c = '25702438094';
        
        return lead;
    }

    public static Lead gerarLead(Empreendimento__c empreendimento) {
        Lead lead = gerarLead();
        lead.EmpreendimentoInteresse__c = empreendimento.Id;
        
        return lead;
    }

    public static Product2 gerarProduto(){
        Product2 produto = new Product2();
        produto.Name = 'Produto de Teste';
        produto.ProductCode = 'Teste-1';
        produto.isActive = true;
        // produto.NumeroDaUnidade__c = 777;
        return produto;
    }

    public static Task gerarTask(Lead lead) {
        Task task = new Task();
        task.Subject = 'Chamada';
        task.Status = 'Completed';
        task.WhoId = lead.Id;
        return task;
    }

    public static PricebookEntry  gerarPricebookEntry(Id idProduto){
        PricebookEntry pricebookEntry = new PricebookEntry();
        pricebookEntry.Pricebook2Id = Test.getStandardPricebookId();
        pricebookEntry.Product2Id = idProduto;
        pricebookEntry.UseStandardPrice = false;
        pricebookEntry.UnitPrice = 100;
        pricebookEntry.IsActive = true;
        return pricebookEntry;
    }

    //Registros simulador de vendas
    public static Empreendimento__c gerarEmpreendimento(){
        Empreendimento__c empreendimento = new Empreendimento__c();
        empreendimento.Name = 'Empreendimento de Teste';
        empreendimento.CNPJEmpreendimento__c = '22151181000190';
        return empreendimento;
    }

    // public static TabelaVendas__c gerarTabelaVendas(){
    //     TabelaVendas__c tabelaVendas = new TabelaVendas__c();
    //     tabelaVendas.Name = 'Teste'; 
    //     tabelaVendas.PeriodicidadeParcelaPos__c = 1;
    //     tabelaVendas.PeriodicidadeParcela__c = 1;
    //     return tabelaVendas;
    // }

    // public static TabelaVendas__c gerarTabelaVendas(Quote cotacao){
    //     TabelaVendas__c tabelaVendas = new TabelaVendas__c();
    //     tabelaVendas.Name = 'Teste'; 
    //     tabelaVendas.PeriodicidadeParcelaPos__c = 1;
    //     tabelaVendas.PeriodicidadeParcela__c = 1;
    //     tabelaVendas.Cotacao__c = cotacao.Id;
    //     return tabelaVendas;
    // }


    public static Opportunity gerarOportunidade(Account conta, Contact corretor) {
        Opportunity oportunidade = new Opportunity();
        oportunidade.Name = 'Teste';
        oportunidade.AccountId = conta.Id;
        oportunidade.Corretor__c = corretor.Id;
        oportunidade.StageName = 'Negociação';
        return oportunidade;
    }

    // public static SeriePagamentos__c gerarSeriePagamento(Id idTabela){
    //     SeriePagamentos__c serie = new SeriePagamentos__c();
    //     serie.Name = 'Teste';
    //     serie.InicioPagamento__c = 1;
    //     serie.QuantidadeParcelas__c = 1;
    //     serie.ValorTotal__c= 1;
    //     serie.TabelaVenda__c = idTabela;
    //     serie.TipoCondicao__c = 'Ato';
    //     return serie;
    // }

    // public static SeriePagamentosService.ObjetoSerie gerarObjetoSerie(String nomeSerie, Id idTabelaVenda){
    //     SeriePagamentosService.ObjetoSerie serie = new SeriePagamentosService.ObjetoSerie();
    //     serie.nome = nomeSerie;
    //     serie.valorTotal = 4; 
    //     serie.quantidadeParcelas = 1;
    //     serie.periodicidade = 1;
    //     serie.inicioPagamento = 0;
    //     serie.aposHabiteSe = false;
    //     return serie;
    // }

    // public static UnidadeTabelaVendas__c gerarUnidadeTabelaVendas(Id idTabela){
    //     UnidadeTabelaVendas__c unidadeVenda = new UnidadeTabelaVendas__c();
    //     unidadeVenda.Name = 'UnidadeVendaTeste';
    //     unidadeVenda.TabelaVenda__c = idTabela;
    //     unidadeVenda.PrecoLista__c = 300000;
    //     return unidadeVenda;
    // } 
}