force-app/main/default/objects/Contract/fields/DataEnvioAssinatura__c.field-meta.xml
<CustomField>
    <fullName>DataEnvioAssinatura__c</fullName>
    <label>Data envio para assinatura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/PrazoAssinatura__c.field-meta.xml
<CustomField>
    <fullName>PrazoAssinatura__c</fullName>
    <label>Prazo para Assinatura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/VerificaPrazoAssinaturaBatch.cls
global class VerificaPrazoAssinaturaBatch implements Database.Batchable<SObject>, Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Status, StartDate, Account.Name, CustomerSignedDate, DataEnvioAssinatura__c, PrazoAssinatura__c FROM Contract WHERE PrazoAssinatura__c < :Date.today() AND Status = \'Em Assinatura\'';

        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        ContratoService.verificaPrazoAssinatura((List<Contract>) scope);
    }
    
    public void finish(Database.BatchableContext bc) {
        System.debug('VerificaPrazoAssinaturaBatch implementada!');
    }
}