force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <label>Bloco</label>
    <nameField>
        <label>Nome do Bloco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Deve ser preenchido com o empreeendimento corespondente.</description>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Blocos</relationshipLabel>
    <relationshipName>Blocos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/PrazoAssinatura__c.field-meta.xml
<CustomField>
    <fullName>PrazoAssinatura__c</fullName>
    <label>Prazo para Assinatura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Contrato.recordType-meta.xml
<RecordType>
    <fullName>Contrato</fullName>
    <active>true</active>
    <label>Contrato</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/ConteudoTemplate__c.field-meta.xml
<CustomField>
    <fullName>ConteudoTemplate__c</fullName>
    <label>Conteúdo do Template</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Templates_de_Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContratoService.cls
public class ContratoService {
    public static String contratoText(Opportunity opp, TemplateDocumento__c template) {
        String text = template.ConteudoTemplate__c;

        Empreendimento__c emp = (Empreendimento__c) QueryHelper.selectAllFields('Empreendimento__c', opp.Empreendimento__c);
        Account conta = (Account) QueryHelper.selectAllFields('Account', opp.AccountId);
        Product2 prd = (Product2) QueryHelper.selectAllFields('Product2', opp.Unidade__c);
        Bloco__c bloco = (Bloco__c) QueryHelper.selectAllFields('Bloco__c', prd.Bloco__c);
        List<OpportunityContactRole> roles = [SELECT Id, ContactId, Role, Contact.Name FROM OpportunityContactRole WHERE OpportunityId = :opp.Id];

        Map<String, SObject> sObjectsMap = new Map<String, SObject>{
            'Opportunity.' => opp,
            'Empreendimento__r.' => emp,
            'Account.' => conta,
            'Bloco__r.' => bloco,
            'Product2.' => prd
        };

        Map<String, Map<String, Schema.SObjectField>> tagFields = new Map<String, Map<String, Schema.SObjectField>>{
            'Opportunity.' => Schema.SObjectType.Opportunity.fields.getMap(),
            'Empreendimento__r.' => Schema.SObjectType.Empreendimento__c.fields.getMap(),
            'Account.' => Schema.SObjectType.Account.fields.getMap(),
            'Bloco__r.' => Schema.SObjectType.Bloco__c.fields.getMap(),
            'Product2.' => Schema.SObjectType.Product2.fields.getMap()
        };

        for (String tagPrefix : tagFields.keySet()) {
            Map<String, Schema.SObjectField> fieldsMap = tagFields.get(tagPrefix);
            SObject relatedSObject = sObjectsMap.get(tagPrefix); 

            if (relatedSObject != null) {
                for (String fieldName : fieldsMap.keySet()) {
                    String apiName = fieldsMap.get(fieldName).getDescribe().getName();
                    String fullTag = tagPrefix + apiName;

                    if (text.contains(fullTag)) {
                        String fieldValue = relatedSObject.get(apiName) == null ? 'N/A' : String.valueOf(relatedSObject.get(apiName));
                        text = text.replace(fullTag, fieldValue);
                    }
                }
            }
        }

        Map<String, Schema.SObjectField> opportunityContactRoleFieldsMap = Schema.SObjectType.OpportunityContactRole.fields.getMap();

        if (text.contains('OpportunityContactRole.Role')) {
            List<String> signatariosList = new List<String>();

            for (OpportunityContactRole role : roles) {
                for (String fieldName : opportunityContactRoleFieldsMap.keySet()) {
                    String apiName = opportunityContactRoleFieldsMap.get(fieldName).getDescribe().getName();
                    String fullTag = 'OpportunityContactRole.' + apiName;

                    if (text.contains(fullTag)) {
                        if (apiName == 'Role' || apiName == 'Contact.Name') {
                            String fieldValue = role.get(apiName) == null ? 'N/A' : String.valueOf(role.get(apiName));
                            signatariosList.add(role.Contact.Name + ' - ' + role.Role);
                        }
                    }
                }
            }

            String signatariosText = String.join(signatariosList, ', ');

            text = text.replace('OpportunityContactRole.Role', signatariosText);
        }

        return text;
    }

    public static void atualizarPrazoAssinatura(List<Contract> contratos) {
        List<Contract> contratosToUpdate = new List<Contract>();
        Date diaAtual = Date.today();

        for (Contract contrato : contratos) {
            if (contrato.Status == 'Em Assinatura') {
                diaAtual = diaAtual.addDays(5);
                contrato.PrazoAssinatura__c = diaAtual;
                contratosToUpdate.add(contrato);
            }
        }

        if (!contratosToUpdate.isEmpty()) {
            update contratosToUpdate;
        }
    }

    public static void evitarGeracaoMultipla(List<Contract> contracts){
        Set<Id> oppIds = new Set<Id>();

        for(Contract ctt : contracts){
            oppIds.add(ctt.Oportunidade__c);
        }

        List<Contract> contratos = ContractSelector.getContractsByOpp(oppIds);

        if(!contratos.isEmpty()){
            for(Contract ctt : contracts){
                if(ctt.Status == 'Contrato Gerado'){
                    ctt.addError('Já existe um contrato gerado para esta oportunidade.');
                }
            }
        }
    }
}