force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecionar se for corretor.</description>
    <label>Corretor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Cliente.recordType-meta.xml
<RecordType>
    <fullName>Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica o corretor responsável pelo lead.</description>
    <inlineHelpText>Indique o corretor responsável pelo lead.</inlineHelpText>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O corretor deve pertencer à roleta do lead.</errorMessage>
        <filterItems>
            <field>ParticipanteRoleta__c.RoletaLeads__c</field>
            <operation>equals</operation>
            <valueField>$Source.RoletaLeads__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ParticipanteRoleta__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <infoMessage>Corretor: Tipo de registro do contatoigual aCorretor</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactoryTest.cls
@IsTest
private class TestDataFactoryTest {

    // Teste para gerarConta sem tipo
    @IsTest
    static void testGerarConta() {
        Account conta = TestDataFactory.gerarConta();
        System.assertEquals('Conta de Teste', conta.Name, 'A conta deve ter o nome correto');
    }

    // Teste para gerarConta com tipo
    @IsTest
    static void testGerarContaComTipo() {
        Account conta = TestDataFactory.gerarConta('Cliente');
        System.assertEquals('Conta de Teste', conta.Name, 'A conta deve ter o nome correto');
        System.assertEquals('Cliente', conta.Type, 'A conta deve ter o tipo correto');
    }

    // Teste para gerarContaPessoal
    @IsTest
    static void testGerarContaPessoal() {
        Account contaPessoal = TestDataFactory.gerarContaPessoal();
        System.assertEquals('John', contaPessoal.FirstName, 'O primeiro nome da conta pessoal deve ser John');
        System.assertEquals('Doe', contaPessoal.LastName, 'O sobrenome da conta pessoal deve ser Doe');
        System.assertEquals('johndoe@example.com', contaPessoal.PersonEmail, 'O email da conta pessoal deve ser johndoe@example.com');
        System.assertNotEquals(null, contaPessoal.RecordTypeId, 'O RecordTypeId da conta pessoal deve ser preenchido');
    }

    // Teste para gerarContato
    @IsTest
    static void testGerarContato() {
        Account conta = TestDataFactory.gerarConta();
        insert conta;
        Contact contato = TestDataFactory.gerarContato(conta);
        System.assertEquals(conta.Id, contato.AccountId, 'O contato deve estar associado à conta correta');
        System.assertEquals('Teste', contato.LastName, 'O sobrenome do contato deve ser Teste');
    }

 


    // Teste para gerarLead
    @IsTest
    static void testGerarLead() {
        Lead lead = TestDataFactory.gerarLead();
        System.assertEquals('Elera', lead.Company, 'A empresa do lead deve ser Elera');
        System.assertEquals('11960387699', lead.MobilePhone, 'O telefone do lead deve estar correto');
    }

    // Teste para gerarLead com Empreendimento
    @IsTest
    static void testGerarLeadComEmpreendimento() {
        Empreendimento__c empreendimento = TestDataFactory.gerarEmpreendimento();
        insert empreendimento;
        Lead lead = TestDataFactory.gerarLead(empreendimento);
        System.assertEquals(empreendimento.Id, lead.EmpreendimentoInteresse__c, 'O empreendimento de interesse do lead deve ser correto');
    }

    // Teste para gerarProduto
    @IsTest
    static void testGerarProduto() {
        Product2 produto = TestDataFactory.gerarProduto();
      //  System.assertEquals('Produto de Teste', produto.Name, 'O nome do produto deve ser Produto de Teste');
      //  System.assertTrue(produto.isActive, 'O produto deve estar ativo');
    }

    // Teste para gerarTask
    @IsTest
    static void testGerarTask() {
        Lead lead = TestDataFactory.gerarLead();
        insert lead;
        Task task = TestDataFactory.gerarTask(lead);
       // System.assertEquals(lead.Id, task.WhoId, 'A task deve estar associada ao lead correto');
       // System.assertEquals('Chamada', task.Subject, 'O assunto da task deve ser Chamada');
    }

  

    // Teste para gerarEmpreendimento
    @IsTest
    static void testGerarEmpreendimento() {
        Empreendimento__c empreendimento = TestDataFactory.gerarEmpreendimento();
     //   System.assertEquals('Empreendimento de Teste', empreendimento.Name, 'O nome do empreendimento deve ser Empreendimento de Teste');
    }

    // Teste para gerarOportunidade
    @IsTest
    static void testGerarOportunidade() {
        Account conta = TestDataFactory.gerarConta();
        insert conta;
        Contact corretor = TestDataFactory.gerarContato(conta);
        insert corretor;
        Opportunity oportunidade = TestDataFactory.gerarOportunidade(conta, corretor);
        //System.assertEquals(conta.Id, oportunidade.AccountId, 'A oportunidade deve estar associada à conta correta');
      //  System.assertEquals(corretor.Id, oportunidade.Corretor__c, 'A oportunidade deve estar associada ao corretor correto');
    }
}