force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <label>Bloco</label>
    <nameField>
        <label>Nome do Bloco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Bloco__c/fields/DataEntrega__c.field-meta.xml
<CustomField>
    <fullName>DataEntrega__c</fullName>
    <label>Data de Entrega</label>
    <type>Date</type>
</CustomField>

you/force-app/main/default/objects/Bloco__c/fields/DataLancamento__c.field-meta.xml
<CustomField>
    <fullName>DataLancamento__c</fullName>
    <label>Data de Lançamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Deve ser preenchido com o empreeendimento corespondente.</description>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Blocos</relationshipLabel>
    <relationshipName>Blocos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/QuantidadeAndares__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAndares__c</fullName>
    <description>Deve ser preenchido 
 com a quantidade
  de andares da Torre.</description>
    <label>Quantidade de Andares</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/TipoBloco__c.field-meta.xml
<CustomField>
    <fullName>TipoBloco__c</fullName>
    <label>Tipo de Bloco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ala</fullName>
            </value>
            <value>
                <fullName>Quadra</fullName>
            </value>
            <value>
                <fullName>Torre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/TotalUnidades__c.field-meta.xml
<CustomField>
    <fullName>TotalUnidades__c</fullName>
    <description>Deve ser preenchido com a quantidade de andares por Torre.</description>
    <label>Total de Unidades</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Empreendimento__c/fields/SPE__c.field-meta.xml
<CustomField>
    <fullName>SPE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SPE (Sociedade de Propósito Específico)</description>
    <label>SPE</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPE</relationshipLabel>
    <relationshipName>Empreendimentos</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/StatusObra__c.field-meta.xml
<CustomField>
    <fullName>StatusObra__c</fullName>
    <description>Status da obra do empreendimento</description>
    <label>Status da Obra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em construção</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Lançamento</fullName>
            </value>
            <value>
                <fullName>Pré-Lançamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/TipoEmpreendimento__c.field-meta.xml
<CustomField>
    <fullName>TipoEmpreendimento__c</fullName>
    <label>Tipo de Empreendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Lote</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/AgenteFinanceiro__c.field-meta.xml
<CustomField>
    <fullName>AgenteFinanceiro__c</fullName>
    <description>Indica o tipo de agente financeiro responsável pela unidade.</description>
    <inlineHelpText>Indica o tipo de agente financeiro responsável pela unidade.</inlineHelpText>
    <label>Agente financeiro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AgenteFinanceiro</valueSetName>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Coeficiente__c.field-meta.xml
<CustomField>
    <fullName>Coeficiente__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Coeficiente a ser aplicado nesta unidade para geração do valor comercial.</description>
    <inlineHelpText>Coeficiente a ser aplicado nesta unidade para geração do valor comercial.</inlineHelpText>
    <label>Coeficiente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Enquadramento__c.field-meta.xml
<CustomField>
    <fullName>Enquadramento__c</fullName>
    <label>Enquadramento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HIS</fullName>
            </value>
            <value>
                <fullName>HMP</fullName>
            </value>
            <value>
                <fullName>R2V</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
                <isActive>false</isActive>
                <label>Comercial</label>
            </value>
            <value>
                <fullName>Hotel</fullName>
                <isActive>false</isActive>
                <label>Hotel</label>
            </value>
            <value>
                <fullName>LJ</fullName>
                <isActive>false</isActive>
                <label>LJ</label>
            </value>
            <value>
                <fullName>NR</fullName>
                <isActive>false</isActive>
                <label>NR</label>
            </value>
            <value>
                <fullName>UH</fullName>
                <isActive>false</isActive>
                <label>UH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da unidade</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Disponivel</fullName>
            </value>
            <value>
                <fullName>&lt;&lt;LISTAR STATUS&gt;&gt;</fullName>
                <isActive>false</isActive>
                <label>&lt;&lt;LISTAR STATUS&gt;&gt;</label>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
                <isActive>false</isActive>
                <label>Contrato Assinado</label>
            </value>
            <value>
                <fullName>Contrato Emitido</fullName>
                <isActive>false</isActive>
                <label>Contrato Emitido</label>
            </value>
            <value>
                <fullName>Negociação</fullName>
                <isActive>false</isActive>
                <label>Negociação</label>
            </value>
            <value>
                <fullName>Permuta</fullName>
                <isActive>false</isActive>
                <label>Permuta</label>
            </value>
            <value>
                <fullName>Reserva condicional</fullName>
                <isActive>false</isActive>
                <label>Reserva condicional</label>
            </value>
            <value>
                <fullName>SD Fora de Venda</fullName>
                <isActive>false</isActive>
                <label>SD Fora de Venda</label>
            </value>
            <value>
                <fullName>Venda Integrada</fullName>
                <isActive>false</isActive>
                <label>Venda Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Product2/fields/ValorM2__c.field-meta.xml
<CustomField>
    <fullName>ValorM2__c</fullName>
    <label>Valor (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Casa.recordType-meta.xml
<RecordType>
    <fullName>Casa</fullName>
    <active>true</active>
    <label>Casa</label>
</RecordType>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/DescontoNominalMoeda__c.field-meta.xml
<CustomField>
    <fullName>DescontoNominalMoeda__c</fullName>
    <inlineHelpText>Máximo de desconto permitido dentro do Simulador</inlineHelpText>
    <label>Desconto Nominal (Moeda)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcela__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcela__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcelaPos__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcelaPos__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela POS</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Publicada</fullName>
            </value>
            <value>
                <fullName>Desativada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/AgenteFinanceiro.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SPE</fullName>
    </customValue>
    <customValue>
        <fullName>FII</fullName>
    </customValue>
    <customValue>
        <fullName>Recompra</fullName>
    </customValue>
    <masterLabel>Agentes financeiros</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TabelaVendaComparacaoTest.cls
@IsTest
public class TabelaVendaComparacaoTest{
    @IsTest
    static void testCompararTabelaEProposta() {
        // Criar uma conta de teste
        Account acc = new Account(
            Name = 'Conta Teste'
        );
        insert acc;

        // Criar dados de teste para a Oportunidade
        Opportunity opp = new Opportunity(
            Name = 'Test Oportunidade', 
            StageName = 'Negociação', 
            CloseDate = Date.today(),
            AccountId = acc.Id // Associando a oportunidade à conta criada
        );
        insert opp;

        // Criar dados de teste para Empreendimento
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento Teste',
            SPE__c = acc.Id,  
            CNPJEmpreendimento__c = '12345678000195',
            TipoEmpreendimento__c = 'Casa',
            StatusObra__c = 'Em construção', 
            MetragemTerreno__c = 1000,
            MetragemConstruIdaM__c = 1000,
            MetragemPrivativaTotal__c = 1000
        );
        insert empreendimento;

        // Criar um bloco associado ao empreendimento
        Bloco__c bloco = new Bloco__c(
            Name = 'Bloco Teste',
            TipoBloco__c = 'Ala',
            TotalUnidades__c = 535,
            QuantidadeAndares__c = 5,
            DataEntrega__c = Date.Today(),
            DataLancamento__c = Date.Today() + 1,
            Empreendimento__c = empreendimento.Id
        );
        insert bloco;

        // Criar um produto associado ao empreendimento
        Product2 produto = new Product2(
            Name = 'Produto Teste', 
            ValorM2__c = 1000,
            Coeficiente__c = 1.5,
            NumeroDaUnidade__c = 123,
            Andar__c = 12,
            AgenteFinanceiro__c = null,
            Bloco__c = bloco.Id,
            Enquadramento__c = 'HIS',
            Status__c = 'Livre',
            NumeroQuartos__c = 2,
            NumeroDeSuites__c = 1,
            NumeroDeVagasIncorporadas__c = 1,
            Empreendimento__c = empreendimento.Id
        );
        insert produto;

        // Criar uma Tabela de Vendas associada ao empreendimento
        TabelaVendas__c tabela = new TabelaVendas__c(
            Name = 'Tabela de vendas test',
            PeriodicidadeParcela__c = 6,
            PeriodicidadeParcelaPos__c = 12,
            DescontoNominalMoeda__c = 120.00, 
            Empreendimento__c = empreendimento.Id
            
        );
        insert tabela;

        // Atualizar a Oportunidade com o empreendimento relacionado
        opp.Empreendimento__c = empreendimento.Id;
        update opp;

        // Simular os dados fornecidos pelo simulador
        Map<String, Decimal> dadosSimulacao = new Map<String, Decimal>{
            'ValorM2aVista' => 900,
            'ValorM2' => 980,
            'DescontoNominal' => 110000,
            'CaptacaoMetadePrazoObra' => 26.67,
            'CaptacaoAteHabiteSe' => 73.33,
            'CaptacaoAposHabiteSe' => 22.95
        };

        
        Test.startTest();
        
        // Chamar o método a ser testado
        List<Map<String, Object>> comparativo = ComparativoService.compararTabelaEProposta(opp.Id, dadosSimulacao);

        
        Test.stopTest();

        // Validar o resultado
        System.assertEquals(6, comparativo.size(), 'Deve haver 6 itens na tabela comparativa.');

        // Verificar se as diferenças foram calculadas corretamente
        System.assertEquals('R$ 1000.00', comparativo[0].get('Tabela'), 'O valor do m² da tabela deve ser R$ 1000.00.');
        System.assertEquals('R$ 980.00', comparativo[0].get('Proposta'), 'O valor do m² da proposta deve ser R$ 980.00.');
        System.assertEquals('R$ 20.00', comparativo[0].get('Diferenca'), 'A diferença do valor do m² deve ser R$ 20.00.');

        System.assertEquals('R$ 120000.00', comparativo[1].get('Tabela'), 'O desconto nominal da tabela deve ser R$ 120000.00.');
        System.assertEquals('R$ 110000.00', comparativo[1].get('Proposta'), 'O desconto nominal da proposta deve ser R$ 110000.00.');
        System.assertEquals('R$ 10000.00', comparativo[1].get('Diferenca'), 'A diferença do desconto nominal deve ser R$ 10000.00.');
    }
}