force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>CNPJ da empresa</description>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Contract/recordTypes/Contrato.recordType-meta.xml
<RecordType>
    <fullName>Contrato</fullName>
    <active>true</active>
    <label>Contrato</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/ConteudoTemplate__c.field-meta.xml
<CustomField>
    <fullName>ConteudoTemplate__c</fullName>
    <label>Conteúdo do Template</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Templates_de_Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/TipoTemplate__c.field-meta.xml
<CustomField>
    <fullName>TipoTemplate__c</fullName>
    <label>Tipo de Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Outro Documento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractControllerTest.cls
@isTest
public class ContractControllerTest {
    
    @TestSetup
    static void makeData(){
        
        Empreendimento__c emp = new Empreendimento__c();
        emp.Name = 'Empreendimento de Teste';
        emp.CNPJEmpreendimento__c = '11084433000199';
        insert emp;
        
        TemplateDocumento__c template = new TemplateDocumento__c(Name = 'Template Test', Empreendimento__c = emp.Id, TipoTemplate__c = 'Contrato', ConteudoTemplate__c = 'Teste de conteudo', Ativo__c = true);
        insert template;

        Account acc = new Account(Name = 'Conta Teste', CNPJ__c = '11084433000199');
        insert acc;

        Contact cont = new Contact(FirstName = 'Contato', LastName = 'Teste', AccountId = acc.Id, CPF__c = '88637869092');
        insert cont;

        Contract ctt = new Contract(Name = 'Contrato Teste', AccountId = acc.Id, Status = 'Rascunho');
        insert ctt;

        List<Opportunity> oppsTeste = new List<Opportunity>();

        Opportunity opp = new Opportunity(Name = 'Oportunidade de Teste', Empreendimento__c = emp.Id, StageName = 'Negociação', CloseDate = Date.today(), ContractId = ctt.Id);
        oppsTeste.add(opp);

        Opportunity opp2 = new Opportunity(Name = 'Oportunidade de Teste 2', Empreendimento__c = emp.Id, StageName = 'Negociação', CloseDate = Date.today(), ContractId = ctt.Id);
        oppsTeste.add(opp2);
        insert oppsTeste;

        OpportunityContactRole oppRole = new OpportunityContactRole(OpportunityId = opp.Id, Role = 'Comprador', ContactId = cont.Id);
        insert oppRole;
    }

    @isTest
    static void testInfoContrato(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
        Contract ctt = ContractController.infoContrato(opp.Id);
        Test.stopTest();

        System.assertNotEquals(null, ctt);
    }

    @isTest
    static void testRolesContatoOpp(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Oportunidade de Teste' LIMIT 1];
        Opportunity opp2 = [SELECT Id FROM Opportunity WHERE Name = 'Oportunidade de Teste 2' LIMIT 1];

        List<OpportunityContactRole> roles = ContractController.rolesContatoOpp(opp.Id);
        System.Assert.isTrue(!roles.isEmpty());

        List<OpportunityContactRole> roles2 = ContractController.rolesContatoOpp(opp2.Id);
        System.Assert.isTrue(roles2.isEmpty());
    }

    @isTest
    static void testRetornarContratoGerado(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Oportunidade de Teste' LIMIT 1];
        TemplateDocumento__c template = [SELECT Id FROM TemplateDocumento__c LIMIT 1];

        Test.startTest();
        ContentVersion contVersion = ContractController.retornarContratoGerado(opp.Id, template.Id);
        Test.stopTest();

        System.assertNotEquals(null, contVersion);
    }


}