force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>CNPJ da empresa</description>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Contract/fields/DataAssinaturaClienteDocuSign__c.field-meta.xml
<CustomField>
    <fullName>DataAssinaturaClienteDocuSign__c</fullName>
    <label>Data da assinatura do cliente (DocuSign)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/DataEnvioAssinatura__c.field-meta.xml
<CustomField>
    <fullName>DataEnvioAssinatura__c</fullName>
    <label>Data envio para assinatura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/DataInicioContrato__c.field-meta.xml
<CustomField>
    <fullName>DataInicioContrato__c</fullName>
    <label>Data Início do Contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>TemplateDocumento__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Contrato.recordType-meta.xml
<RecordType>
    <fullName>Contrato</fullName>
    <active>true</active>
    <label>Contrato</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Empreendimento__c/fields/StatusObra__c.field-meta.xml
<CustomField>
    <fullName>StatusObra__c</fullName>
    <description>Status da obra do empreendimento</description>
    <label>Status da Obra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em construção</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Lançamento</fullName>
            </value>
            <value>
                <fullName>Pré-Lançamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/TipoEmpreendimento__c.field-meta.xml
<CustomField>
    <fullName>TipoEmpreendimento__c</fullName>
    <label>Tipo de Empreendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Lote</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo De Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negócio existente</fullName>
                <default>true</default>
                <label>Negócio existente</label>
            </value>
            <value>
                <fullName>Negócio novo</fullName>
            </value>
            <value>
                <fullName>Financiamento Bancário</fullName>
                <isActive>false</isActive>
                <label>Financiamento Bancário</label>
            </value>
            <value>
                <fullName>Financiamento Direto</fullName>
                <isActive>false</isActive>
                <label>Financiamento Direto</label>
            </value>
            <value>
                <fullName>Venda a Vista</fullName>
                <isActive>false</isActive>
                <label>Venda a Vista</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Templates_de_Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/TipoTemplate__c.field-meta.xml
<CustomField>
    <fullName>TipoTemplate__c</fullName>
    <label>Tipo de Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Outro Documento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractHelperTest.cls
@isTest
private class ContractHelperTest {

    @testSetup
    static void setup() {
        Account conta = new Account();
        conta.Name = 'Conta de Teste';
        conta.CNPJ__c = '34138415000148';
        conta.Type = 'HouseImobiliaria';
        insert conta;

        Empreendimento__c empreendimento = new Empreendimento__c();
        empreendimento.Name = 'Empreendimento de Teste';
        empreendimento.CNPJEmpreendimento__c = '22151181000190';
        empreendimento.TipoEmpreendimento__c = 'Casa';
        empreendimento.StatusObra__c = 'Entregue';
        empreendimento.MetragemPrivativaTotal__c = 5000;
        empreendimento.MetragemTerreno__c = 10000;
        empreendimento.MetragemConstruIdaM__c = 7000;
        insert empreendimento;

        Opportunity oportunidade = new Opportunity();
        oportunidade.Name = 'Teste';
        oportunidade.Amount = 1000;
        oportunidade.CanalAtendimento__c = 'WhatsApp';
        oportunidade.Probability = 20;
        oportunidade.TipoVenda__c = 'Negócio novo';
        oportunidade.StageName = 'Negociação';
        oportunidade.CloseDate = System.today().addDays(15);
        oportunidade.Empreendimento__c = empreendimento.Id; 
        insert oportunidade;

        TemplateDocumento__c template = new TemplateDocumento__c();
        template.Name = 'Template Test';
        template.TipoTemplate__c = 'Contrato';
        template.Empreendimento__c = oportunidade.Empreendimento__c;
        insert template;

        Contract contract = new Contract(
            AccountId = conta.Id,
            Oportunidade__c = oportunidade.Id,
            DataInicioContrato__c = Date.today(),
            Status = 'Rascunho',
            Name = 'Contrato Test',
            DataEnvioAssinatura__c = Date.today(),
            DataAssinaturaClienteDocuSign__c = Date.today(),
            Template__c = template.Id
        );
        insert contract;

        Contact contato = new Contact();
        contato.FirstName = 'Elera';
        contato.LastName = 'Teste';
        contato.Email = 'teste@gmail.com';
        contato.AccountId = conta.Id;
        insert contato;


        ContractContactRole ccr = new ContractContactRole(
            ContactId = contato.Id,
            ContractId = contract.Id,
            Role = 'Comprador'
        );
        insert ccr;
            
        String ctrName = 'Contract: '+ contract.Id;
        ContentVersion contVersion = new ContentVersion();
        contVersion.ContentLocation = 'S'; // Indíca que será armazenado diretamente no Salesforce 
        contVersion.Title = ctrName;
        contVersion.PathOnClient = ctrName + '.pdf';
        contVersion.VersionData = Blob.valueOf('TEXT');
        insert contVersion;

        ContentVersion contentVersion_1 = [SELECT Id,  ContentDocumentId, Title FROM ContentVersion WHERE Id = :contVersion.Id LIMIT 1];
        ContentDocumentLink contDocumentLink = new ContentDocumentLink();
        contDocumentLink.ContentDocumentId = contentVersion_1.ContentDocumentId;
        contDocumentLink.LinkedEntityId = contract.Id;
        contDocumentLink.shareType = 'V';
        insert contDocumentLink;

    }

    @isTest
    static void testCreate() {
        // Obter dados criados na configuração
        Account account = [SELECT Id, Name FROM Account LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        TemplateDocumento__c template = [SELECT Id FROM TemplateDocumento__c LIMIT 1];
        List<Contact> contacts = [SELECT Id FROM Contact LIMIT 2];

        // Mapear dados de entrada para o método
        Map<String, Object> data = new Map<String, Object>{
            'status' => 'Rascunho',
            'dataInicioContrato' => String.valueOf(Date.today()),
            'dataEnvioParaAssinatura' => String.valueOf(Date.today().addDays(1)),
            'dataAssinaturaCliente' => String.valueOf(Date.today().addDays(2)),
            'conta' => new Map<String, String>{ 'Id' => account.Id, 'Name' => account.Name },
            'template' => template.Id,
            'signatarios' => new List<Map<String, String>>{
                new Map<String, String>{ 'value' => contacts[0].Id, 'role' => 'Signatário 1' }
            },
            'oportunidade' => opp.Id
        };

        // Testar o método de criação
        Test.startTest();
        Contract contract = ContractHelper.create(data);
        Test.stopTest();

        // Verificar resultados
        System.assertNotEquals(null, contract, 'O contrato não deve ser nulo');
        System.assertEquals('ContratoGerado', contract.Status, 'O status do contrato deve ser "ContratoGerado"');

        // Verificar papel de contatos
        List<ContractContactRole> ccrs = [SELECT Id, Role, ContactId FROM ContractContactRole WHERE ContractId = :contract.Id];
        System.assertEquals(1, ccrs.size(), 'Devem existir um papél de contato associado ao contrato');
        System.assertEquals('Signatário 1', ccrs[0].Role, 'O papel do primeiro contato deve ser "Signatário 1"');

        // Verificar versão de conteúdo
        ContentDocumentLink contentLink = [SELECT ContentDocument.Title FROM ContentDocumentLink WHERE LinkedEntityId = :contract.Id LIMIT 1];
        String titleExpected = 'Contract: ' + contract.Id;
        System.assertEquals(contentLink.ContentDocument.Title, titleExpected, 'O título do conteúdo deve começar com "Contrato"');
    }

    @isTest
    static void testDeleteById() {
        Contract ctr = [
            SELECT Id FROM Contract
        ];
        
        Test.startTest();
        ContractHelper.deleteById(ctr.Id);
        Test.stopTest();

        List<Contract> result = [
            SELECT Id FROM Contract
        ];
        System.assertEquals(0, result.size(), 'Deveria ter nenhum item na lista.');
    }

    @IsTest
    static void testGetByOpportunityId() {
        Opportunity opp = [
            SELECT Id FROM Opportunity
        ];

        Test.startTest();
        List<Contract> result = ContractHelper.getByOpportunityId(opp.Id);
        Test.stopTest();

        List<Contract> expected = [
            SELECT Id FROM Contract
        ];

        System.assertEquals(expected.size(), result.size(), 'Deveria conter um contrato na lista.');
    }

    @IsTest
    static void testSendNotification() {
        List<Contract> ctrs = [
            SELECT Id FROM Contract
        ];
        
        Test.startTest();
        ContractHelper.sendNotification(ctrs);
        Test.stopTest();

        Contact ctt = [
            SELECT Id FROM Contact
        ];

        
        List<FeedItem> feeds = [
            SELECT Id, ParentId, Body
            FROM FeedItem
        ];

        System.debug(ctt);

        System.debug(feeds);

        String messageExpected = 'O contrato foi assinado dentro do prazo estipulado.';

        System.assertEquals(messageExpected, feeds[0].Body, 'Deveria conter mensagem de Contrato assinado.');
    }

}