force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>CNPJ da empresa</description>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da unidade</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Disponivel</fullName>
            </value>
            <value>
                <fullName>&lt;&lt;LISTAR STATUS&gt;&gt;</fullName>
                <isActive>false</isActive>
                <label>&lt;&lt;LISTAR STATUS&gt;&gt;</label>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
                <isActive>false</isActive>
                <label>Contrato Assinado</label>
            </value>
            <value>
                <fullName>Contrato Emitido</fullName>
                <isActive>false</isActive>
                <label>Contrato Emitido</label>
            </value>
            <value>
                <fullName>Negociação</fullName>
                <isActive>false</isActive>
                <label>Negociação</label>
            </value>
            <value>
                <fullName>Permuta</fullName>
                <isActive>false</isActive>
                <label>Permuta</label>
            </value>
            <value>
                <fullName>Reserva condicional</fullName>
                <isActive>false</isActive>
                <label>Reserva condicional</label>
            </value>
            <value>
                <fullName>SD Fora de Venda</fullName>
                <isActive>false</isActive>
                <label>SD Fora de Venda</label>
            </value>
            <value>
                <fullName>Venda Integrada</fullName>
                <isActive>false</isActive>
                <label>Venda Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteSyncHelperTest.cls
@IsTest
public class QuoteSyncHelperTest {

    @TestSetup
    static void setupTestData() {
        // Cria uma conta de teste
        Account account = new Account(Name = 'Test Account');
        account.CNPJ__c = '34138415000148';
        insert account;

        // Cria uma oportunidade associada à conta
        Opportunity opportunity = new Opportunity(
            Name = 'Teste Oportunidade',
            AccountId = account.Id,
            CloseDate = System.today().addDays(30),
            StageName = 'Negociação'
        );
        insert opportunity;
    }

    @IsTest
    static void testQuoteSyncTrigger_StatusUpdate() {
		Product2 product = new Product2(name='Product',productCode='XX1234', isActive=true, NumeroDaUnidade__c = 15, 
                                        Status__c = 'Vendida');
        insert product;
    
        id standardPBID = Test.getStandardPricebookId(); 
    
        PricebookEntry stdPBE = new PriceBookEntry(
            Product2Id=product.Id,
            Pricebook2Id=standardPBID,
            UnitPrice = 3000000.00,
            UseStandardPrice = false,
            IsActive=true
        );
    
        insert stdPBE;     
      
        PriceBook2 customPriceBook = new PriceBook2();
        customPriceBook.Name='Custom Pricebook';
        customPriceBook.IsActive=true;
        insert customPriceBook;

        PricebookEntry cusPBE = new PriceBookEntry(
            Product2Id = product.Id,
            Pricebook2Id=customPriceBook.Id,
            UnitPrice = 5000000.00,
            UseStandardPrice = false,
            IsActive=true
        );

        insert cusPBE;

        // Criar uma oportunidade associada ao Pricebook personalizado
        Opportunity opp = new Opportunity(
            Name = 'Test Opportunity',
            Pricebook2Id = customPriceBook.Id, 
            CloseDate = Date.today().addDays(30),
            StageName = 'Prospecting'
        );
        insert opp;

        Opportunity opptest = new Opportunity(
            Name = 'Test Opportunity 1',
            Pricebook2Id = customPriceBook.Id,
            CloseDate = Date.today().addDays(30),
            StageName = 'Prospecting'
        );
        insert opptest;

        
        Opportunity opptest2 = new Opportunity(
            Name = 'Test Opportunity 2',
            Pricebook2Id = customPriceBook.Id, 
            CloseDate = Date.today().addDays(30),
            StageName = 'Prospecting'
        );
        insert opptest2;

        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            PricebookEntryId = cusPBE.Id,
            Quantity = 1,
            TotalPrice = 100
        );
        insert oli;
        
        OpportunityLineItem olitest = new OpportunityLineItem(
            OpportunityId = opptest.Id,
            PricebookEntryId = cusPBE.Id,
            Quantity = 1,
            TotalPrice = 100
        );
        insert olitest;

        Quote quote = new Quote(
            Name = 'Test Quote',
            OpportunityId = opp.Id,
            Pricebook2Id = customPriceBook.Id,
            Status = 'Simulacao'
        );
        insert quote;

        Quote quotetest = new Quote(
            Name = 'Test Quote 2',
            OpportunityId = opptest2.id,
            Pricebook2Id = customPriceBook.Id,
            Status = 'Simulacao'
        );
        insert quotetest;

        System.debug('opptest ' + opptest);

        QuoteLineItem qli = new QuoteLineItem(
            QuoteId = quote.Id,
            PricebookEntryId = cusPBE.Id,
            Quantity = 1,   
            UnitPrice = 100
        );
        insert qli;

        QuoteLineItem qlitest = new QuoteLineItem(
            QuoteId = quotetest.Id,
            PricebookEntryId = cusPBE.Id,
            Quantity = 1,
            UnitPrice = 100
        );
        insert qlitest;
            
        Set<Id> opportunityIds = new Set<Id>();
        opportunityIds.add(quote.OpportunityId);

        System.debug('set ' + opportunityIds);
            
        Map<Id, Quote> syncedQuotesMap = new Map<Id, Quote>(
            [SELECT Id, Name, OpportunityId, IsSyncing  FROM Quote WHERE OpportunityId IN :opportunityIds]
        );
        System.debug('map ' + syncedQuotesMap);

        List<Quote> newQuotes = [SELECT Id, OpportunityId, Status, Name FROM Quote LIMIT 1];
        newQuotes.add(quote);
        newQuotes.add(quotetest);
        System.debug('list ' + newQuotes);

        quote.Status = 'Aprovada';
        update quote;
        
        Quote syncedQuote = syncedQuotesMap.get(quote.OpportunityId);

        Test.startTest();
            QuoteSyncHelper.BeforeInsertOrUpdate(newQuotes);            
        Test.stopTest();

        Quote updatedQuote = [SELECT Id, Status FROM Quote WHERE Id = :quote.Id];
        System.assertEquals('Aprovada', updatedQuote.Status, 'O status da cotação não foi atualizado corretamente.');
    }
    
}