force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>CNPJ da empresa</description>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContractTriggerHandlerTest.cls
@IsTest
public class ContractTriggerHandlerTest {

    @TestSetup
    static void setupData() {
        Account acc = new Account(Name = 'Conta Teste', CNPJ__c = '11084433000199');
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Oportunidade de Teste',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            AccountId = acc.Id
        );
        insert opp;

        Contract contract1 = new Contract(
            Status = 'Rascunho',
            Oportunidade__c = opp.Id,
            AccountId = acc.Id
        );
        Contract contract2 = new Contract(
            Status = 'Rascunho',
            Oportunidade__c = opp.Id,
            AccountId = acc.Id
        );
        insert new List<Contract>{ contract1, contract2 };
    }

    @IsTest
    static void testbeforeUpdate() {
        Contract ctrs = [
            SELECT Id, Status FROM Contract LIMIT 1
        ];
        ctrs.Status = 'ContratoGerado';

        update ctrs;
    }
}