force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>CNPJ da empresa</description>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <label>Bloco</label>
    <nameField>
        <label>Nome do Bloco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Bloco__c/fields/DataEntrega__c.field-meta.xml
<CustomField>
    <fullName>DataEntrega__c</fullName>
    <label>Data de Entrega</label>
    <type>Date</type>
</CustomField>

you/force-app/main/default/objects/Bloco__c/fields/DataLancamento__c.field-meta.xml
<CustomField>
    <fullName>DataLancamento__c</fullName>
    <label>Data de Lançamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Deve ser preenchido com o empreeendimento corespondente.</description>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Blocos</relationshipLabel>
    <relationshipName>Blocos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/QuantidadeAndares__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAndares__c</fullName>
    <description>Deve ser preenchido 
 com a quantidade
  de andares da Torre.</description>
    <label>Quantidade de Andares</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/TotalUnidades__c.field-meta.xml
<CustomField>
    <fullName>TotalUnidades__c</fullName>
    <description>Deve ser preenchido com a quantidade de andares por Torre.</description>
    <label>Total de Unidades</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Empreendimento__c/fields/SPE__c.field-meta.xml
<CustomField>
    <fullName>SPE__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SPE (Sociedade de Propósito Específico)</description>
    <label>SPE</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPE</relationshipLabel>
    <relationshipName>Empreendimentos</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/StatusObra__c.field-meta.xml
<CustomField>
    <fullName>StatusObra__c</fullName>
    <description>Status da obra do empreendimento</description>
    <label>Status da Obra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em construção</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Lançamento</fullName>
            </value>
            <value>
                <fullName>Pré-Lançamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/TipoEmpreendimento__c.field-meta.xml
<CustomField>
    <fullName>TipoEmpreendimento__c</fullName>
    <label>Tipo de Empreendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Lote</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da unidade</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Disponivel</fullName>
            </value>
            <value>
                <fullName>&lt;&lt;LISTAR STATUS&gt;&gt;</fullName>
                <isActive>false</isActive>
                <label>&lt;&lt;LISTAR STATUS&gt;&gt;</label>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
                <isActive>false</isActive>
                <label>Contrato Assinado</label>
            </value>
            <value>
                <fullName>Contrato Emitido</fullName>
                <isActive>false</isActive>
                <label>Contrato Emitido</label>
            </value>
            <value>
                <fullName>Negociação</fullName>
                <isActive>false</isActive>
                <label>Negociação</label>
            </value>
            <value>
                <fullName>Permuta</fullName>
                <isActive>false</isActive>
                <label>Permuta</label>
            </value>
            <value>
                <fullName>Reserva condicional</fullName>
                <isActive>false</isActive>
                <label>Reserva condicional</label>
            </value>
            <value>
                <fullName>SD Fora de Venda</fullName>
                <isActive>false</isActive>
                <label>SD Fora de Venda</label>
            </value>
            <value>
                <fullName>Venda Integrada</fullName>
                <isActive>false</isActive>
                <label>Venda Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Product2/fields/ValorM2__c.field-meta.xml
<CustomField>
    <fullName>ValorM2__c</fullName>
    <label>Valor (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Apartamento.recordType-meta.xml
<RecordType>
    <fullName>Apartamento</fullName>
    <active>true</active>
    <label>Apartamento</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Casa.recordType-meta.xml
<RecordType>
    <fullName>Casa</fullName>
    <active>true</active>
    <label>Casa</label>
</RecordType>

you/force-app/main/default/objects/Quote/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Cotações</relationshipLabel>
    <relationshipName>Cota_es</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteDATest.cls
@IsTest
public class QuoteDATest {
    
    @TestSetup
    static void makeData() {
        Account account = new Account(Name = 'Test Account');
        account.CNPJ__c = '34138415000148';
        insert account;
        
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Nome do Empreendimento',
        SPE__c = account.Id,
        CNPJEmpreendimento__c = '04682086000130',
        TipoEmpreendimento__c = 'Casa',
        StatusObra__c = 'Entregue',
        MetragemPrivativaTotal__c = 5000,
        MetragemTerreno__c = 10000,
        MetragemConstruIdaM__c = 7000
            );
        insert empreendimento;
        
        Bloco__c bloco = new Bloco__c(
            Name = 'Nome do Bloco',
        DataLancamento__c = Date.today(),
        DataEntrega__c = Date.today().addMonths(12),
        Empreendimento__c = empreendimento.Id,
        QuantidadeAndares__c = 10,
        TotalUnidades__c = 50
            );
        insert bloco;
        
        Product2 unidade = new Product2(
            Name = 'Nome do Produto do Apartamento',
        ProductCode = '854785964',
        ExternalId = '10',
        Empreendimento__c = empreendimento.Id,
        Bloco__c = bloco.Id,
        NumeroDaUnidade__c = 25,
        ValorM2__c = 8,
        Status__c = 'Reservada'
            );
        insert unidade;
        
        Opportunity opportunity = new Opportunity(
            Name = 'Test Opportunity',
        AccountId = account.Id,
        CloseDate = System.today().addDays(30),
        StageName = 'Negociacao'
            );
        insert opportunity;
    }
    
    @IsTest
    static void testGetQuotesMapByIds() {
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        Product2 unidade = [SELECT Id FROM Product2 LIMIT 1];
        
        Id standardPricebook = Test.getStandardPricebookId();
        
        PricebookEntry pricebookEntry = new PricebookEntry(
            Product2Id = unidade.Id,
        Pricebook2Id = standardPricebook,
        UnitPrice = 100,
        IsActive = true
            );
        insert pricebookEntry;
        
        Quote quote = new Quote(
            Name = 'Test Quote',
        OpportunityId = opportunity.Id,
        Pricebook2Id = standardPricebook
            );
        insert quote;
        
        Test.startTest();
        Map<Id, Quote> quotesMap = QuoteDA.getQuotesMapByIds(new List<Id>{quote.Id});
        Test.stopTest();
        
        System.assertEquals(1, quotesMap.size(), 'Deve haver 1 cotação no mapa.');
        System.assertNotEquals(null, quotesMap.get(quote.Id), 'A cotação no mapa não deve ser nula.');
    }
    
    @IsTest
    static void testGetProductByQuoteId() {
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        Product2 unidade = [SELECT Id FROM Product2 LIMIT 1];
        
        Id standardPricebook = Test.getStandardPricebookId();
        
        PricebookEntry pricebookEntry = new PricebookEntry(
            Product2Id = unidade.Id,
        Pricebook2Id = standardPricebook,
        UnitPrice = 100,
        IsActive = true
            );
        insert pricebookEntry;
        
        Quote quote = new Quote(
            Name = 'Test Quote',
        OpportunityId = opportunity.Id,
        Pricebook2Id = standardPricebook
            );
        insert quote;
        
        QuoteLineItem quoteLineItem = new QuoteLineItem(
            QuoteId = quote.Id,
        Product2Id = unidade.Id,
        PricebookEntryId = pricebookEntry.Id,
        Quantity = 1,
        UnitPrice = 100
            );
        insert quoteLineItem;
        
        Test.startTest();
        Product2 product = QuoteDA.getProductByQuoteId(quote.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, product, 'O produto da cotação não deve ser nulo.');
    }
    
    @IsTest
    static void testGetQuoteLineItemsByQuoteId() {
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        Product2 unidade = [SELECT Id FROM Product2 LIMIT 1];
        
        Id standardPricebook = Test.getStandardPricebookId();
        
        PricebookEntry pricebookEntry = new PricebookEntry(
            Product2Id = unidade.Id,
        Pricebook2Id = standardPricebook,
        UnitPrice = 100,
        IsActive = true
            );
        insert pricebookEntry;
        
        Quote quote = new Quote(
            Name = 'Test Quote',
        OpportunityId = opportunity.Id,
        Pricebook2Id = standardPricebook
            );
        insert quote;
        
        QuoteLineItem quoteLineItem = new QuoteLineItem(
            QuoteId = quote.Id,
        Product2Id = unidade.Id,
        PricebookEntryId = pricebookEntry.Id,
        Quantity = 1,
        UnitPrice = 100
            );
        insert quoteLineItem;
        
        Test.startTest();
        List<QuoteLineItem> lineItems = QuoteDA.getQuoteLineItemsByQuoteId(quote.Id);
        Test.stopTest();
        
        System.assertEquals(1, lineItems.size(), 'Deve haver 1 item de linha na cotação.');
        System.assertEquals(quote.Id, lineItems[0].QuoteId, 'O ID da cotação do item de linha deve corresponder ao ID da cotação.');
    }

    @IsTest
    static void testGetProductByQuoteId_NullScenario() {
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        Id standardPricebook = Test.getStandardPricebookId();

        // Criando uma cotação sem associar um QuoteLineItem
        Quote quote = new Quote(
            Name = 'Test Quote',
            OpportunityId = opportunity.Id,
            Pricebook2Id = standardPricebook
        );
        insert quote;

        // Teste para validar o cenário onde não há QuoteLineItem associado
        Test.startTest();
        Product2 productNull = QuoteDA.getProductByQuoteId(quote.Id);
        Test.stopTest();

        // Validação do cenário nulo
        System.assertEquals(null, productNull, 'O produto da cotação deve ser nulo quando não há item de linha.');
    }
    
    @IsTest
    static void testGetOrCreatePricebookEntryId() {
        Product2 testProduct = [SELECT Id FROM Product2 LIMIT 1];
        
        Test.startTest();
        Id pbeId = QuoteDA.getOrCreatePricebookEntryId(testProduct.Id, null);
        Test.stopTest();
        
        System.assertNotEquals(null, pbeId, 'O ID do PricebookEntry não deve ser nulo.');
        PricebookEntry createdPBE = [SELECT Id FROM PricebookEntry WHERE Id = :pbeId];
        System.assertNotEquals(null, createdPBE, 'O registro do PricebookEntry deve existir.');
    }
}