force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <description>CNPJ da empresa</description>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <label>Bloco</label>
    <nameField>
        <label>Nome do Bloco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blocos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Deve ser preenchido com o empreeendimento corespondente.</description>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Blocos</relationshipLabel>
    <relationshipName>Blocos</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/PrazoAssinatura__c.field-meta.xml
<CustomField>
    <fullName>PrazoAssinatura__c</fullName>
    <label>Prazo para Assinatura</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Contrato.recordType-meta.xml
<RecordType>
    <fullName>Contrato</fullName>
    <active>true</active>
    <label>Contrato</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da unidade</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Disponivel</fullName>
            </value>
            <value>
                <fullName>&lt;&lt;LISTAR STATUS&gt;&gt;</fullName>
                <isActive>false</isActive>
                <label>&lt;&lt;LISTAR STATUS&gt;&gt;</label>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
                <isActive>false</isActive>
                <label>Contrato Assinado</label>
            </value>
            <value>
                <fullName>Contrato Emitido</fullName>
                <isActive>false</isActive>
                <label>Contrato Emitido</label>
            </value>
            <value>
                <fullName>Negociação</fullName>
                <isActive>false</isActive>
                <label>Negociação</label>
            </value>
            <value>
                <fullName>Permuta</fullName>
                <isActive>false</isActive>
                <label>Permuta</label>
            </value>
            <value>
                <fullName>Reserva condicional</fullName>
                <isActive>false</isActive>
                <label>Reserva condicional</label>
            </value>
            <value>
                <fullName>SD Fora de Venda</fullName>
                <isActive>false</isActive>
                <label>SD Fora de Venda</label>
            </value>
            <value>
                <fullName>Venda Integrada</fullName>
                <isActive>false</isActive>
                <label>Venda Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/ConteudoTemplate__c.field-meta.xml
<CustomField>
    <fullName>ConteudoTemplate__c</fullName>
    <label>Conteúdo do Template</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Templates_de_Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TemplateDocumento__c/fields/TipoTemplate__c.field-meta.xml
<CustomField>
    <fullName>TipoTemplate__c</fullName>
    <label>Tipo de Template</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contrato</fullName>
            </value>
            <value>
                <fullName>Outro Documento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContratoServiceTest.cls
@isTest
public class ContratoServiceTest {
    @TestSetup
    static void makeData(){
        Empreendimento__c emp = new Empreendimento__c();
        emp.Name = 'Empreendimento de Teste';
        emp.CNPJEmpreendimento__c = '11084433000199';
        insert emp;
        
        TemplateDocumento__c template = new TemplateDocumento__c(Name = 'Template Test', Empreendimento__c = emp.Id, TipoTemplate__c = 'Contrato', ConteudoTemplate__c = 'Teste Opportunity.Name, OpportunityContactRole.Role', Ativo__c = true);
        insert template;

        Account acc = new Account(Name = 'Conta Teste', CNPJ__c = '11084433000199');
        insert acc;

        Contact cont = new Contact(
            FirstName = 'Contato', 
            LastName = 'Teste', 
            AccountId = acc.Id, 
            CPF__c = '88637869092',
            Email = 'teste@gmail.com'
            );
        insert cont;

        Bloco__c bloco = new Bloco__c(Name = 'Bloco Teste');
        insert bloco;

        Product2 prd = new Product2(Name = 'Produto Teste', Bloco__c = bloco.Id, Status__c = 'Reservada', NumeroDaUnidade__c = 101);
        insert prd;

        Pricebook2 pricebook = new Pricebook2(
            Name = 'test',
            isActive = true
        );
        insert pricebook;

        Opportunity opp = new Opportunity(
            AccountId = acc.Id, 
            Name = 'Oportunidade de Teste', 
            Unidade__c = prd.Id, 
            Empreendimento__c = emp.Id, 
            StageName = 'Negociação', 
            CloseDate = Date.today(),
            Pricebook2Id = pricebook.Id
        );
        insert opp;

        
        PricebookEntry pricebookStandard = new PricebookEntry(
            Pricebook2Id = Test.getStandardPricebookId(),
            Product2Id = prd.Id,
            UnitPrice = 100,
            IsActive = true
        );

        PricebookEntry pricebookEntry = new PricebookEntry(
            Pricebook2Id = pricebook.Id,
            Product2Id = prd.Id,
            UnitPrice = 100,
            IsActive = true
        );
        insert new List<PricebookEntry> { pricebookStandard, pricebookEntry };
        

        Contract ctt = new Contract(
            Name = 'Contrato Teste', 
            AccountId = acc.Id, 
            Status = 'Rascunho', 
            Oportunidade__c = opp.Id,
            PrazoAssinatura__c = Date.today().addDays(-2)
        );
        insert ctt;

        OpportunityContactRole role = new OpportunityContactRole(
            Role = 'Fiador', 
            ContactId = cont.Id, 
            OpportunityId = opp.Id
        );
        insert role;

        OpportunityLineItem opli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Product2Id = prd.Id,
            PricebookEntryId = pricebookEntry.Id,
            Quantity = 3,
            TotalPrice = 12
        );
        insert opli;
    }

    @isTest
    static void testContratoText(){
        Opportunity opp = [SELECT Id, Empreendimento__c, AccountId, Unidade__c, Name FROM Opportunity LIMIT 1];
        TemplateDocumento__c template = [SELECT Id, ConteudoTemplate__c FROM TemplateDocumento__c LIMIT 1];
        OpportunityContactRole role = [SELECT Id, Role, ContactId FROM OpportunityContactRole WHERE OpportunityId = :opp.Id LIMIT 1];
        Contact cont = [SELECT Id, Name FROM Contact WHERE Id = :role.ContactId LIMIT 1];

        String text = ContratoService.contratoText(opp, template);
        System.assertNotEquals(null, text);
        System.assertEquals('Teste '+ opp.Name + ', ' + cont.Name + ' - '+ role.Role, text);
    }

    @isTest
    static void testAtualizarPrazoAssinatura(){
        Contract ctt = [SELECT Id, Status, CustomerSignedDate, PrazoAssinatura__c FROM Contract LIMIT 1];

        Test.startTest();
        ContratoService.atualizarPrazoAssinatura(new List<Contract>{ctt});
        Test.stopTest();
    }


    @IsTest
    static void testEvitarGeracaoMultipla() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Contract contrato1 = [SELECT Id, Status, Oportunidade__c FROM Contract WHERE Oportunidade__c = :opp.Id LIMIT 1];

        contrato1.Status = 'ContratoGerado';
        Test.startTest();
        try {
            update contrato1;
            ContratoService.evitarGeracaoMultipla(new List<Contract>{ contrato1 });
        } catch (Exception e) {
         
        }
        Test.stopTest();
    }

    @IsTest
    static void testVerificaPrazoAssinatura() {
        Opportunity opp = [SELECT Id, StageName, Unidade__c, Empreendimento__c FROM Opportunity LIMIT 1];

        Account acct  = [SELECT Id FROM Account LIMIT 1];
        Contact contato = [SELECT Id, Name FROM Contact WHERE AccountId = :acct.Id LIMIT 1];
        
        OpportunityContactRole role = [SELECT Id FROM OpportunityContactRole WHERE OpportunityId = :opp.Id LIMIT 1];

        Contract contrato = [SELECT Id, Status, CustomerSignedDate, PrazoAssinatura__c, Oportunidade__c FROM Contract LIMIT 1];
        contrato.Status = 'EmAssinatura';
        update contrato;
        
        Test.startTest();
        ContratoService.verificaPrazoAssinatura(new List<Contract>{ contrato });
        Test.stopTest();
    }
}