force-app/main/default/objects/Account/fields/EmailJuridico__c.field-meta.xml
<CustomField>
    <fullName>EmailJuridico__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/Relacionamento__c.field-meta.xml
<CustomField>
    <fullName>Relacionamento__c</fullName>
    <label>Relacionamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cônjuge/Companheiro</fullName>
            </value>
            <value>
                <fullName>Pai</fullName>
            </value>
            <value>
                <fullName>Mãe</fullName>
            </value>
            <value>
                <fullName>Irmão/Irmã</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AnaliseCredito__c/AnaliseCredito__c.object-meta.xml
<CustomObject>
    <label>Análise de Crédito</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Análises de Crédito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AnaliseCredito__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Análises de Crédito</relationshipLabel>
    <relationshipName>Analises_de_Credito</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnaliseCredito__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Análises de Crédito</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecionar se for corretor.</description>
    <label>Corretor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <infoMessage>Corretor: Tipo de registro do contatoigual aCorretor</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityContactRole/fields/PorcentagemParticipacao__c.field-meta.xml
<CustomField>
    <fullName>PorcentagemParticipacao__c</fullName>
    <label>% de participação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/OpportunityDA.cls
public with sharing class OpportunityDA {
    
    public static Map<Id, Opportunity> getOpportunitiesWithQuote(Set<Id> opportunityIds) {
        return new Map<Id, Opportunity>([
            SELECT Id, Pricebook2Id, SyncedQuoteId
            FROM Opportunity
            WHERE Id IN :opportunityIds AND Pricebook2Id != null
        ]);
    }
    
    public static Boolean hasSyncedQuote(Id opportunityId) {
        Opportunity opp;
        try {
            opp = [
                SELECT SyncedQuoteId
                FROM Opportunity
                WHERE Id = :opportunityId
            ];
        } catch (QueryException e) {
            System.debug('Erro ao consultar oportunidade: ' + e.getMessage());
            return false;
        }
        
        return !String.isBlank(opp.SyncedQuoteId);
    }
    
    public static List<OpportunityLineItem> getOpportunityLineItems(Id opportunityId) {
        return [
            SELECT Id, OpportunityId, Product2Id
            FROM OpportunityLineItem
            WHERE OpportunityId = :opportunityId
        ];
    }
    
    public static List<OpportunityContactRole> getOpportunityContactRoles(Id opportunityId) {
        return [
            SELECT Id, OpportunityId, ContactId
            FROM OpportunityContactRole
            WHERE OpportunityId = :opportunityId
        ];
    }
    
    public static List<OpportunityContactRole> getOpportunityContactRolesPercent(Id opportunityId) {
        return [
            SELECT Id, OpportunityId, ContactId, PorcentagemParticipacao__c 
            FROM OpportunityContactRole
            WHERE OpportunityId = :opportunityId
        ];
    }
    
    public static List<AccountContactRelation> getAccountsWithSpouse(Set<Id> accountIds) {
        if (accountIds.isEmpty()) {return new List<AccountContactRelation>(); }

        return [
            SELECT AccountId 
            FROM AccountContactRelation 
            WHERE AccountId IN :accountIds AND Relacionamento__c = 'Cônjuge/Companheiro'
        ];
    }
    
    // Método para obter o mapa de contagem de análises de crédito por oportunidade
    public static Map<Id, Integer> getAnaliseCreditoCountByOpportunity(Set<Id> opportunityIds) {
        Map<Id, Integer> mapAnalisesRelacionadas = new Map<Id, Integer>();
        
        List<AggregateResult> aggregateResults = [
        SELECT COUNT(Id) quantidade, Opportunity__c
        FROM AnaliseCredito__c
        WHERE Opportunity__c IN :opportunityIds
        GROUP BY Opportunity__c
    ];
        
        for (AggregateResult ag : aggregateResults) {
            Id oppId = (Id) ag.get('Opportunity__c');
            Integer quantidade = (Integer) ag.get('quantidade');
            mapAnalisesRelacionadas.put(oppId, quantidade);
        }
        
        return mapAnalisesRelacionadas;
    }
    
    public static Boolean getOpportunityWithChecklistApproval(Id opportunityId) {
        List<ProcessInstance> processInstances = [
        SELECT Id, 
            ProcessDefinition.DeveloperName, 
            Status 
        FROM ProcessInstance 
        WHERE TargetObjectId = :opportunityId 
        AND ProcessDefinition.DeveloperName = 'ProcessoAprovacaoChecklist'
        AND Status = 'Approved' 
    ];
        
        return !processInstances.isEmpty();
    }
    
    public static List<Opportunity> getAllByAnaliseCreditoId(Set<Id> idsAnalise) {
        if (idsAnalise == null) {return new List<Opportunity>();}
        
        return [
            SELECT Id, Name, AccountId, Corretor__c, StageName, Type
            FROM Opportunity
            WHERE Id IN (
                SELECT Opportunity__c
                FROM AnaliseCredito__c
                WHERE Id IN :idsAnalise 
            )
        ];
    }
    
    public static List<Opportunity> getByAnaliseCreditoId(Id idAnalise) {
        if (idAnalise == null) {return new List<Opportunity>();}
        
        return [
            SELECT Id, Name, AccountId, Corretor__c, StageName, Type
            FROM Opportunity
            WHERE Id IN (
                SELECT Opportunity__c
                FROM AnaliseCredito__c
                WHERE Id = :idAnalise
            )
        ];
    }
    
    public static List<Opportunity> getAllById(Set<Id> ids) {
        if (ids == null) {return new List<Opportunity>();}
        
        return [
            SELECT Id, 
                Name, 
                AccountId, 
                Account.PersonEmail, 
                Account.EmailJuridico__c, 
                Corretor__c, 
                Corretor__r.Email,
                Empreendimento__c, 
                OwnerId, 
                Owner.Email 
            FROM Opportunity
            WHERE Id IN :ids
        ];
    }

    public static Opportunity getById(Id id) {
        try {
            return [
                SELECT Id, 
                    Name, 
                    AccountId, 
                    Account.PersonEmail, 
                    Account.EmailJuridico__c, 
                    Corretor__c, 
                    Corretor__r.Email,
                    Empreendimento__c, 
                    OwnerId, 
                    Owner.Email,
                    Unidade__c
                FROM Opportunity
                WHERE Id = :id
            ];
        } catch (Exception e) {
            return null;
        }
    }
 
    public static List<OpportunityLineItem> getProductsById(Id id) {
        try {
            return [
                SELECT Id, OpportunityId, Product2Id 
                FROM OpportunityLineItem
                WHERE OpportunityId = :id
            ];
        } catch (Exception e) {
            return null;
        }
    }

}