force-app/main/default/objects/Account/fields/EmailJuridico__c.field-meta.xml
<CustomField>
    <fullName>EmailJuridico__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Conta.recordType-meta.xml
<RecordType>
    <fullName>Conta</fullName>
    <active>true</active>
    <label>Conta</label>
</RecordType>

force-app/main/default/objects/AnaliseCredito__c/AnaliseCredito__c.object-meta.xml
<CustomObject>
    <label>Análise de Crédito</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Análises de Crédito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AnaliseCredito__c/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AnaliseCredito__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Análises de Crédito</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnaliseCredito__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reprovada</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AnaliseCredito__c/recordTypes/AnaliseCredito.recordType-meta.xml
<RecordType>
    <fullName>AnaliseCredito</fullName>
    <active>true</active>
    <label>Análise de Crédito</label>
</RecordType>

force-app/main/default/objects/Checklist_de_Documentos__c/Checklist_de_Documentos__c.object-meta.xml
<CustomObject>
    <label>Checklist de Documentos</label>
    <nameField>
        <label>Nome de Checklist de Documentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Documenta_o__c.field-meta.xml
<CustomField>
    <fullName>Documenta_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentação</label>
    <referenceTo>Documentacao__c</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <description>Documentação de contato</description>
    <label>Documentação</label>
    <nameField>
        <label>Nome de Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Documentacao__c/fields/AnaliseCredito__c.field-meta.xml
<CustomField>
    <fullName>AnaliseCredito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Análise de Crédito</label>
    <referenceTo>AnaliseCredito__c</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documenta_es</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Entregue__c.field-meta.xml
<CustomField>
    <fullName>Entregue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entregue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Validado__c.field-meta.xml
<CustomField>
    <fullName>Validado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Descreve se o documento foi ou está validado ou não.</description>
    <label>Validado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo De Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negócio existente</fullName>
                <default>true</default>
                <label>Negócio existente</label>
            </value>
            <value>
                <fullName>Negócio novo</fullName>
            </value>
            <value>
                <fullName>Financiamento Bancário</fullName>
                <isActive>false</isActive>
                <label>Financiamento Bancário</label>
            </value>
            <value>
                <fullName>Financiamento Direto</fullName>
                <isActive>false</isActive>
                <label>Financiamento Direto</label>
            </value>
            <value>
                <fullName>Venda a Vista</fullName>
                <isActive>false</isActive>
                <label>Venda a Vista</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AnaliseCreditoTriggerHandlerTest.cls
@IsTest
public with sharing class AnaliseCreditoTriggerHandlerTest {
    
    @TestSetup
    static void setup() {
        // Criando um Account
        Account accTest = new Account(
            Name = 'Conta Teste',
            EmailJuridico__c = 'teste.@elera.io'
        );
        insert accTest;
        
        // Criando uma Opportunity
        Opportunity opp1 = new Opportunity(
            Name = 'Teste',
            Amount = 1000,
            CanalAtendimento__c = 'WhatsApp',
            Probability = 20,
            TipoVenda__c = 'Negócio novo',
            StageName = 'Pré-análise',
            CloseDate = System.today().addDays(15),
            AccountId = accTest.Id
        );
        insert opp1;

        // Criando um Documento
        Documentacao__c doc = new Documentacao__c(
            Name = 'Documento test',
            Obrigatorio__c = true,
            Entregue__c = false,
            Validado__c = false
        );
        insert doc;

        // Criando um Checklist de Documentos
        Checklist_de_Documentos__c checklists = new Checklist_de_Documentos__c(
            Oportunidade__c = opp1.Id,
            Documenta_o__c = doc.Id
        );
        insert checklists;
    }
    
    @IsTest
    static void testBeforeInsert() {
        Opportunity oppTest = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        
        AnaliseCredito__c analise1 = gerarAnaliseCredito(oppTest.Id);
        AnaliseCredito__c analise2 = gerarAnaliseCredito(oppTest.Id);
        analise2.Status__c = 'Aprovada';
        
        Test.startTest();
        insert new List<AnaliseCredito__c>{ analise1, analise2 };
        Test.stopTest();
    }

    @IsTest
    static void testBeforeUpdate() {
        Opportunity oppTest = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        
        AnaliseCredito__c analise1 = gerarAnaliseCredito(oppTest.Id);
        AnaliseCredito__c analise2 = gerarAnaliseCredito(oppTest.Id);
        insert new List<AnaliseCredito__c>{ analise1, analise2 };

        analise1.Status__c = 'Aprovada';
        analise2.Name = 'SIRRRRR';

        Test.startTest();
        update new List<AnaliseCredito__c>{ analise1, analise2 };
        Test.stopTest();
    }

    @IsTest
    static void testAfterInsert() {
        Opportunity oppTest = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        
        AnaliseCredito__c analise1 = gerarAnaliseCredito(oppTest.Id);
        AnaliseCredito__c analise2 = gerarAnaliseCredito(oppTest.Id);
        
        Test.startTest();
        insert new List<AnaliseCredito__c>{ analise1, analise2 };
        Test.stopTest();
    }

    @IsTest
    static void testAfterUpdate() {
        Opportunity oppTest = [SELECT Id, StageName FROM Opportunity LIMIT 1];
        
        AnaliseCredito__c analise1 = gerarAnaliseCredito(oppTest.Id);
        AnaliseCredito__c analise2 = gerarAnaliseCredito(oppTest.Id);
        insert new List<AnaliseCredito__c>{ analise1, analise2 };

        analise1.Status__c = 'Aprovada';
        analise2.Name = 'SIRRRRR';

        Test.startTest();
        update new List<AnaliseCredito__c>{ analise1, analise2 };
        Test.stopTest();
    }

    // Método auxiliar para gerar AnaliseCredito
    private static AnaliseCredito__c gerarAnaliseCredito(Id oppId) {
        return new AnaliseCredito__c(
            Name = 'Teste',
            Status__c = 'Em Análise',
            Opportunity__c = oppId,
            DataVencimento__c = Date.today()
        );
    }
}