force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/Product2/fields/ValorM2__c.field-meta.xml
<CustomField>
    <fullName>ValorM2__c</fullName>
    <label>Valor (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/DescontoNominalMoeda__c.field-meta.xml
<CustomField>
    <fullName>DescontoNominalMoeda__c</fullName>
    <inlineHelpText>Máximo de desconto permitido dentro do Simulador</inlineHelpText>
    <label>Desconto Nominal (Moeda)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TabelaVendaComparacao.cls
public class TabelaVendaComparacao {
    @AuraEnabled(cacheable=true)

    public static Opportunity obterTabelaPorId(Id oppId) {
        // Obter o Empreendimento relacionado à Oportunidade
        Opportunity opp = [SELECT Id, Empreendimento__c FROM Opportunity WHERE Id = :oppId LIMIT 1];

        // Verificar se a Oportunidade retornou um Empreendimento
        if (opp.Empreendimento__c != null) {
            // Obter o Desconto Nominal da Tabela de Vendas relacionada ao Empreendimento
            TabelaVendas__c tabelaVenda = [SELECT Id, DescontoNominalMoeda__c
                                           FROM TabelaVendas__c 
                                           WHERE Empreendimento__c = :opp.Empreendimento__c 
                                           LIMIT 1];

            // Obter o Valor por metro quadrado (ValorM2__c) de um produto relacionado ao Empreendimento
            Product2 produto = [SELECT Id, ValorM2__c
                                FROM Product2 
                                WHERE Empreendimento__c = :opp.Empreendimento__c 
                                LIMIT 1];

            // Atribuir esses valores a propriedades na Opportunity ou retorná-los de outra forma

            opp.put('DescontoNominalMoeda__c', tabelaVenda.DescontoNominalMoeda__c);
            opp.put('ValorM2__c', produto.ValorM2__c);
        }

        return opp;
    }
}