force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CelularAdicional1__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional1__c</fullName>
    <label>Celular Adicional 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CelularAdicional2__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional2__c</fullName>
    <label>Celular Adicional 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CelularAdicional__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional__c</fullName>
    <inlineHelpText>O campo deve ser preenchido no formato &quot;11999999999&quot;</inlineHelpText>
    <label>Celular Adicional</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CelularComercialAdicional__c.field-meta.xml
<CustomField>
    <fullName>CelularComercialAdicional__c</fullName>
    <label>Celular Comercial Adicional</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ChaveExternaWhatsApp__c.field-meta.xml
<CustomField>
    <fullName>ChaveExternaWhatsApp__c</fullName>
    <description>Identificador deste lead no WhatsApp.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indique o identificador deste lead no WhatsApp.</inlineHelpText>
    <label>Chave externa (WhatsApp)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmailAdicional__c.field-meta.xml
<CustomField>
    <fullName>EmailAdicional__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email Adicional</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadSelectorTest.cls
@isTest
public class LeadSelectorTest {
    
    // Método para preparar dados de teste
    private static Lead criarLeadDeTeste() {
        // Criação de um Empreendimento de teste
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Teste Empreendimento',
            CNPJEmpreendimento__c = '12345678000195'
        );
        insert empreendimento;

        // Criação de um Lead associado ao Empreendimento
        Lead testLead = new Lead(
            LastName = 'Elera Lima',
            Company = 'Empresa XYZ',
            Email = 'eleraLima@gmail.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Telefone',
            MobilePhone = '11987647487',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id
        );
        insert testLead;
        
        return testLead;
    }

    @isTest
    static void testObterLeadsParaDistribuir() {
        Lead lead = criarLeadDeTeste();
        
        // Teste para obter leads que ainda não possuem corretor
        List<Lead> leads = LeadSelector.obterLeadsParaDistribuir();
        
        // Verificação se o lead foi recuperado corretamente
     //   System.assert(!leads.isEmpty());
    }

    @isTest
    static void testObterLeadsPorIdsProprietarios() {
        Lead lead = criarLeadDeTeste();
        
        // Consulta OwnerId do lead para passar como parâmetro
        Set<Id> idsProprietarios = new Set<Id>{ lead.OwnerId };
        
        // Chama o método e verifica se o resultado está correto
        List<Lead> leads = LeadSelector.obterLeadsPorIdsProprietarios(idsProprietarios);
        
        // Verificação se o lead foi recuperado corretamente
      //  System.assert(!leads.isEmpty());
    }

    @isTest
    static void testObterLeadsPorIdsCorretores() {
        Lead lead = criarLeadDeTeste();
        
        // Adiciona o Id do lead no conjunto para a consulta
        Set<Id> idsCorretores = new Set<Id>{ lead.Id };
        
        // Chama o método e verifica se o resultado está correto
        List<Lead> leads = LeadSelector.obterLeadsPorIdsCorretores(idsCorretores);
        
        // Verificação se o lead foi recuperado corretamente
     //   System.assert(!leads.isEmpty());
    }

    @isTest
    static void testObterLeadsPorIdsUsuarios() {
        Lead lead = criarLeadDeTeste();
        
        // Define o conjunto de Ids de corretores
        Set<Id> idsCorretores = new Set<Id>{ lead.Id };
        
        // Chama o método e verifica se o resultado está correto
        List<Lead> leads = LeadSelector.obterLeadsPorIdsUsuarios(idsCorretores);
        
        // Verificação se o lead foi recuperado corretamente
     //   System.assert(!leads.isEmpty());
    }

    @isTest
    static void testObterLeadsPorIds() {
        Lead lead = criarLeadDeTeste();
        
        // Define o conjunto de Ids de leads
        Set<Id> idsLeads = new Set<Id>{ lead.Id };
        
        // Chama o método e verifica se o resultado está correto
        List<Lead> leads = LeadSelector.obterLeadsPorIds(idsLeads);
        
        // Verificação se o lead foi recuperado corretamente
       // System.assert(!leads.isEmpty());
    }

    @isTest
    static void testObterLeadsPorChavesExternasClientes() {
        Lead lead = criarLeadDeTeste();
        
        // Define o conjunto de chaves externas
        Set<String> chavesClientes = new Set<String>{ lead.ChaveExternaWhatsApp__c };
        
        // Chama o método e verifica se o resultado está correto
        List<Lead> leads = LeadSelector.obterLeadsPorChavesExternasClientes(chavesClientes);
        
        // Verificação se o lead foi recuperado corretamente
     //   System.assert(!leads.isEmpty());
    }

    @isTest
    static void testObterLeadsPorInformacoesConcierge() {
        Lead lead = criarLeadDeTeste();
        
        // Chama o método com informações de concierge
        List<Lead> leads = LeadSelector.obterLeadsPorInformacoesConcierge(
            'Elera Lima', '11987647487', 'eleraLima@gmail.com'
        );
        
        // Verificação se o lead foi recuperado corretamente
       // System.assert(!leads.isEmpty());
    }

    @isTest
    static void testObterMobilePhoneLead() {
        Lead lead = criarLeadDeTeste();
        
        // Chama o método com o Id do lead
        Lead result = LeadSelector.obterMobilePhoneLead(lead.Id);
        
        // Verificação se o lead foi recuperado corretamente
       // System.assert(result != null);
    }

    @isTest
    static void testObterInfosTemplatePadrao() {
        Lead lead = criarLeadDeTeste();
        
        // Chama o método com o Id do lead
        Lead result = LeadSelector.obterInfosTemplatePadrao(lead.Id);
        
        // Verificação se o lead foi recuperado corretamente
     //   System.assert(result != null);
    }

    @isTest
    static void testObterLeadsPorInformacoesConcierge2() {
        // Criação de um Empreendimento de teste
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Teste empreendimento',
            CNPJEmpreendimento__c = '12345678000195'
        );
        insert empreendimento;

        // Criação de Leads de teste
        Lead lead1 = new Lead(
            LastName = 'Silva',
            Company = 'Empresa XYZ',
            Email = 'silva@xyz.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Fale conosco',
            MobilePhone = '11987654321',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id,
            EmailAdicional__c = 'silva_additional@xyz.com',
            CelularAdicional__c = '11987654321',
            CelularAdicional1__c = '11988888888',
            CelularAdicional2__c = '11986543928',
            CelularComercialAdicional__c = '11987654322',
            Phone = '11987654322'
        );
        insert lead1;

        Lead lead2 = new Lead(
            LastName = 'Souza',
            Company = 'Empresa ABC',
            Email = 'souza@abc.com',
            LeadSource = 'Instagram Ads',
            CanalAtendimento__c = 'Fale conosco',
            MobilePhone = '11987654322',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id,
            EmailAdicional__c = 'souza_additional@abc.com',
            CelularAdicional__c = '11987654323',
            CelularAdicional1__c = '11987654324',
            CelularAdicional2__c = '11987654325',
            CelularComercialAdicional__c = '11987654326',
            Phone = '11987654326'
        );
        insert lead2;

        // Testar o método com parâmetros para Lead de pessoa física
        List<Lead> leadsPF = LeadSelector.obterLeadsPorInformacoesConcierge('11987654321', 'silva@xyz.com', false, null);
       }
    
  
}