force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ObjectHelperTest.cls
@isTest
private class ObjectHelperTest {
    
    @TestSetup
    static void makeData(){
        doMakeData();
    }

    private static void doMakeData(){
        Empreendimento__c empreendimento = new Empreendimento__c();
        empreendimento.Name = 'Empreendimento de Teste';
        empreendimento.CNPJEmpreendimento__c = '22416340000130';
        insert empreendimento;

        

        insert new Lead(
                LastName = 'Zika',
                Company = 'Chave',
                Status = 'Novo',
                Email = 't@g.com',
                CanalAtendimento__c = 'Loja',
                EmpreendimentoInteresse__c = empreendimento.Id
            );
    }

    @isTest
    private static void getLookUpId(){
        Empreendimento__c empreendimento = [SELECT Id FROM Empreendimento__c LIMIT 1].get(0);
        List<Lead> leads = [SELECT Id, EmpreendimentoInteresse__c FROM Lead];

        Set<Id> empreendimentosId = new Set<Id>();

        Test.startTest();

        empreendimentosId = ObjectHelper.getLookUpId(leads, 'EmpreendimentoInteresse__c');

        Test.stopTest();

        Assert.isTrue(empreendimentosId.contains(empreendimento.Id));
    }
}