force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadDomainTest.cls
@isTest
public class LeadDomainTest {
    @isTest
    static void testObterLeadPorId() {
        // Criação de um Empreendimento de teste
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Teste Empreendimento',
            CNPJEmpreendimento__c = '12345678000195'
        );
        insert empreendimento;

        // Criação de um Lead de teste associado ao Empreendimento
        Lead testLead = new Lead(
            LastName = 'Elera Lima',
            Company = 'Empresa XYZ',
            Email = 'eleraLima@gmail.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Telefone',
            MobilePhone = '11987647487',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id
        );
        insert testLead;

        // Chamar o método obterLeadPorId
        Lead resultLead = LeadDomain.obterLeadPorId(testLead.Id);
    }

    @isTest
    static void testObterLeadsPorCanalAtendimento() {
        // Criação de um Empreendimento de teste
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Teste Empreendimento',
            CNPJEmpreendimento__c = '12345678000195'
        );
        insert empreendimento;

        // Criação de alguns Leads de teste associados ao Empreendimento
        Lead lead1 = new Lead(
            LastName = 'Teste1',
            Company = 'Empresa XYZ',
            Email = 'teste1@empresa.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Telefone',
            MobilePhone = '11987600001',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id
        );

        Lead lead2 = new Lead(
            LastName = 'Teste2',
            Company = 'Empresa XYZ',
            Email = 'teste2@empresa.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Telefone',
            MobilePhone = '11987600002',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id
        );

        Lead lead3 = new Lead(
            LastName = 'Teste3',
            Company = 'Empresa XYZ',
            Email = 'teste3@empresa.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Telefone',
            MobilePhone = '11987600003',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id
        );
        insert new List<Lead>{lead1, lead2, lead3};

        // Chamar o método obterLeadsPorCanalAtendimento
        Map<String, List<Lead>> leadsPorCanal = LeadDomain.obterLeadsPorCanalAtendimento(new List<Lead>{lead1, lead2, lead3});
    }
}