force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da unidade</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Disponivel</fullName>
            </value>
            <value>
                <fullName>&lt;&lt;LISTAR STATUS&gt;&gt;</fullName>
                <isActive>false</isActive>
                <label>&lt;&lt;LISTAR STATUS&gt;&gt;</label>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
                <isActive>false</isActive>
                <label>Contrato Assinado</label>
            </value>
            <value>
                <fullName>Contrato Emitido</fullName>
                <isActive>false</isActive>
                <label>Contrato Emitido</label>
            </value>
            <value>
                <fullName>Negociação</fullName>
                <isActive>false</isActive>
                <label>Negociação</label>
            </value>
            <value>
                <fullName>Permuta</fullName>
                <isActive>false</isActive>
                <label>Permuta</label>
            </value>
            <value>
                <fullName>Reserva condicional</fullName>
                <isActive>false</isActive>
                <label>Reserva condicional</label>
            </value>
            <value>
                <fullName>SD Fora de Venda</fullName>
                <isActive>false</isActive>
                <label>SD Fora de Venda</label>
            </value>
            <value>
                <fullName>Venda Integrada</fullName>
                <isActive>false</isActive>
                <label>Venda Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcela__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcela__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcelaPos__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcelaPos__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela POS</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Publicada</fullName>
            </value>
            <value>
                <fullName>Desativada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SimuladorVendasControllerTest.cls
@isTest
public class SimuladorVendasControllerTest {
    
    @TestSetup
    static void makeData(){
        // Criar e inserir um Empreendimento
        Empreendimento__c empreendimento = new Empreendimento__c();
        empreendimento.Name = 'Empreendimento de Teste';
        empreendimento.CNPJEmpreendimento__c = '22151181000190';
        insert empreendimento;

        // Criar e inserir um Produto
        Product2 produto = new Product2();
        produto.Name = 'Produto de Teste';
        produto.ProductCode = 'Teste-1';
        produto.isActive = true;
        produto.NumeroDaUnidade__c = 777;
        produto.Status__c = 'Disponivel';
        insert produto;

        // Criar e inserir uma PricebookEntry
        PricebookEntry entradaPreco = new PricebookEntry();
        entradaPreco.Pricebook2Id = Test.getStandardPricebookId();
        entradaPreco.Product2Id = produto.Id;
        entradaPreco.UseStandardPrice = false;
        entradaPreco.UnitPrice = 100;
        entradaPreco.IsActive = true;
        insert entradaPreco;

        // Criar e inserir uma TabelaVendas associada ao Empreendimento
        TabelaVendas__c tabela = new TabelaVendas__c();
        tabela.Name = 'Teste';
        tabela.PeriodicidadeParcelaPos__c = 1;
        tabela.PeriodicidadeParcela__c = 1;
        tabela.Empreendimento__c = empreendimento.Id;
        insert tabela;
    }

    @isTest
    public static void testBuscarProdutoPorId(){

        Product2 produto = [SELECT Id FROM Product2 LIMIT 1];

        Test.startTest();
        Product2 produtoBuscado = SimuladorVendasController.buscarProdutoPorId(produto.id);
        Test.stopTest();

        Assert.areEqual(produto.Id, produtoBuscado.Id, 'Os Ids devem ser os mesmos');
    }

    @isTest
    public static void testBuscarEntradaTabelaPrecoPorIdDeProduto(){

        Product2 produto = [SELECT Id FROM Product2 LIMIT 1];
       
        Test.startTest();
        PricebookEntry entrada = SimuladorVendasController.buscarEntradaTabelaPrecoPorIdDeProduto(produto.Id);
        Test.stopTest();

        Assert.areEqual(100, entrada.UnitPrice, 'Os valores devem ser iguais');
    }

    @isTest
    public static void testObterTabelasPorIdEmpreendimento(){
        Empreendimento__c  empreendimento = [SELECT Id FROM Empreendimento__c LIMIT 1];

        Test.startTest();
        List<TabelaVendas__c> tabelas = SimuladorVendasController.obterTabelasPorIdEmpreendimento(empreendimento.Id);
        Test.stopTest();

        Assert.areEqual(1, tabelas.size(), 'A lista de tabelas deve ter 1 item');
    }

}