force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

you/force-app/main/default/objects/Empreendimento__c/fields/Acabamento__c.field-meta.xml
<CustomField>
    <fullName>Acabamento__c</fullName>
    <description>Porcentagem de conclusão do Acabamento</description>
    <label>Acabamento</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/Alvenaria__c.field-meta.xml
<CustomField>
    <fullName>Alvenaria__c</fullName>
    <description>Porcentagem de conclusão da Alvenaria</description>
    <label>Alvenaria</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/AreaExterna__c.field-meta.xml
<CustomField>
    <fullName>AreaExterna__c</fullName>
    <description>Porcentagem de conclusão da Área Externa</description>
    <label>Área Externa</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <description>Bairro do Empreendimento</description>
    <label>Bairro</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Complemento__c.field-meta.xml
<CustomField>
    <fullName>Complemento__c</fullName>
    <label>Complemento</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/DataEntregaChaves__c.field-meta.xml
<CustomField>
    <fullName>DataEntregaChaves__c</fullName>
    <description>Data da entrega das chaves
 do empreendimento</description>
    <label>Data da Entrega das Chaves</label>
    <type>Date</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/DataHabitase__c.field-meta.xml
<CustomField>
    <fullName>DataHabitase__c</fullName>
    <description>Data do Habite-se do empreendimento</description>
    <label>Data do Habita-se</label>
    <type>Date</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/DiasDeVencimentoDaParcela__c.field-meta.xml
<CustomField>
    <fullName>DiasDeVencimentoDaParcela__c</fullName>
    <description>Dias de vencimento para series de pagamento</description>
    <label>Dias de vencimento da parcela</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/Estrutura__c.field-meta.xml
<CustomField>
    <fullName>Estrutura__c</fullName>
    <description>Porcentagem de conclusão da Estrutura</description>
    <label>Estrutura</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/EvolucaoObra__c.field-meta.xml
<CustomField>
    <fullName>EvolucaoObra__c</fullName>
    <label>Evolução da obra</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/Fundacao__c.field-meta.xml
<CustomField>
    <fullName>Fundacao__c</fullName>
    <description>Porcentagem de conclusão da Fundação</description>
    <label>Fundação</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/Instalacoes__c.field-meta.xml
<CustomField>
    <fullName>Instalacoes__c</fullName>
    <description>Porcentagem de conclusão das Instalações</description>
    <label>Instalações</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <description>CidadeEstado/Pais do Empreendimento</description>
    <label>Logradouro</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <description>Número de Endereço do Empreendiment</description>
    <label>Número</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/OpcoesLazerDisponiveis__c.field-meta.xml
<CustomField>
    <fullName>OpcoesLazerDisponiveis__c</fullName>
    <description>Opções de lazer disponíveis</description>
    <label>Opções de Lazer Disponíveis</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academia</fullName>
            </value>
            <value>
                <fullName>Ar-condicionado nas áreas de lazer</fullName>
            </value>
            <value>
                <fullName>Ar-condicionado nas áreas internas de lazer</fullName>
            </value>
            <value>
                <fullName>Área para jogos</fullName>
            </value>
            <value>
                <fullName>Áreas comuns entregues equipadas e decoradas</fullName>
            </value>
            <value>
                <fullName>Áreas técnicas</fullName>
            </value>
            <value>
                <fullName>Áreas verdes de acesso exclusivo aos condomínios</fullName>
            </value>
            <value>
                <fullName>Arquibancada</fullName>
            </value>
            <value>
                <fullName>Arquibancada residencial</fullName>
            </value>
            <value>
                <fullName>Atelier</fullName>
            </value>
            <value>
                <fullName>Bar da piscina</fullName>
            </value>
            <value>
                <fullName>Bar lounge no rooftop</fullName>
            </value>
            <value>
                <fullName>Beauty care</fullName>
            </value>
            <value>
                <fullName>Bicicletário</fullName>
            </value>
            <value>
                <fullName>Bicicletario com bike lab</fullName>
            </value>
            <value>
                <fullName>Brinquedoteca</fullName>
            </value>
            <value>
                <fullName>Caixilhos com persiana de enrolar nos APTOS. de 1 Dorm.</fullName>
            </value>
            <value>
                <fullName>Churrasqueira</fullName>
            </value>
            <value>
                <fullName>Churrasqueira com Forno de Pizza</fullName>
            </value>
            <value>
                <fullName>Churrasqueira e piscina com deck molhado e solário</fullName>
            </value>
            <value>
                <fullName>Churrasqueira e spa com solário</fullName>
            </value>
            <value>
                <fullName>Churrasqueira Gourmet</fullName>
            </value>
            <value>
                <fullName>Cinema</fullName>
            </value>
            <value>
                <fullName>Cokitchen</fullName>
            </value>
            <value>
                <fullName>Comércio térreo</fullName>
            </value>
            <value>
                <fullName>Contrapiso com tratamento acústico nas unidades</fullName>
            </value>
            <value>
                <fullName>Coworking</fullName>
            </value>
            <value>
                <fullName>Coworking / Gourmet</fullName>
            </value>
            <value>
                <fullName>Coworking integrado com jogos e café</fullName>
            </value>
            <value>
                <fullName>Coworking no rooftop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/StatusObra__c.field-meta.xml
<CustomField>
    <fullName>StatusObra__c</fullName>
    <description>Status da obra do empreendimento</description>
    <label>Status da Obra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em construção</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Lançamento</fullName>
            </value>
            <value>
                <fullName>Pré-Lançamento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/TipoEmpreendimento__c.field-meta.xml
<CustomField>
    <fullName>TipoEmpreendimento__c</fullName>
    <label>Tipo de Empreendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Lote</fullName>
            </value>
            <value>
                <fullName>Residencial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/Empreendimento__c/fields/ValorM__c.field-meta.xml
<CustomField>
    <fullName>ValorM__c</fullName>
    <description>Valor do metro quadrado do empreendimento.</description>
    <label>Valor (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EmpreendimentoSelector.cls
public with sharing class EmpreendimentoSelector {
    public static Empreendimento__c getEmpreendimentoById(String id) {
        return [SELECT CNPJEmpreendimento__c, DataEntregaChaves__c, DataHabitase__c, StatusObra__c, CEP__c, Logradouro__c,
                   Bairro__c, Numero__c, Complemento__c, Cidade__c, UF__c, Fundacao__c, Estrutura__c, Alvenaria__c,
                   Acabamento__c, AreaExterna__c, EvolucaoObra__c, Instalacoes__c, TipoEmpreendimento__c,
                   DiasDeVencimentoDaParcela__c, ValorM__c, MetragemPrivativaTotal__c, MetragemTerreno__c,
                   MetragemConstruIdaM__c, OpcoesLazerDisponiveis__c, FracaoIdealTotal__c, Name
            FROM Empreendimento__c WHERE Id = :id
        ];
    }
}