force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Lead Perdido</fullName>
                <label>Lead Perdido(não trabalho)</label>
            </value>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Nutrindo</fullName>
            </value>
            <value>
                <fullName>Tentativa de contato</fullName>
            </value>
            <value>
                <fullName>Contato Realizado</fullName>
            </value>
            <value>
                <fullName>Agendamento de Visita</fullName>
            </value>
            <value>
                <fullName>Qualificação</fullName>
            </value>
            <value>
                <fullName>Convertido</fullName>
                <label>Conversão</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FaseParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FaseParaRedirecionamentoDoLead__c</fullName>
    <label>Fase para redirecionamento do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Nutrindo</fullName>
            </value>
            <value>
                <fullName>Tentativa de contato</fullName>
            </value>
            <value>
                <fullName>Contato Realizado</fullName>
            </value>
            <value>
                <fullName>Agendamento de Visita</fullName>
            </value>
            <value>
                <fullName>Qualificação</fullName>
            </value>
            <value>
                <fullName>Conversão</fullName>
            </value>
            <value>
                <fullName>Lead Perdido(não trabalho)</fullName>
            </value>
            <value>
                <fullName>Convertido</fullName>
                <isActive>false</isActive>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lead Perdido</fullName>
                <isActive>false</isActive>
                <label>Lead Perdido</label>
            </value>
            <value>
                <fullName>Não Qualificado</fullName>
                <isActive>false</isActive>
                <label>Não Qualificado</label>
            </value>
            <value>
                <fullName>Prospecção</fullName>
                <isActive>false</isActive>
                <label>Prospecção</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ConfiguracaoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>ConfiguracaoDeSLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuração de SLA</label>
    <referenceTo>ConfiguracoesDeNegocio__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DataHoraVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataHoraVencimento__c</fullName>
    <label>Tempo limite para perda</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ApplyVersion.cls
global class ApplyVersion implements Schedulable {
    public DateTime limitDate;

    
    public ApplyVersion(Datetime limitDate){
        this.limitDate = limitDate;
    }

    global void execute(SchedulableContext SC) {
     
        List<Lead> leadsToUpdate = [SELECT Id,
                                   Status,
                                   DataHoraVencimento__c,
                                   ConfiguracaoDeSLA__c,
                                   ConfiguracaoDeSLA__r.FaseParaRedirecionamentoDoLead__c,
                                   ConfiguracaoDeSLA__r.Fase__c,
                                   ConfiguracaoDeSLA__r.FilaParaRedirecionamentoDoLead__c
                                FROM Lead
                                WHERE DataHoraVencimento__c <: this.limitDate];

        
        List<Lead> leadsToUpdateList = new List<Lead>();

        for (Lead ld : leadsToUpdate) {
            if (ld.Status.equalsIgnoreCase(ld.ConfiguracaoDeSLA__r.Fase__c) && ld.DataHoraVencimento__c < DateTime.now()) {
                List<Group> grupos = [SELECT Id FROM Group WHERE Name =: ld.ConfiguracaoDeSLA__r.FilaParaRedirecionamentoDoLead__c];
                if (!grupos.isEmpty()) {
                    ld.OwnerId = grupos[0].Id; 
                    ld.Status = ld.ConfiguracaoDeSLA__r.FaseParaRedirecionamentoDoLead__c;
                    leadsToUpdateList.add(ld); 
                } else {
                    System.debug('Nenhum grupo encontrado com o nome: ' + ld.ConfiguracaoDeSLA__r.FilaParaRedirecionamentoDoLead__c);
                }
            }
        }

        
        if (!leadsToUpdateList.isEmpty()) {
            TriggerHandler.bypass('LeadTriggerHandler');
            update leadsToUpdateList;
            TriggerHandler.clearBypass('LeadTriggerHandler');
        }

      
         scheduleNextJob();
    }

   private void scheduleNextJob() {
    
    DateTime newDate = Datetime.now().addMinutes(5);

    
    List<CronTrigger> existingJobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'ApplyVersionJob'];

    
    if (!existingJobs.isEmpty()) {
        for (CronTrigger job : existingJobs) {
            System.abortJob(job.Id);
        }
    }

    // Ajuste para garantir que os valores de hora e minuto sejam válidos
    Integer second = newDate.second();
    Integer minute = newDate.minute();
    Integer hour = newDate.hour();

    // Constrói a expressão cron para agendar o job
    String cron = '0 ' + minute + ' ' + hour + ' * * ?';
    
    // Agenda um novo job com a nova expressão cron
    System.schedule('ApplyVersionJob', cron, new ApplyVersion(newDate));
}
}