force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Lead Perdido</fullName>
                <label>Lead Perdido(não trabalho)</label>
            </value>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Nutrindo</fullName>
            </value>
            <value>
                <fullName>Tentativa de contato</fullName>
            </value>
            <value>
                <fullName>Contato Realizado</fullName>
            </value>
            <value>
                <fullName>Agendamento de Visita</fullName>
            </value>
            <value>
                <fullName>Qualificação</fullName>
            </value>
            <value>
                <fullName>Convertido</fullName>
                <label>Conversão</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FaseParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FaseParaRedirecionamentoDoLead__c</fullName>
    <label>Fase para redirecionamento do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Nutrindo</fullName>
            </value>
            <value>
                <fullName>Tentativa de contato</fullName>
            </value>
            <value>
                <fullName>Contato Realizado</fullName>
            </value>
            <value>
                <fullName>Agendamento de Visita</fullName>
            </value>
            <value>
                <fullName>Qualificação</fullName>
            </value>
            <value>
                <fullName>Conversão</fullName>
            </value>
            <value>
                <fullName>Lead Perdido(não trabalho)</fullName>
            </value>
            <value>
                <fullName>Convertido</fullName>
                <isActive>false</isActive>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lead Perdido</fullName>
                <isActive>false</isActive>
                <label>Lead Perdido</label>
            </value>
            <value>
                <fullName>Não Qualificado</fullName>
                <isActive>false</isActive>
                <label>Não Qualificado</label>
            </value>
            <value>
                <fullName>Prospecção</fullName>
                <isActive>false</isActive>
                <label>Prospecção</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ConfiguracaoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>ConfiguracaoDeSLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuração de SLA</label>
    <referenceTo>ConfiguracoesDeNegocio__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DataHoraVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataHoraVencimento__c</fullName>
    <label>Tempo limite para perda</label>
    <type>DateTime</type>
</CustomField>

you/force-app/main/default/classes/ApplyVersionTest.cls
@isTest
private class ApplyVersionTest {
    @isTest
    static void testScheduleNewJob() {
        TriggerHandler.bypass('LeadTriggerHandler');
        ConfiguracoesDeNegocio__c config = new ConfiguracoesDeNegocio__c();
        config.FaseParaRedirecionamentoDoLead__c = 'Descartado';
        config.Fase__c = 'Novo';
        config.FilaParaRedirecionamentoDoLead__c = 'Fila Perda Lead 2';
        insert config;

        Group gp =  new Group();
        gp.Name = 'Fila Perda Lead 2';
        insert gp;

        Lead lead = new Lead(
            LastName = 'Raposo',
            Company = 'porao',
            Status = 'Novo',
            ConfiguracaoDeSLA__c = config.Id,
            CanalAtendimento__c = 'Whatsapp',
            Email = 'e@gmail.com',
            DataHoraVencimento__c = DateTime.Now()
        );
        insert lead;

        DateTime limitDate = DateTime.now().addMinutes(30);
        ApplyVersion applyVersion = new ApplyVersion(limitDate);

        Test.startTest();
        String sch = '0 0 0 1 1 ? 2025'; // Schedule for a specific date
        System.schedule('Test ApplyVersion Job', sch, applyVersion);
        Test.stopTest();

        // Verify the job is scheduled
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered FROM CronTrigger WHERE CronJobDetail.Name = 'Test ApplyVersion Job'];
        System.assertNotEquals(null, ct);
        System.assertEquals(0, ct.TimesTriggered);
    }
}