force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/TempoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>TempoDeSLA__c</fullName>
    <inlineHelpText>Define a qualidade esperada de um serviço,
tempo estabelecido em minutos.</inlineHelpText>
    <label>Tempo de SLA</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Verifique se o CNPJ está no formato correto: de 14 dígitos corridos</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskTriggerTest.cls
@IsTest
public class TaskTriggerTest {

    @TestSetup
    static void setup() {
        // Criação do Empreendimento
        Empreendimento__c empreendimento = new Empreendimento__c(Name = 'Teste empreendimento', CNPJEmpreendimento__c = '07135796000139');
        insert empreendimento;

        // Criação da Configuração de Negócio
        ConfiguracoesDeNegocio__c conf = new ConfiguracoesDeNegocio__c(name = 'teste', TempoDeSLA__c = 10);
        insert conf;

        // Criação do Lead associado ao empreendimento
        Lead lead = new Lead(
            LastName = 'Paulo',
            Company = 'Elera',
            Email = 'pauloelera123@gmail.com',
            LeadSource = 'Telefone',
            CanalAtendimento__c = 'Chat',
            MobilePhone = '11960387699',
            Status = 'Novo',
            cpf__c = '50154031003',
            cnpj__c = '28724715000106',
            EmpreendimentoInteresse__c = empreendimento.Id
        );
        insert lead;

        // Atualização de status do lead
        lead.Status = 'Tentativa de contato';
        update lead;

        // Criação da Task
        Task task = new Task(
            WhoId = lead.Id,
            Subject = 'Chamada',
            Status = 'Not Started',
            ActivityDate = Date.today().addDays(4)
        );
        insert task;
    }

    @IsTest
    static void testBeforeInsert() {
        // Configuração de teste
        Lead lead = [SELECT Id FROM Lead LIMIT 1];
        Task task = new Task(
            WhoId = lead.Id,
            Subject = 'Email',
            Status = 'Not Started',
            ActivityDate = Date.today().addDays(2)
        );

        Test.startTest();
        insert task;
        Test.stopTest();

        // Verificação se a Task foi inserida corretamente
        Task insertedTask = [SELECT Id, ActivityDate FROM Task WHERE Id = :task.Id];
        System.assertEquals(Date.today().addDays(2), insertedTask.ActivityDate);
    }

    @IsTest
    static void testBeforeUpdate() {
        Task task = [SELECT Id, ActivityDate FROM Task LIMIT 1];
        task.ActivityDate = Date.today().addDays(5);

        Test.startTest();
        update task;
        Test.stopTest();

        // Verificação se a Task foi atualizada corretamente
        Task updatedTask = [SELECT Id, ActivityDate FROM Task WHERE Id = :task.Id];
        System.assertEquals(Date.today().addDays(5), updatedTask.ActivityDate);
    }

    @IsTest
    static void testAfterUpdate() {
        Task task = [SELECT Id, WhoId, Status FROM Task LIMIT 1];
        task.Status = 'Completed';

        Test.startTest();
        update task;
        Test.stopTest();

    }

    @IsTest
    static void testBeforeDelete() {
        Task task = [SELECT Id FROM Task LIMIT 1];

        Test.startTest();
        delete task;
        Test.stopTest();

        // Verificação se a Task foi deletada corretamente
        Integer count = [SELECT COUNT() FROM Task WHERE Id = :task.Id];
        System.assertEquals(0, count);
    }

    @IsTest
    static void testAfterInsert() {
        // Configuração de teste
        Lead lead = [SELECT Id FROM Lead LIMIT 1];
        Task task = new Task(
            WhoId = lead.Id,
            Subject = 'Reunião',
            Status = 'Not Started',
            ActivityDate = Date.today().addDays(3)
        );

        Test.startTest();
        insert task;
        Test.stopTest();

        // Verificação se a Task foi inserida corretamente
        Task insertedTask = [SELECT Id, ActivityDate FROM Task WHERE Id = :task.Id];
        System.assertEquals(Date.today().addDays(3), insertedTask.ActivityDate);
    }

    @IsTest
    static void testAfterDelete() {
        // Configuração de teste
        Task task = new Task(
            WhoId = [SELECT Id FROM Lead LIMIT 1].Id,
            Subject = 'Reunião',
            Status = 'Not Started',
            ActivityDate = Date.today().addDays(3)
        );
        insert task;

        Test.startTest();
        delete task;
        Test.stopTest();

        // Verificação se a Task foi deletada corretamente
        Integer count = [SELECT COUNT() FROM Task WHERE Id = :task.Id];
        System.assertEquals(0, count);
    }
}