force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Lead Perdido</fullName>
                <label>Lead Perdido(não trabalho)</label>
            </value>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Nutrindo</fullName>
            </value>
            <value>
                <fullName>Tentativa de contato</fullName>
            </value>
            <value>
                <fullName>Contato Realizado</fullName>
            </value>
            <value>
                <fullName>Agendamento de Visita</fullName>
            </value>
            <value>
                <fullName>Qualificação</fullName>
            </value>
            <value>
                <fullName>Convertido</fullName>
                <label>Conversão</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FaseParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FaseParaRedirecionamentoDoLead__c</fullName>
    <label>Fase para redirecionamento do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Descartado</fullName>
            </value>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Nutrindo</fullName>
            </value>
            <value>
                <fullName>Tentativa de contato</fullName>
            </value>
            <value>
                <fullName>Contato Realizado</fullName>
            </value>
            <value>
                <fullName>Agendamento de Visita</fullName>
            </value>
            <value>
                <fullName>Qualificação</fullName>
            </value>
            <value>
                <fullName>Conversão</fullName>
            </value>
            <value>
                <fullName>Lead Perdido(não trabalho)</fullName>
            </value>
            <value>
                <fullName>Convertido</fullName>
                <isActive>false</isActive>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lead Perdido</fullName>
                <isActive>false</isActive>
                <label>Lead Perdido</label>
            </value>
            <value>
                <fullName>Não Qualificado</fullName>
                <isActive>false</isActive>
                <label>Não Qualificado</label>
            </value>
            <value>
                <fullName>Prospecção</fullName>
                <isActive>false</isActive>
                <label>Prospecção</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ConfiguracaoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>ConfiguracaoDeSLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuração de SLA</label>
    <referenceTo>ConfiguracoesDeNegocio__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DataHoraVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataHoraVencimento__c</fullName>
    <label>Tempo limite para perda</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ApplyVersionTest.cls
@isTest
private class ApplyVersionTest {
    @testSetup
    static void setupData() {
        // Ignorar o gatilho LeadTrigger
        TriggerHandler.bypass('LeadTriggerHandler');
        
        // Configurações de SLA
        ConfiguracoesDeNegocio__c config = new ConfiguracoesDeNegocio__c(
            FaseParaRedirecionamentoDoLead__c = 'Descartado',
            Fase__c = 'Novo',
            FilaParaRedirecionamentoDoLead__c = 'Fila Perda Lead' // Usando o nome da fila existente
        );
        insert config;

        // Recuperar a fila "Fila Perda Lead"
        Group filaPerdaLead = [SELECT Id FROM Group WHERE Name = 'Fila Perda Lead' LIMIT 1];
        
        // Recuperar a fila "Roteamento Lead"
        Group roteamentoLead = [SELECT Id FROM Group WHERE Name = 'Roteamento Lead' LIMIT 1];

        // Lead expirado (para ser atualizado)
        Lead lead1 = new Lead(
            LastName = 'Raposo',
            Company = 'Test Company',
            Status = 'Novo',
            ConfiguracaoDeSLA__c = config.Id,
            CanalAtendimento__c = 'Whatsapp',
            Email = 'lead1@example.com',
            DataHoraVencimento__c = DateTime.now().addMinutes(-10) // Lead expirado
        );
        insert lead1;

        // Limpar o bypass após a inserção
        TriggerHandler.clearBypass('LeadTriggerHandler');
    }

    @isTest
    static void testExecute() {
        // Definir a data limite para o job
        DateTime limitDate = DateTime.now();

        // Criar a instância do job ApplyVersion
        ApplyVersion applyVersion = new ApplyVersion(limitDate);

        // Iniciar teste
        Test.startTest();

        // Executar o job manualmente
        applyVersion.execute(null);

        // Parar o teste
        Test.stopTest();

        // Verificar se o lead expirado foi atualizado
        Lead updatedLead = [SELECT Id, Status, OwnerId FROM Lead WHERE Email = 'lead1@example.com'];
        Group queue = [SELECT Id FROM Group WHERE Name = 'Fila Perda Lead' LIMIT 1];

        // Verificar se o proprietário do Lead foi alterado para a fila "Fila Perda Lead"
        System.assertEquals(queue.Id, updatedLead.OwnerId, 'O lead deveria ser redirecionado para a fila "Fila Perda Lead".');

        // Verificar se um novo job foi agendado
        List<CronTrigger> scheduledJobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'ApplyVersionJob'];
       
    }
}