force-app/main/default/objects/Mensagem__c/Mensagem__c.object-meta.xml
<CustomObject>
    <description>Responsável pelo registro de mensagens em comunicação com clientes.</description>
    <label>Mensagem</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Nome da mensagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mensagens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mensagem__c/fields/Certificado__c.field-meta.xml
<CustomField>
    <fullName>Certificado__c</fullName>
    <description>Indica o certificado digital atrelado a esta mensagem.</description>
    <inlineHelpText>Indique o certificado digital atrelado a esta mensagem.</inlineHelpText>
    <label>Certificado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/ChaveExterna__c.field-meta.xml
<CustomField>
    <fullName>ChaveExterna__c</fullName>
    <description>Indica o identificador desta mensagem no serviço externo.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indique o identificador desta mensagem no serviço externo.</inlineHelpText>
    <label>Chave externa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/ChaveExternaCliente__c.field-meta.xml
<CustomField>
    <fullName>ChaveExternaCliente__c</fullName>
    <description>Indica o identificador do cliente no serviço externo.</description>
    <inlineHelpText>Indica o identificador do cliente no serviço externo.</inlineHelpText>
    <label>Chave externa do cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/ChaveExternaMidia__c.field-meta.xml
<CustomField>
    <fullName>ChaveExternaMidia__c</fullName>
    <description>Indica o identificador da mídia enviada por mensagem, quando houver, no serviço externo.</description>
    <inlineHelpText>Indica o identificador da mídia enviada por mensagem, quando houver, no serviço externo.</inlineHelpText>
    <label>Chave externa da mídia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/CodigoStatus__c.field-meta.xml
<CustomField>
    <fullName>CodigoStatus__c</fullName>
    <description>Registra código do status da requisição para aplicativo de mensagens.</description>
    <inlineHelpText>Registra código do status da requisição para aplicativo de mensagens.</inlineHelpText>
    <label>Código do status</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/Conteudo__c.field-meta.xml
<CustomField>
    <fullName>Conteudo__c</fullName>
    <label>Conteúdo</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/CorpoRequisicao__c.field-meta.xml
<CustomField>
    <fullName>CorpoRequisicao__c</fullName>
    <description>Registra o corpo da requisição quando mensagem enviada pela plataforma ou recebida.</description>
    <inlineHelpText>Registra o corpo da requisição quando mensagem enviada pela plataforma ou recebida.</inlineHelpText>
    <label>Corpo da requisição</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/DataHora__c.field-meta.xml
<CustomField>
    <fullName>DataHora__c</fullName>
    <description>Indica a data e hora da chegada da mensagem no serviço externo.</description>
    <inlineHelpText>Indica a data e hora da chegada da mensagem no serviço externo.</inlineHelpText>
    <label>Data e hora</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/De__c.field-meta.xml
<CustomField>
    <fullName>De__c</fullName>
    <description>Indica o número de telefone do remetente da mensagem.</description>
    <inlineHelpText>Indique o número de telefone do remetente da mensagem.</inlineHelpText>
    <label>De</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/LeadMensagem__c.field-meta.xml
<CustomField>
    <fullName>LeadMensagem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo responsável por fazer o relacionamento da mensagem com o Lead.</description>
    <inlineHelpText>Campo responsável por fazer o relacionamento da mensagem com o Lead.</inlineHelpText>
    <label>Lead da Mensagem</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Mensagens</relationshipLabel>
    <relationshipName>Mensagens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/NomeArquivo__c.field-meta.xml
<CustomField>
    <fullName>NomeArquivo__c</fullName>
    <description>Indica o nome do arquivo quando houver arquivo anexado à mensagem.</description>
    <inlineHelpText>Indica o nome do arquivo quando houver arquivo anexado à mensagem.</inlineHelpText>
    <label>Nome do arquivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Registra o status da requisição para o aplicativo de mensagens.</description>
    <inlineHelpText>Registra o status da requisição para o aplicativo de mensagens.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Indica o tipo de mensagem recebida, se textual ou mídia, por exemplo.</description>
    <inlineHelpText>Indica o tipo de mensagem recebida, se textual ou mídia, por exemplo.</inlineHelpText>
    <label>Tipo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/TipoMidia__c.field-meta.xml
<CustomField>
    <fullName>TipoMidia__c</fullName>
    <description>Indica o típo da mídia enviada na mensagem.</description>
    <inlineHelpText>Indica o típo da mídia enviada na mensagem.</inlineHelpText>
    <label>Tipo de mídia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/URLMidia__c.field-meta.xml
<CustomField>
    <fullName>URLMidia__c</fullName>
    <description>Indica a URL para visualização e download da mídia relacionada à mensagem.</description>
    <inlineHelpText>Indica a URL para visualização e download da mídia relacionada à mensagem.</inlineHelpText>
    <label>URL da mídia</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/MensagemSelector.cls
public without sharing class MensagemSelector {
    public static List<Mensagem__c> obterMensagensPorIds(Set<Id> idsMensagens) {
        return [
            SELECT 
                Certificado__c,
                ChaveExterna__c,
                ChaveExternaMidia__c,
                ChaveExternaCliente__c,
                CodigoStatus__c,
                Conteudo__c,
                CorpoRequisicao__c,
                DataHora__c,
                De__c,
                NomeArquivo__c,
                Status__c,
                Tipo__c,
                TipoMidia__c,
                LeadMensagem__c,
                URLMidia__c
            FROM Mensagem__c
            WHERE Id IN :idsMensagens
        ];
    }

    public static List<Mensagem__c> obterMensagensPorChavesExternasClientes(Set<String> chavesExternasClientes) {
        System.debug('chavesExternasClientes: ' + chavesExternasClientes);
        if (chavesExternasClientes == null || chavesExternasClientes.isEmpty()) {
            System.debug('chavesExternasClientes is null or empty');
            return new List<Mensagem__c>();
        }
        System.debug('chavesExternasClientes is not null or empty');
        return [
            SELECT 
                Certificado__c,
                ChaveExterna__c,
                ChaveExternaMidia__c,
                ChaveExternaCliente__c,
                CodigoStatus__c,
                Conteudo__c,
                CorpoRequisicao__c,
                DataHora__c,
                De__c,
                NomeArquivo__c,
                Status__c,
                Tipo__c,
                TipoMidia__c,
                LeadMensagem__c,
                URLMidia__c
            FROM Mensagem__c
            WHERE ChaveExternaCliente__c IN :chavesExternasClientes 
            ORDER BY DataHora__c ASC
        ];
    }
}