force-app/main/default/objects/Mensagem__c/Mensagem__c.object-meta.xml
<CustomObject>
    <description>Responsável pelo registro de mensagens em comunicação com clientes.</description>
    <label>Mensagem</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Nome da mensagem</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mensagens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mensagem__c/fields/Certificado__c.field-meta.xml
<CustomField>
    <fullName>Certificado__c</fullName>
    <description>Indica o certificado digital atrelado a esta mensagem.</description>
    <inlineHelpText>Indique o certificado digital atrelado a esta mensagem.</inlineHelpText>
    <label>Certificado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/ChaveExterna__c.field-meta.xml
<CustomField>
    <fullName>ChaveExterna__c</fullName>
    <description>Indica o identificador desta mensagem no serviço externo.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indique o identificador desta mensagem no serviço externo.</inlineHelpText>
    <label>Chave externa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/ChaveExternaCliente__c.field-meta.xml
<CustomField>
    <fullName>ChaveExternaCliente__c</fullName>
    <description>Indica o identificador do cliente no serviço externo.</description>
    <inlineHelpText>Indica o identificador do cliente no serviço externo.</inlineHelpText>
    <label>Chave externa do cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/ChaveExternaMidia__c.field-meta.xml
<CustomField>
    <fullName>ChaveExternaMidia__c</fullName>
    <description>Indica o identificador da mídia enviada por mensagem, quando houver, no serviço externo.</description>
    <inlineHelpText>Indica o identificador da mídia enviada por mensagem, quando houver, no serviço externo.</inlineHelpText>
    <label>Chave externa da mídia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/CodigoStatus__c.field-meta.xml
<CustomField>
    <fullName>CodigoStatus__c</fullName>
    <description>Registra código do status da requisição para aplicativo de mensagens.</description>
    <inlineHelpText>Registra código do status da requisição para aplicativo de mensagens.</inlineHelpText>
    <label>Código do status</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/Conteudo__c.field-meta.xml
<CustomField>
    <fullName>Conteudo__c</fullName>
    <label>Conteúdo</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/CorpoRequisicao__c.field-meta.xml
<CustomField>
    <fullName>CorpoRequisicao__c</fullName>
    <description>Registra o corpo da requisição quando mensagem enviada pela plataforma ou recebida.</description>
    <inlineHelpText>Registra o corpo da requisição quando mensagem enviada pela plataforma ou recebida.</inlineHelpText>
    <label>Corpo da requisição</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/DataHora__c.field-meta.xml
<CustomField>
    <fullName>DataHora__c</fullName>
    <description>Indica a data e hora da chegada da mensagem no serviço externo.</description>
    <inlineHelpText>Indica a data e hora da chegada da mensagem no serviço externo.</inlineHelpText>
    <label>Data e hora</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/De__c.field-meta.xml
<CustomField>
    <fullName>De__c</fullName>
    <description>Indica o número de telefone do remetente da mensagem.</description>
    <inlineHelpText>Indique o número de telefone do remetente da mensagem.</inlineHelpText>
    <label>De</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/NomeArquivo__c.field-meta.xml
<CustomField>
    <fullName>NomeArquivo__c</fullName>
    <description>Indica o nome do arquivo quando houver arquivo anexado à mensagem.</description>
    <inlineHelpText>Indica o nome do arquivo quando houver arquivo anexado à mensagem.</inlineHelpText>
    <label>Nome do arquivo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Registra o status da requisição para o aplicativo de mensagens.</description>
    <inlineHelpText>Registra o status da requisição para o aplicativo de mensagens.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Indica o tipo de mensagem recebida, se textual ou mídia, por exemplo.</description>
    <inlineHelpText>Indica o tipo de mensagem recebida, se textual ou mídia, por exemplo.</inlineHelpText>
    <label>Tipo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/TipoMidia__c.field-meta.xml
<CustomField>
    <fullName>TipoMidia__c</fullName>
    <description>Indica o típo da mídia enviada na mensagem.</description>
    <inlineHelpText>Indica o típo da mídia enviada na mensagem.</inlineHelpText>
    <label>Tipo de mídia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensagem__c/fields/URLMidia__c.field-meta.xml
<CustomField>
    <fullName>URLMidia__c</fullName>
    <description>Indica a URL para visualização e download da mídia relacionada à mensagem.</description>
    <inlineHelpText>Indica a URL para visualização e download da mídia relacionada à mensagem.</inlineHelpText>
    <label>URL da mídia</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/MensagemSelectorTest.cls
@isTest
public class MensagemSelectorTest {
    @isTest
    static void obterMensagensPorIdsTest() {
        Mensagem__c mensagem1 = new Mensagem__c(
            ChaveExterna__c = '5444775455221225',
            Certificado__c = 'Certificado1',
            ChaveExternaMidia__c = 'Midia1',
            ChaveExternaCliente__c = 'Cliente1',
            CodigoStatus__c = 1,
            Conteudo__c = 'Conteudo1',
            CorpoRequisicao__c = 'Corpo1',
            DataHora__c = DateTime.now(),
            De__c = '1234567890',
            NomeArquivo__c = 'Arquivo1.txt',
            Status__c = 'Ativo',
            Tipo__c = 'Tipo1',
            TipoMidia__c = 'TipoMidia1',
            URLMidia__c = 'http://example.com/media1'
        );

        Mensagem__c mensagem2 = new Mensagem__c(
            ChaveExterna__c = '5444775455221226',
            Certificado__c = 'Certificado2',
            ChaveExternaMidia__c = 'Midia2',
            ChaveExternaCliente__c = 'Cliente2',
            CodigoStatus__c = 2,
            Conteudo__c = 'Conteudo2',
            CorpoRequisicao__c = 'Corpo2',
            DataHora__c = DateTime.now().addDays(-1),
            De__c = '0987654321',
            NomeArquivo__c = 'Arquivo2.txt',
            Status__c = 'Inativo',
            Tipo__c = 'Tipo2',
            TipoMidia__c = 'TipoMidia2',
            URLMidia__c = 'http://example.com/media2'
        );

        insert new List<Mensagem__c> { mensagem1, mensagem2 };

        Set<Id> idsMensagens = new Set<Id>{ mensagem1.Id, mensagem2.Id };
        List<Mensagem__c> mensagens = MensagemSelector.obterMensagensPorIds(idsMensagens);

        Mensagem__c mensagemRetornada1 = mensagens[0];
        System.assertEquals('Certificado1', mensagemRetornada1.Certificado__c);
        System.assertEquals('Cliente1', mensagemRetornada1.ChaveExternaCliente__c);

        Mensagem__c mensagemRetornada2 = mensagens[1];
        System.assertEquals('Certificado2', mensagemRetornada2.Certificado__c);
        System.assertEquals('Cliente2', mensagemRetornada2.ChaveExternaCliente__c);
    }

    @isTest
    static void obterMensagensPorChavesExternasClientesTest() {
        Mensagem__c mensagem1 = new Mensagem__c(
            ChaveExterna__c = '5444775455221225',
            Certificado__c = 'Certificado1',
            ChaveExternaMidia__c = 'Midia1',
            ChaveExternaCliente__c = 'Cliente1',
            CodigoStatus__c = 1,
            Conteudo__c = 'Conteudo1',
            CorpoRequisicao__c = 'Corpo1',
            DataHora__c = DateTime.now(),
            De__c = '1234567890',
            NomeArquivo__c = 'Arquivo1.txt',
            Status__c = 'Ativo',
            Tipo__c = 'Tipo1',
            TipoMidia__c = 'TipoMidia1',
            URLMidia__c = 'http://example.com/media1'
        );

        Mensagem__c mensagem2 = new Mensagem__c(
            ChaveExterna__c = '5444775455221227',
            Certificado__c = 'Certificado3',
            ChaveExternaMidia__c = 'Midia3',
            ChaveExternaCliente__c = 'Cliente1',
            CodigoStatus__c = 2,
            Conteudo__c = 'Conteudo3',
            CorpoRequisicao__c = 'Corpo3',
            DataHora__c = DateTime.now().addDays(-1),
            De__c = '1122334455',
            NomeArquivo__c = 'Arquivo3.txt',
            Status__c = 'Inativo',
            Tipo__c = 'Tipo3',
            TipoMidia__c = 'TipoMidia3',
            URLMidia__c = 'http://example.com/media3'
        );

        insert new List<Mensagem__c> { mensagem1, mensagem2 };

        Set<String> chavesExternasClientes = new Set<String>{ 'Cliente1' };
        List<Mensagem__c> mensagensCliente = MensagemSelector.obterMensagensPorChavesExternasClientes(chavesExternasClientes);

        System.assert(mensagensCliente[0].DataHora__c <= mensagensCliente[1].DataHora__c, 'Mensagens devem estar em ordem crescente de DataHora');
    }
}