force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ChaveExternaWhatsApp__c.field-meta.xml
<CustomField>
    <fullName>ChaveExternaWhatsApp__c</fullName>
    <description>Identificador deste lead no WhatsApp.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indique o identificador deste lead no WhatsApp.</inlineHelpText>
    <label>Chave externa (WhatsApp)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ConfiguracaoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>ConfiguracaoDeSLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuração de SLA</label>
    <referenceTo>ConfiguracoesDeNegocio__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CorretorContato__c.field-meta.xml
<CustomField>
    <fullName>CorretorContato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor (Contato)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaOriginal__c.field-meta.xml
<CustomField>
    <fullName>MidiaOriginal__c</fullName>
    <label>Mídia Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrimeiraInteracao__c.field-meta.xml
<CustomField>
    <fullName>PrimeiraInteracao__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primeira Interação</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a roleta de leads para onde o lead foi distribuído.</description>
    <inlineHelpText>Indica a roleta de leads para onde o lead foi distribuído.</inlineHelpText>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SubProduto__c.field-meta.xml
<CustomField>
    <fullName>SubProduto__c</fullName>
    <label>SubProduto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Park Mariana Life by You,inc</fullName>
            </value>
            <value>
                <fullName>Park Mariana Exclusive by You,inc</fullName>
            </value>
            <value>
                <fullName>Oscar Freire Studios Boutique by You,inc</fullName>
            </value>
            <value>
                <fullName>Eleva Harmonia Studios</fullName>
            </value>
            <value>
                <fullName>Moma Moema Studios</fullName>
            </value>
            <value>
                <fullName>Moma Moema Residencial</fullName>
            </value>
            <value>
                <fullName>Studios Alto by You,inc Paraíso</fullName>
            </value>
            <value>
                <fullName>Studios Casa Jardins by You,inc</fullName>
            </value>
            <value>
                <fullName>Moema Signature Studios by You,inc</fullName>
            </value>
            <value>
                <fullName>Core Pinheiros – Health</fullName>
            </value>
            <value>
                <fullName>Core Pinheiros – Home</fullName>
            </value>
            <value>
                <fullName>Core Pinheiros – Hotel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AtualizarLeadBolsaoJob.cls
public class AtualizarLeadBolsaoJob implements Schedulable {
    private Id roletaLeadsId;

    public AtualizarLeadBolsaoJob(Id roletaLeadsId) {
        this.roletaLeadsId = roletaLeadsId;
    }

    public void execute(SchedulableContext sc) {
        try {
            List<Lead> leadsToClone = [SELECT id, lastname, FirstName, RecordTypeId, MobilePhone, Email, LeadSource, Status, OwnerId, CanalAtendimento__c, ChaveExternaWhatsApp__c, ConfiguracaoDeSLA__c, EmpreendimentoInteresse__c, MidiaOriginal__c, PrimeiraInteracao__c, RoletaLeads__c, SubProduto__c
                                       FROM Lead 
                                       WHERE CorretorContato__r.Name = '' 
                                       AND RoletaLeads__c != null
                                       AND RoletaLeads__r.Id = :roletaLeadsId
                                       AND Status = 'Novo'  
                                       LIMIT 1];
            
            if (leadsToClone.isEmpty()) {
                System.debug('Não há leads para clonar.');
                return;
            }

            delete leadsToClone;

            Lead leadToClone = leadsToClone[0];
            Lead clonedLead = leadToClone.clone(false, true, true, true);
            clonedLead.Status = 'Novo';

            insert clonedLead;

            System.debug('Lead clonado e inserido com sucesso.');
        } catch (Exception e) {
            System.debug('Erro ao clonar e inserir o lead: ' + e.getMessage());
        }
    }
}