force-app/main/default/objects/Lead/fields/CelularAdicional1__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional1__c</fullName>
    <label>Celular Adicional 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CelularAdicional2__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional2__c</fullName>
    <label>Celular Adicional 2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CelularAdicional__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional__c</fullName>
    <inlineHelpText>O campo deve ser preenchido no formato &quot;11999999999&quot;</inlineHelpText>
    <label>Celular Adicional</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CelularComercialAdicional__c.field-meta.xml
<CustomField>
    <fullName>CelularComercialAdicional__c</fullName>
    <label>Celular Comercial Adicional</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmailAdicional__c.field-meta.xml
<CustomField>
    <fullName>EmailAdicional__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email Adicional</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LeadMtnDA.cls
public class LeadMtnDA {

    public static Id obterLeadExistente(String email, String celular) {
        if (String.isBlank(email) && String.isBlank(celular)) {
            return null; 
        }

        List<String> conditions = new List<String>();
        if (String.isNotBlank(celular)) {
            conditions.add('(MobilePhone = :celular)');
            conditions.add('(CelularAdicional__c = :celular)');
            conditions.add('(CelularAdicional1__c = :celular)');
            conditions.add('(CelularAdicional2__c = :celular)');
            conditions.add('(CelularComercialAdicional__c = :celular)');
        }
        if (String.isNotBlank(email)) {
            conditions.add('(Email = :email)');
            conditions.add('(EmailAdicional__c = :email)');
        }

        if (conditions.isEmpty()) {
            return null;
        }

        String query = 'SELECT Id FROM Lead WHERE ' + String.join(conditions, ' OR ') + ' LIMIT 1';

        List<Lead> leads = Database.query(query);
        return (!leads.isEmpty()) ? leads[0].Id : null;
    }
}