force-app/main/default/objects/Lead/fields/CorretorContato__c.field-meta.xml
<CustomField>
    <fullName>CorretorContato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor (Contato)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a roleta de leads para onde o lead foi distribuído.</description>
    <inlineHelpText>Indica a roleta de leads para onde o lead foi distribuído.</inlineHelpText>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>HoraInicio__c</fullName>
    <description>Indica o horário de início para as distribuições de lead para a roleta.</description>
    <label>Hora de início</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/RoletaLeadsHelper.cls
public class RoletaLeadsHelper {

    public static void LeadsBolsao(List<RoletaLeads__c> listaRoletas) {
        Set<Id> idsLeads = new Set<Id>();
    
        System.debug('Lista Roletas: ' + listaRoletas.size());
    
        for (RoletaLeads__c roleta : listaRoletas) { 
            Time horaInicio = roleta.HoraInicio__c;
            System.debug('Hora Inicio: ' + horaInicio);
            Datetime startDateTime = Datetime.newInstance(System.today(), horaInicio);
            System.debug('Start Date Time: ' + startDateTime);
            String baseJobName = 'Bolsao de Leads da Roleta ' + roleta.Id;
    
            System.debug('Base Job Name: ' + baseJobName);
    
            Datetime jobStartTime = startDateTime.addMinutes(5);
    
            List<Lead> leadsBolsao = [
                SELECT Id  
                FROM Lead 
                WHERE RoletaLeads__c != NULL 
                AND CorretorContato__r.Name = ''
                AND Status = 'Novo' 
                AND RoletaLeads__r.Id = :roleta.Id 
                LIMIT 100
            ];
    
            System.debug('Leads Bolsao: ' + leadsBolsao.size());
    
            if (!leadsBolsao.isEmpty()) {
                for (Integer i = 1; i <= leadsBolsao.size(); i++) {
                    if (jobStartTime < System.now()) {
                        jobStartTime = System.now().addMinutes(10);
                    }
    
                    String uniqueJobName = baseJobName + ' - Job ' + i + ' - ' + Datetime.now().getTime();
    
                    List<CronTrigger> jobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :uniqueJobName];
    
                    if (jobs.isEmpty()) {
                        String sch = '0 ' + jobStartTime.minute() + ' ' + jobStartTime.hour() + ' ' + jobStartTime.day() + ' ' + jobStartTime.month() + ' ? ' + jobStartTime.year();
    
                        try {
                            System.schedule(uniqueJobName, sch, new AtualizarLeadBolsaoJob(roleta.Id));
                            idsLeads.add(roleta.Id);
    
                            jobStartTime = jobStartTime.addMinutes(3);
                        } catch (Exception e) {
                            System.debug('Erro ao agendar o job: ' + e.getMessage());
                        }
                    }
                }
            }
        }
    }
    


    public static void LeadsBolsaoHorarioAgendado(List<RoletaLeads__c> listaRoletas, Time horaInicio) {
        Set<Id> idsLeads = new Set<Id>();
        
        System.debug('Lista Roletas: ' + listaRoletas.size());
        
        for (RoletaLeads__c roleta : listaRoletas) {
            System.debug('Hora Inicio: ' + horaInicio);
            Datetime startDateTime = Datetime.newInstance(System.today(), horaInicio);
            System.debug('Start Date Time: ' + startDateTime);
            String baseJobName = 'Bolsao de Leads da Roleta ' + roleta.Id;
            
            System.debug('Base Job Name: ' + baseJobName);
            
            Datetime jobStartTime = startDateTime.addMinutes(5);
            
            List<Lead> leadsBolsao = [
                SELECT Id
                FROM Lead
                WHERE RoletaLeads__c != NULL
                AND CorretorContato__r.Name = ''
                AND RoletaLeads__r.Id = :roleta.Id
                AND Status = 'Novo'
                LIMIT 100
            ];
            
            System.debug('Leads Bolsao: ' + leadsBolsao.size());
            
            // Verifica se já existem jobs agendados com base no nome base do job
            List<AsyncApexJob> existingJobs = [
                SELECT Id, Status, CronTrigger.CronJobDetail.Name 
                FROM AsyncApexJob 
                WHERE (Status = 'Preparing' OR Status = 'Processing' OR Status = 'Queued') 
                AND CronTrigger.CronJobDetail.Name LIKE :('%' + baseJobName + '%')
            ];
            
            if (existingJobs.isEmpty()) {
                if (!leadsBolsao.isEmpty()) {
                    for (Integer i = 1; i <= leadsBolsao.size(); i++) {
                        if (jobStartTime < System.now()) {
                            jobStartTime = System.now().addMinutes(10);
                        }
                        
                        String uniqueJobName = baseJobName + ' - Job ' + i + ' - ' + Datetime.now().getTime();
                        
                        List<CronTrigger> jobs = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = :uniqueJobName];
                        
                        if (jobs.isEmpty()) {
                            String sch = '0 ' + jobStartTime.minute() + ' ' + jobStartTime.hour() + ' ' + jobStartTime.day() + ' ' + jobStartTime.month() + ' ? ' + jobStartTime.year();
                            
                            try {
                                System.schedule(uniqueJobName, sch, new AtualizarLeadBolsaoJob(roleta.Id));
                                idsLeads.add(roleta.Id);
                                
                                jobStartTime = jobStartTime.addMinutes(3);
                            } catch (Exception e) {
                                System.debug('Erro ao agendar o job: ' + e.getMessage());
                            }
                        }
                    }
                }
            } else {
                System.debug('Já existem jobs agendados para ' + baseJobName + '. Nenhum novo job será criado.');
            }
        }
    }
    
    public static void limparParticipantesRoleta(Id roletaId) {
        try {
            List<ParticipanteRoleta__c> participantes = [
                SELECT Id 
                FROM ParticipanteRoleta__c 
                WHERE RoletaLeads__c = :roletaId
            ];  
            if (!participantes.isEmpty()) {
                delete participantes;
            }
        } catch (Exception e) {
            System.debug('Erro ao limpar participantes da roleta: ' + e.getMessage());
        }
    }
}