force-app/main/default/objects/Lead/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a roleta de leads para onde o lead foi distribuído.</description>
    <inlineHelpText>Indica a roleta de leads para onde o lead foi distribuído.</inlineHelpText>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_MTN__c/Lead_MTN__c.object-meta.xml
<CustomObject>
    <label>Lead MTN</label>
    <nameField>
        <label>Lead MTN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead MTNS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_MTN__c/fields/Roleta_de_leads__c.field-meta.xml
<CustomField>
    <fullName>Roleta_de_leads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Lead MTNS</relationshipLabel>
    <relationshipName>Lead_MTNS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/PresencaValidada__c.field-meta.xml
<CustomField>
    <fullName>PresencaValidada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se a presença do corretor foi validada pelo coordenador para recepção de leads.</description>
    <inlineHelpText>Indica se a presença do corretor foi validada pelo coordenador para recepção de leads.</inlineHelpText>
    <label>Presença validada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProcessLeadMtnQueueable.cls
public class ProcessLeadMtnQueueable implements Queueable, Database.AllowsCallouts {
    private List<Lead_MTN__c> leadsToProcess;
    private Integer index;

    public ProcessLeadMtnQueueable(List<Lead_MTN__c> leadsToProcess, Integer index) {
        this.leadsToProcess = leadsToProcess;
        this.index = index;
    }

    public void execute(QueueableContext context) {
        if (index < leadsToProcess.size()) {
            // Processa o Lead_MTN__c atual
            Lead_MTN__c leadMTN = leadsToProcess[index];

            // Verifica se há um participante validado na roleta
            List<ParticipanteRoleta__c> participantes = [
                SELECT Name, PresencaValidada__c, RoletaLeads__r.Name, RoletaLeads__c 
                FROM ParticipanteRoleta__c 
                WHERE RoletaLeads__c = :leadMTN.Roleta_de_leads__c AND PresencaValidada__c = true
                LIMIT 1
            ];

            // Se houver pelo menos um participante validado, processa o lead
            if (!participantes.isEmpty()) {
                LeadMtnHelper.criarLeads(new List<Lead_MTN__c>{leadMTN});
            }

            // Agenda o próximo processamento após 20 segundos (ou 1 minuto)
            Integer nextIndex = index + 1;
            if (nextIndex < leadsToProcess.size()) {
                System.enqueueJob(new ProcessLeadMtnQueueable(leadsToProcess, nextIndex));

                Long waitTime = 15000;
                        DateTime now = DateTime.now();
                        while (DateTime.now().getTime() < now.getTime() + waitTime) {
                            // Espera
                        }
            }
        }
    }
}