force-app/main/default/objects/Contact/fields/CelularAdicional1__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional1__c</fullName>
    <description>1 Celular adicional do Contato.</description>
    <label>Celular Adicional 1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CelularAdicional__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional__c</fullName>
    <description>1 Celular adicional do Contato.</description>
    <inlineHelpText>O campo deve ser preenchido no formato &quot;11999999999&quot;</inlineHelpText>
    <label>Celular Adicional</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecionar se for corretor.</description>
    <label>Corretor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EmailAdicional__c.field-meta.xml
<CustomField>
    <fullName>EmailAdicional__c</fullName>
    <description>E-mail adicional do Contato.</description>
    <label>Email Adicional</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CelularAdicional__c.field-meta.xml
<CustomField>
    <fullName>CelularAdicional__c</fullName>
    <inlineHelpText>O campo deve ser preenchido no formato &quot;11999999999&quot;</inlineHelpText>
    <label>Celular Adicional</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ChaveExternaWhatsApp__c.field-meta.xml
<CustomField>
    <fullName>ChaveExternaWhatsApp__c</fullName>
    <description>Identificador deste lead no WhatsApp.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indique o identificador deste lead no WhatsApp.</inlineHelpText>
    <label>Chave externa (WhatsApp)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica o corretor responsável pelo lead.</description>
    <inlineHelpText>Indique o corretor responsável pelo lead.</inlineHelpText>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O corretor deve pertencer à roleta do lead.</errorMessage>
        <filterItems>
            <field>ParticipanteRoleta__c.RoletaLeads__c</field>
            <operation>equals</operation>
            <valueField>$Source.RoletaLeads__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ParticipanteRoleta__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CorretorContato__c.field-meta.xml
<CustomField>
    <fullName>CorretorContato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor (Contato)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmailAdicional__c.field-meta.xml
<CustomField>
    <fullName>EmailAdicional__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email Adicional</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FimDialogo__c.field-meta.xml
<CustomField>
    <fullName>FimDialogo__c</fullName>
    <description>Indica a data e hora de fim do diálogo via serviço externo de mensagens.</description>
    <inlineHelpText>Indica a data e hora de fim do diálogo via serviço externo de mensagens.</inlineHelpText>
    <label>Fim do diálogo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/InicioDialogo__c.field-meta.xml
<CustomField>
    <fullName>InicioDialogo__c</fullName>
    <description>Indica a data e hora de início do diálogo via serviço externo de mensagens.</description>
    <inlineHelpText>Indica a data e hora de início do diálogo via serviço externo de mensagens.</inlineHelpText>
    <label>Início do diálogo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RemetenteWhatsApp__c.field-meta.xml
<CustomField>
    <fullName>RemetenteWhatsApp__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Campo responsável por definir quem foi o remetente inicial da conversa.</description>
    <inlineHelpText>Se o campo estiver selecionado (True) significa que o Remetente foi o Lead, Se o campo não estiver selecionado (False) significa que o Remetente foi corretor.</inlineHelpText>
    <label>Remetente WhatsApp</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a roleta de leads para onde o lead foi distribuído.</description>
    <inlineHelpText>Indica a roleta de leads para onde o lead foi distribuído.</inlineHelpText>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UltimaMensagem__c.field-meta.xml
<CustomField>
    <fullName>UltimaMensagem__c</fullName>
    <description>Indica a data e hora da última mensagem recebida em conversa via serviço externo de mensagens.</description>
    <inlineHelpText>Indica a data e hora da última mensagem recebida em conversa via serviço externo de mensagens.</inlineHelpText>
    <label>Última mensagem</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/MembroEquipe__c.object-meta.xml
<CustomObject>
    <description>Vincula um usuário responsável pelo atendimento dos leads a uma equipe de roleta de
        leads</description>
    <label>Membro da equipe</label>
    <nameField>
        <label>Nome do membro da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros da equipe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

you/force-app/main/default/objects/MembroEquipe__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipLabel>Membros da equipe</relationshipLabel>
    <relationshipName>MembrosEquipe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MembrosEquipe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/CargaRestante__c.field-meta.xml
<CustomField>
    <fullName>CargaRestante__c</fullName>
    <formula>MembroEquipe__r.Equipe__r.CargaMaxima__c - OcupacaoAtual__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Carga restante</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/MembroEquipe__c.field-meta.xml
<CustomField>
    <fullName>MembroEquipe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica qual membro da equipe participou da roleta.</description>
    <label>Membro da equipe</label>
    <referenceTo>MembroEquipe__c</referenceTo>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsChat__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsChat__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Chat&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Chat&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Chat&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsFaleConosco__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsFaleConosco__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Fale
        conosco&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Fale
        conosco&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Fale conosco&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsLoja__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsLoja__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Loja&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Loja&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Loja&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsStand__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsStand__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Stand&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Stand&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Stand&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsTelefone__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsTelefone__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Telefone&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Telefone&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Telefone&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

you/force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsWhatsApp__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsWhatsApp__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;WhatsApp&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;WhatsApp&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;WhatsApp&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Indica a equipe responsável pelo atendimento dos leads distribuídos para a roleta.</description>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipName>RoletasLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadSelector.cls
public without sharing class LeadSelector {
    
    public static List<Lead> obterLeadsParaDistribuir() {
        return [
            SELECT
                Id,
                Name,
                CanalAtendimento__c,
                RoletaLeads__c,
                Corretor__c,
                ChaveExternaWhatsApp__c,
                FirstName,
                LastName,
                MobilePhone,
                Email,
                CreatedDate,
                Status,
                OwnerId,
                Owner.Name,
                InicioDialogo__c,
                FimDialogo__c,
                UltimaMensagem__c
            FROM Lead
            WHERE Corretor__c = null
        ];
    }
    
    public static List<Lead> obterLeadsPorIdsProprietarios(Set<Id> idsProprietarios) {
        return [
            SELECT 
                Name, 
                Email, 
                CreatedDate, 
                OwnerId, 
                Owner.Name
            FROM Lead 
            WHERE status NOT IN ('Lead Perdido(não trabalho)', 'Conversão', 'Descartado')
            AND OwnerId IN :idsProprietarios
        ];
    }
    
    public static List<Lead> obterLeadsPorIdsCorretores(Set<Id> idsCorretores) {
        return [
            SELECT 
                Name, 
                Email 
            FROM Lead 
            WHERE Corretor__c IN :idsCorretores
        ];
    }
    
    public static List<Lead> obterLeadsPorIdsUsuarios(Set<Id> idsCorretores) {
        // Obtemos os membros da equipe e os nomes das equipes associadas aos corretores
        List<MembroEquipe__c> membros = [
            SELECT Id, Equipe__r.Name 
            FROM MembroEquipe__c 
            WHERE Usuario__r.Id IN :idsCorretores
        ];
    
        // Agora, obtemos os nomes das equipes dos membros
        Set<String> nomesEquipes = new Set<String>();
        for (MembroEquipe__c membro : membros) {
            nomesEquipes.add(membro.Equipe__r.Name);
        }
    
        // Consulta os leads com roleta e cuja equipe está no conjunto de nomes
        List<Lead> leadsComRoleta = [
            SELECT
                Name,
                Email,
                CanalAtendimento__c,
                OwnerId,
                Owner.Name,
                CreatedDate,
                Corretor__r.CargaRestante__c,
                RoletaLeads__r.Name,          
                RoletaLeads__r.Equipe__r.Name
            FROM Lead
            WHERE
                RoletaLeads__r.Id != null 
                AND CorretorContato__c = null 
                AND RoletaLeads__r.Equipe__r.Name IN :nomesEquipes
        ];
    
        // Consulta os leads associados a corretores e que não estão associados ao mesmo corretor
        List<Lead> leadsComEquipe = [
            SELECT
                Name,
                Email,
                CanalAtendimento__c,
                OwnerId,
                Owner.Name,
                CreatedDate,
                Corretor__r.CargaRestante__c
            FROM Lead
            WHERE
                Corretor__r.MembroEquipe__r.Usuario__c IN :idsCorretores
                AND OwnerId NOT IN :idsCorretores
        ];
    
        // Para evitar duplicação, usamos um Set para controlar os IDs dos leads já recuperados
        Set<Id> leadIds = new Set<Id>();
        List<Lead> todosLeads = new List<Lead>();
    
        // Adiciona os leads de RoletaLeads sem duplicação
        for (Lead lead : leadsComRoleta) {
            if (!leadIds.contains(lead.Id)) {
                todosLeads.add(lead);
                leadIds.add(lead.Id);
            }
        }
    
        // Adiciona os leads da equipe sem duplicação
        for (Lead lead : leadsComEquipe) {
            if (!leadIds.contains(lead.Id)) {
                todosLeads.add(lead);
                leadIds.add(lead.Id);
            }
        }
    
        // Retorna a lista combinada sem duplicação
        return todosLeads;
    }
    
    
    public static List<Lead> bolsaoLeads(Set<Id> idsCorretores) {
        return [
            SELECT
                Id,
                Name,
                Email,
                CanalAtendimento__c,
                OwnerId,
                Owner.Name,
                CreatedDate,
                Corretor__r.CargaRestante__c
            FROM Lead
            WHERE
                RoletaLeads__c != ''
                AND CorretorContato__r.Name = ''
                AND OwnerId NOT IN :idsCorretores
        ];
    }
    
    


    public static List<Lead> obterLeadsPorIds(Set<Id> idsLeads) {
        return [
            SELECT
                Name,
                CanalAtendimento__c,
                RoletaLeads__c,
                Corretor__c,
                ChaveExternaWhatsApp__c,
                FirstName,
                LastName,
                MobilePhone,
                Email,
                Status,
                OwnerId,
                CreatedDate,
                Owner.Name,
                InicioDialogo__c,
                FimDialogo__c,
                UltimaMensagem__c,
                EmpreendimentoInteresse__r.Name,
                RemetenteWhatsApp__c,
                Corretor__r.QuantidadeLeadsFaleConosco__c,
                Corretor__r.QuantidadeLeadsChat__c,
                Corretor__r.QuantidadeLeadsWhatsApp__c,
                Corretor__r.QuantidadeLeadsTelefone__c,
                Corretor__r.QuantidadeLeadsLoja__c,
                Corretor__r.QuantidadeLeadsStand__c
            FROM Lead
            WHERE Id IN :idsLeads
        ];
    }
    
    // esse metodo esra esperando um set de ids mas esta passando uma lista o que esra errado 
    // public static List<Lead> obterLeadsPorIds(Set<Id> idsLeads) {
    //     Lead lead = [
    //         SELECT EmpreendimentoInteresse__r.Name 
    //         FROM Lead 
    //         WHERE Id = :idsLeads
    //     ];
    
    //     return [
    //         SELECT
    //             Name,
    //             CanalAtendimento__c,
    //             RoletaLeads__c,
    //             Corretor__c,
    //             ChaveExternaWhatsApp__c,
    //             FirstName,
    //             LastName,
    //             MobilePhone,
    //             Email,
    //             Status,
    //             OwnerId,
    //             CreatedDate,
    //             Owner.Name,
    //             InicioDialogo__c,
    //             FimDialogo__c,
    //             UltimaMensagem__c,
    //             EmpreendimentoInteresse__c,
    //             Corretor__r.QuantidadeLeadsFaleConosco__c,
    //             Corretor__r.QuantidadeLeadsChat__c,
    //             Corretor__r.QuantidadeLeadsWhatsApp__c,
    //             Corretor__r.QuantidadeLeadsTelefone__c,
    //             Corretor__r.QuantidadeLeadsLoja__c,
    //             Corretor__r.QuantidadeLeadsStand__c
    //         FROM Lead
    //         WHERE Id IN :idsLeads
    //     ];
    // }

    public static List<Lead> obterLeadsPorChavesExternasClientes(Set<String> chavesClientes) {
        return [
            SELECT ChaveExternaWhatsApp__c 
            FROM Lead 
            WHERE ChaveExternaWhatsApp__c IN :chavesClientes
        ];
    }

    public static List<Lead> obterLeadsPorInformacoesConcierge(String nomeCompleto, String celular, String email) {
        return Database.query(
            'SELECT ' +
            '    Name, ' +
            '    FirstName, ' +
            '    LastName, ' +
            '    MobilePhone, ' +
            '    Email, ' +
            '    Status, ' +
            '    LeadSource, ' +
            '    CanalAtendimento__c, ' +
            '    Owner.Name ' +
            'FROM Lead ' +
            'WHERE ' +
            '    (Name LIKE \'%' + nomeCompleto + '%\' AND Name != null) OR ' +
            '    (MobilePhone = :celular AND MobilePhone != null) OR ' +
            '    (Email = :email AND Email != null)'
        );
    }

    public static List<Lead> obterLeadsPorInformacoesConcierge(String celular, String email, Boolean isJuridica, String phone) {
        List<String> conditions = new List<String>();
    
        // Construir as condições da consulta dinamicamente
        if (isJuridica) {
            if (String.isNotBlank(phone)) {
                conditions.add('(Phone = :phone)');
            }
            if (String.isNotBlank(email)) {
                conditions.add('(EmailAdicional__c = :email)');
                conditions.add('(Email = :email)');
            }
        } else {
            if (String.isNotBlank(celular)) {
                conditions.add('(MobilePhone = :celular)');
                conditions.add('(CelularAdicional__c = :celular)');
                conditions.add('(CelularAdicional1__c = :celular)');
                conditions.add('(CelularAdicional2__c = :celular)');
                conditions.add('(CelularComercialAdicional__c = :celular)');
            }
            if (String.isNotBlank(email)) {
                conditions.add('(Email = :email)');
                conditions.add('(EmailAdicional__c = :email)');
            }
        }
    
        // Se nenhuma condição for adicionada, retorne uma lista vazia
        if (conditions.isEmpty()) {
            return new List<Lead>();
        }
    
        // Construa a consulta com as condições dinâmicas
        String query = 'SELECT ' +
                       '    Id, ' +
                       '    Name, ' +
                       '    MobilePhone, ' +
                       '    Email, ' +
                       '    Status, ' +
                       '    Owner.Name, ' +
                       '    CorretorContato__r.Name, ' + 
                       '    InicioDialogo__c, ' +
                       '    FimDialogo__c, ' +
                       '    UltimaMensagem__c, ' +
                       '    Phone, ' +
                       '    CreatedDate ' +
                       'FROM Lead ' +
                       'WHERE ' + String.join(conditions, ' OR ') +
                       ' LIMIT 500';
    
        // Realize a consulta usando a string de consulta dinâmica
        return Database.query(query);
    }
    
    
    public static Lead obterMobilePhoneLead(String idLead) {
        return [
            SELECT MobilePhone 
            FROM Lead 
            WHERE Id = :idLead
        ];
    }

    public static Lead obterInfosTemplatePadrao(String idLead) {
        return [
            SELECT 
                MobilePhone,
                FirstName,
                Owner.Name,
                EmpreendimentoInteresse__c,
                ChaveExternaWhatsApp__c
            FROM Lead 
            WHERE Id = :idLead
        ];
    }
}