force-app/main/default/objects/Contact/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecionar se for corretor.</description>
    <label>Corretor</label>
    <type>Checkbox</type>
</CustomField>

you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>UsuarioCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário do Corretor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipe__c/Equipe__c.object-meta.xml
<CustomObject>
    <description>Agrupa os responsáveis pelo atendimento dos leads distribuídos por
        roleta</description>
    <label>Equipe</label>
    <nameField>
        <label>Nome da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipe__c/fields/CargaMaxima__c.field-meta.xml
<CustomField>
    <fullName>CargaMaxima__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Carga máxima</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica o corretor responsável pelo lead.</description>
    <inlineHelpText>Indique o corretor responsável pelo lead.</inlineHelpText>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O corretor deve pertencer à roleta do lead.</errorMessage>
        <filterItems>
            <field>ParticipanteRoleta__c.RoletaLeads__c</field>
            <operation>equals</operation>
            <valueField>$Source.RoletaLeads__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ParticipanteRoleta__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CorretorContato__c.field-meta.xml
<CustomField>
    <fullName>CorretorContato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor (Contato)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>LeadsEmpreendimentoInteresse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a roleta de leads para onde o lead foi distribuído.</description>
    <inlineHelpText>Indica a roleta de leads para onde o lead foi distribuído.</inlineHelpText>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>UsuarioCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Contato)</relationshipLabel>
    <relationshipName>LeadsContatoCorretor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/MembroEquipe__c.object-meta.xml
<CustomObject>
    <description>Vincula um usuário responsável pelo atendimento dos leads a uma equipe de roleta de
        leads</description>
    <label>Membro da equipe</label>
    <nameField>
        <label>Nome do membro da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros da equipe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

you/force-app/main/default/objects/MembroEquipe__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipLabel>Membros da equipe</relationshipLabel>
    <relationshipName>MembrosEquipe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MembrosEquipe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/MembroEquipe__c.field-meta.xml
<CustomField>
    <fullName>MembroEquipe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica qual membro da equipe participou da roleta.</description>
    <label>Membro da equipe</label>
    <referenceTo>MembroEquipe__c</referenceTo>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/ParticipanteRoleta__c/fields/Posicao__c.field-meta.xml
<CustomField>
    <fullName>Posicao__c</fullName>
    <description>Indica a posição do participante na fila para distribuição de leads.</description>
    <inlineHelpText>Indica a posição do participante na fila para distribuição de leads.</inlineHelpText>
    <label>Posição</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <description>Indica a situação do usuário no Omnichannel.</description>
    <formula>TEXT(MembroEquipe__r.Usuario__r.Situacao__c)</formula>
    <inlineHelpText>Indica a situação do usuário no Omnichannel.</inlineHelpText>
    <label>Situação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/UsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>UsuarioCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>Participantes_da_roleta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/DiasSemana__c.field-meta.xml
<CustomField>
    <fullName>DiasSemana__c</fullName>
    <description>Indica em quais dias da semana podem ser realizadas distribuições de lead para a
        roleta</description>
    <inlineHelpText>Selecione os dias da semana para a distribuição de leads na roleta.</inlineHelpText>
    <label>Dias da semana</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiasSemana</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Indica a equipe responsável pelo atendimento dos leads distribuídos para a roleta.</description>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipName>RoletasLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <defaultValue>&apos;Offline&apos;</defaultValue>
    <label>Situação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SituacoesParticipantes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CanaisAtendimento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fale conosco</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Telefone</fullName>
    </customValue>
    <customValue>
        <fullName>Loja</fullName>
    </customValue>
    <customValue>
        <fullName>Stand</fullName>
    </customValue>
    <masterLabel>Canais de atendimento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DiasSemana.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domingo</fullName>
    </customValue>
    <customValue>
        <fullName>Segunda-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Terça-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quarta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quinta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sexta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sábado</fullName>
    </customValue>
    <masterLabel>Dias da semana</masterLabel>
</GlobalValueSet>

you/force-app/main/default/globalValueSets/SituacoesParticipantes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Indisponível</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Situações dos participantes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OmnichannelServiceTest.cls
@isTest
public class OmnichannelServiceTest {

    @TestSetup
    static void setupTestData() {
        // Criação de um Empreendimento de exemplo com CNPJ
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Teste empreendimento',
            CNPJEmpreendimento__c = '91529585000197' // Adicione um CNPJ válido
        );
        insert empreendimento;
    
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator' LIMIT 1];
        

        Contact corretor1 = new Contact(
            FirstName = 'Carlos', 
            LastName = 'Silva',
            CPF__c = '84057287248'
        );
        insert corretor1;


        User usuarioCorretor = new User(
          LastName = 'LIVESTON',
          FirstName='JASON',
          Username = 'jasonl@gmail.com',
          Alias = 'jliv',
          Email = 'john@acme.com',
          ProfileId = adminProfile.Id,
          TimeZoneSidKey = 'GMT',
          LanguageLocaleKey = 'en_US',
          EmailEncodingKey = 'UTF-8',
          LocaleSidKey = 'en_US'
        );
    
        insert usuarioCorretor;

        


    
        // Criação de um Roleta Leads
        RoletaLeads__c roleta1 = new RoletaLeads__c(
            Name = 'Roleta You - Corretores novo',
            CanaisAtendimento__c = 'Fale conosco;Chat;WhatsApp;Telefone;Loja;Stand',
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira'
        );
        insert roleta1;
    
        // Criar uma equipe
        Equipe__c eq = new Equipe__c(Name = 'eq' , CargaMaxima__c = 3.00);
        insert eq;


    
        // Criação de um Membro de Equipe
        MembroEquipe__c membro = new MembroEquipe__c(Name = 'Membro Teste', Equipe__c = eq.Id , Usuario__c = usuarioCorretor.Id);
        insert membro;

        // Criação de um Participante Roleta
        ParticipanteRoleta__c participante = new ParticipanteRoleta__c(
            MembroEquipe__c = membro.Id,
            RoletaLeads__c = roleta1.Id,
            Posicao__c = 1,
            UsuarioCorretor__c = corretor1.Id 
        );
        insert participante;

        Lead testLead = new Lead(
            LastName = 'Lead silva',
            FirstName = 'Silva',
            Company = 'Empresa XYZ',
            Email = 'leadsilvana332@gmail.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Fale conosco',
            MobilePhone = '5519987654109',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id,
            OwnerId = usuarioCorretor.Id,
            corretorContato__c = corretor1.Id,
            Corretor__c = participante.Id 
        );
        insert testLead;
        
      
        
    }
    

    @IsTest
    static void testSelecionarCanais() {
        List<String> canaisAtendimento = new List<String>{'Fale conosco;Chat;WhatsApp;Telefone;Loja;Stand'};
        String result = OmnichannelService.selecionarCanais(canaisAtendimento);
        System.assertNotEquals(null, result, 'A seleção de canais não retornou um resultado válido.');
    }

    

    @IsTest
    static void testRejeitarLead() {
        // Configuração de dados de teste
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Teste empreendimento',
            CNPJEmpreendimento__c = '91529585000197'
        );
        insert empreendimento;
    
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
    
        Contact corretor1 = new Contact(
            FirstName = 'Gustavo',
            LastName = 'Da Silva',
            CPF__c = '84057287248'
        );
        insert corretor1;
    
        User usuarioCorretor = new User(
            LastName = 'LIVESTONG',
            FirstName = 'JASONL',
            Username = 'jason' + System.currentTimeMillis() + '@gmail.com',
            Alias = 'jlivb',
            Email = 'john@acmes.com',
            ProfileId = adminProfile.Id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US',
            Situacao__c = 'Online'
        );
        insert usuarioCorretor;
    
        RoletaLeads__c roleta1 = new RoletaLeads__c(
            Name = 'Roleta Teste',
            CanaisAtendimento__c = 'Fale conosco;Chat',
            DiasSemana__c = 'Segunda-feira;Terça-feira'
        );
        insert roleta1;
    
        Equipe__c equipe = new Equipe__c(
            Name = 'Equipe Teste',
            CargaMaxima__c = 5.0
        );
        insert equipe;
    
        MembroEquipe__c membroEquipe = new MembroEquipe__c(
            Name = 'Membro Teste',
            Equipe__c = equipe.Id,
            Usuario__c = usuarioCorretor.Id
        );
        insert membroEquipe;
    
        ParticipanteRoleta__c participante = new ParticipanteRoleta__c(
            MembroEquipe__c = membroEquipe.Id,
            RoletaLeads__c = roleta1.Id,
            Posicao__c = 1
        );
        insert participante;
    
        Lead testLead = new Lead(
            LastName = 'Ferreira',
            FirstName = 'Da Silva',
            Company = 'Empresa Teste',
            Email = 'silva@teste.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Fale conosco',
            MobilePhone = '5511987654323',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id,
            RoletaLeads__c = roleta1.Id,
            OwnerId = usuarioCorretor.Id,
            Corretor__c = participante.Id
        );
        insert testLead;
    
        Test.startTest();
        String result = OmnichannelService.rejeitarLead(testLead.Id);
        Test.stopTest();
    
        System.assertNotEquals(null, result, 'O resultado não deve ser nulo.');
    }


    @IsTest
    static void testAlterarSituacao() {
        String novaSituacao = 'Online';
        String result = OmnichannelService.alterarSituacao(novaSituacao);
        System.assertNotEquals(null, result, 'A alteração de situação não retornou um resultado válido.');
    }
    
    @IsTest
    static void testAlterarSituacaog() {
        String novaSituacao = 'Indisponível';
        String result = OmnichannelService.alterarSituacao(novaSituacao);
        System.assertNotEquals(null, result, 'A alteração de situação não retornou um resultado válido.');
    }
    
     @IsTest
    static void testAlterarSituacaoOffline() {
        String novaSituacao = 'Offline';
        String result = OmnichannelService.alterarSituacao(novaSituacao);
        System.assertNotEquals(null, result, 'A alteração de situação não retornou um resultado válido.');
    }
    @isTest
    static void UsuarioOffline(){
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator' LIMIT 1];
        
        User testUser = new User(
            FirstName = 'Dantas',
            LastName = 'Will',
            Alias = 'wdantas',
            Email = 'wdantas@example.com',
            Username = 'wdantas@test.com' + System.currentTimeMillis(), // Para garantir unicidade
            ProfileId = adminProfile.Id, // Usar o ProfileId do Administrador do sistema
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            TimeZoneSidKey = 'America/New_York',
            LanguageLocaleKey = 'pt_BR',
            Situacao__c = '' // Inicialmente em branco
        );
        insert testUser;

        String result = OmnichannelService.alterarSituacao('Offline');
    }

    @IsTest
    static void testObterLeadsEmTrabalho() {
        String result = OmnichannelService.obterLeadsEmTrabalho();
        System.assertNotEquals(null, result, 'A obtenção de leads em trabalho não retornou um resultado válido.');
    }

   @IsTest
static void testObterLeadsEmNovo() {
    // Criar um contato de teste
    Contact testContact = new Contact(
        FirstName = 'Contato',
        LastName = 'Teste',
        Email = 'contato.teste@example.com'
    );
    insert testContact;
    
    // Criação de um perfil
    Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

    // Criar um usuário de teste
    User testUser = new User(
        FirstName = 'Gabriel',
        LastName = 'Lima',
        Alias = 'gab',
        Email = 'gab@example.com',
        Username = 'gab@test.com' + System.currentTimeMillis(),
        ProfileId = adminProfile.Id,
        LocaleSidKey = 'en_US',
        EmailEncodingKey = 'UTF-8',
        TimeZoneSidKey = 'America/New_York',
        LanguageLocaleKey = 'pt_BR',
        Situacao__c = 'Online'
    );
    insert testUser;

    // Criar um único Lead de teste
    Lead testLead = new Lead(
        FirstName = 'Lead1',
        LastName = 'Teste',
        Company = 'Empresa 1',
        Email = 'lead1@empresa.com',
        Phone = '1234567890',
        MobilePhone = '9876543210',
        Status = 'Novo',
        CanalAtendimento__c = 'Fale conosco',
        CorretorContato__c = testContact.Id,
        OwnerId = UserInfo.getUserId()
    );
    insert testLead;

    // Rodar como o usuário de teste
    System.runAs(testUser) {
        Test.startTest();
        String result = OmnichannelService.obterLeadsEmNovo();
        Test.stopTest();

        // Validar o resultado
        System.assertNotEquals(null, result, 'O resultado não deve ser nulo.');
        List<LeadDTO> leadsDTO = (List<LeadDTO>) JSON.deserialize(result, List<LeadDTO>.class);
    }
}

    @IsTest
    static void testObterUsuario() {
        
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator' LIMIT 1];
        
        User testUser = new User(
            FirstName = 'Gabriel',
            LastName = 'Lima',
            Alias = 'gab',
            Email = 'gab@example.com',
            Username = 'gab@test.com' + System.currentTimeMillis(), // Para garantir unicidade
            ProfileId = adminProfile.Id, // Usar o ProfileId do Administrador do sistema
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            TimeZoneSidKey = 'America/New_York',
            LanguageLocaleKey = 'pt_BR',
            Situacao__c = ' '
        );
        insert testUser;
        
        System.runAs(testUser) {
            String result = OmnichannelService.obterUsuario();
            System.assertNotEquals(null, result, 'A obtenção do usuário não retornou um resultado válido.');
        }
    }

    @IsTest
    static void testObterSituacoes() {
        Map<String, String> result = OmnichannelService.obterSituacoes();
        System.assertNotEquals(null, result, 'A obtenção das situações não retornou um resultado válido.');
        System.assert(!result.isEmpty(), 'As situações obtidas estão vazias.');
    }

    @IsTest
    static void testDefinirStatusInicial() {
                Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator' LIMIT 1];
        
        User testUser = new User(
            FirstName = 'Gabriel',
            LastName = 'Lima',
            Alias = 'gab',
            Email = 'gab@example.com',
            Username = 'gab@test.com' + System.currentTimeMillis(), // Para garantir unicidade
            ProfileId = adminProfile.Id, // Usar o ProfileId do Administrador do sistema
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            TimeZoneSidKey = 'America/New_York',
            LanguageLocaleKey = 'pt_BR',
            Situacao__c = null
        );
        insert testUser;
        
        System.runAs(testUser) {
         	String result = OmnichannelService.definirStatusInicial();
        	System.assertNotEquals(null, result, 'A definição de status inicial não retornou um resultado válido.');   
        }
    }

    @IsTest
    static void testObterCanaisAtendimento() {
        Map<String, String> result = OmnichannelService.obterCanaisAtendimento();
        Test.startTest();
    }
    @isTest
    static void testAceitarLead() {
        Test.startTest();
        Lead testLead = [SELECT Id FROM Lead LIMIT 1];
        String result = OmnichannelService.aceitarLead(testLead.Id);  
        Test.stopTest();
        
    }
    
    @isTest
    static void testAceitarLeadNull() {
        // Criação do Empreendimento
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Teste empreendimento',
            CNPJEmpreendimento__c = '91529585000197' // CNPJ válido
        );
        insert empreendimento;
    
        // Criação de um perfil de administrador
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator' LIMIT 1];        
    
        // Criação de um corretor (usuário)
        Contact corretor1 = new Contact(
            FirstName = 'Gustavo', 
            LastName = 'Da Silva',
            CPF__c = '84057287248'
        );
        insert corretor1;
    
        User usuarioCorretor = new User(
            LastName = 'LIVESTONG',
            FirstName = 'JASONL',
            Username = 'japon43@gmail.com',
            Alias = 'jlivb',
            Email = 'john@acmes.com',
            ProfileId = adminProfile.Id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );
        insert usuarioCorretor;
    
        // Criação de uma roleta de leads
        RoletaLeads__c roleta1 = new RoletaLeads__c(
            Name = 'Roleta You - Corretores novos',
            CanaisAtendimento__c = 'Fale conosco;Chat;WhatsApp;Telefone;Loja;Stand',
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira'
        );
        insert roleta1;
    
        // Criação de uma equipe
        Equipe__c eq = new Equipe__c(Name = 'eq', CargaMaxima__c = 3.00);
        insert eq;
    
        // Criação de um membro da equipe
        MembroEquipe__c membro = new MembroEquipe__c(
            Name = 'Membro Teste',
            Equipe__c = eq.Id,
            Usuario__c = usuarioCorretor.Id
        );
        insert membro;
    
        // Criação de um participante da roleta
        ParticipanteRoleta__c participante = new ParticipanteRoleta__c(
            MembroEquipe__c = membro.Id,
            RoletaLeads__c = roleta1.Id, 
            Posicao__c = 1,
            UsuarioCorretor__c = corretor1.Id
        );
        insert participante;
    
        // Criação de um lead com corretor nulo
        Lead testLeadNull = new Lead(
            LastName = 'Ferreira',
            FirstName = 'Da Silva',
            Company = 'Empresa WXYZ',
            Email = 'silva@wxyz.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Fale conosco',
            MobilePhone = '5511987654323',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id,
            RoletaLeads__c = roleta1.Id,
            OwnerId = usuarioCorretor.Id,
            corretorContato__c = corretor1.Id,
            Corretor__c = null
        );
        insert testLeadNull;
    
        // Teste de aceitação do lead
        System.runAs(usuarioCorretor) {
            Test.startTest();
            String result = OmnichannelService.aceitarLead(testLeadNull.Id);
            Test.stopTest();
        
            // Validações
            Lead updatedLead = [SELECT Corretor__c, OwnerId FROM Lead WHERE Id = :testLeadNull.Id];
            System.assertEquals(usuarioCorretor.Id, updatedLead.OwnerId, 'O OwnerId deve ser atualizado para o usuário corretor.');
        }
    }
    
    @isTest
    static void testAceitarChat() {
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator' LIMIT 1];
    
        Contact corretor1 = new Contact(
            FirstName = 'Pereira Lucas', 
            LastName = 'Silva',
            CPF__c = '10695957058'
        );
        insert corretor1;
    
        User testUser = new User(
            LastName = 'pejrkd',
            FirstName = 'sjajsas',
            Username = 'shajsas@gmail.com',
            Alias = 'lupi',
            Email = 'jdhsj@acme.com',
            ProfileId = adminProfile.id,
            TimeZoneSidKey = 'GMT',
            LanguageLocaleKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LocaleSidKey = 'en_US'
        );
        insert testUser;
    
        // Criação de uma roleta de leads
        RoletaLeads__c roleta1 = new RoletaLeads__c(
            Name = 'Roleta You - Corretores novo',
            CanaisAtendimento__c = 'Fale conosco;Chat;WhatsApp;Telefone;Loja;Stand',
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira'
        );
        insert roleta1;
    
        // Criação de uma equipe
        Equipe__c eq = new Equipe__c(Name = 'lucas', CargaMaxima__c = 10.00);
        insert eq;
    
        // Criação de um membro da equipe
        MembroEquipe__c membro = new MembroEquipe__c(Name = 'Membro Pleno', Equipe__c = eq.Id , Usuario__c = testUser.Id);
        insert membro;
    
        // Criação de um participante da roleta
        ParticipanteRoleta__c participante = new ParticipanteRoleta__c(
            MembroEquipe__c = membro.Id,
            RoletaLeads__c = roleta1.Id,
            Posicao__c = 1,
            UsuarioCorretor__c = corretor1.Id 
        );
        insert participante;
    
        // Criação de um empreendimento
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Teste empreendimento',
            CNPJEmpreendimento__c = '91529585000197' // CNPJ válido
        );
        insert empreendimento;
    
        // Criação de um lead
        Lead leadNovo = new Lead(
            LastName = 'DSKJDJKJKSD',
            FirstName = 'DSDJSDSHJ',
            Company = 'Empresa JHDHJ',
            Email = 'POWIOQJFN@xyz.com',
            LeadSource = 'Chat',
            CanalAtendimento__c = 'Chat',
            MobilePhone = '11987651286',
            Status = 'Novo',
            EmpreendimentoInteresse__c = empreendimento.Id,
            OwnerId = testUser.Id,
            corretorContato__c = corretor1.Id,
            Corretor__c = participante.Id 
        );
        insert leadNovo;
    
        // Teste de aceitação do lead
        String result = OmnichannelService.aceitarLead(leadNovo.Id); 
    }
    
    @IsTest
    static void chatter() {
        Lead testLead = new Lead(
            LastName = 'Silva',
            FirstName = 'Teste',
            Company = 'Empresa XYZ',
            Email = 'test.lead43@yahoo.com',
            Status = 'Novo',
            MobilePhone = '5511989540932'
        );
        insert testLead;
    
        User user = [SELECT Id FROM User WHERE IsActive = true AND Profile.Name = 'System Administrator' LIMIT 1];
    
        // Chama o método a ser testado
        OmnichannelService.notificarPeloChatter(testLead.Id, user.Id);
    }
    
  
}