force-app/main/default/objects/Contact/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecionar se for corretor.</description>
    <label>Corretor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UsuarioCorretor__c.field-meta.xml
<CustomField>
    <fullName>UsuarioCorretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário do Corretor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Cliente.recordType-meta.xml
<RecordType>
    <fullName>Cliente</fullName>
    <active>true</active>
    <label>Cliente</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <infoMessage>Corretor: Tipo de registro do contatoigual aCorretor</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status da unidade</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Disponivel</fullName>
            </value>
            <value>
                <fullName>&lt;&lt;LISTAR STATUS&gt;&gt;</fullName>
                <isActive>false</isActive>
                <label>&lt;&lt;LISTAR STATUS&gt;&gt;</label>
            </value>
            <value>
                <fullName>Contrato Assinado</fullName>
                <isActive>false</isActive>
                <label>Contrato Assinado</label>
            </value>
            <value>
                <fullName>Contrato Emitido</fullName>
                <isActive>false</isActive>
                <label>Contrato Emitido</label>
            </value>
            <value>
                <fullName>Negociação</fullName>
                <isActive>false</isActive>
                <label>Negociação</label>
            </value>
            <value>
                <fullName>Permuta</fullName>
                <isActive>false</isActive>
                <label>Permuta</label>
            </value>
            <value>
                <fullName>Reserva condicional</fullName>
                <isActive>false</isActive>
                <label>Reserva condicional</label>
            </value>
            <value>
                <fullName>SD Fora de Venda</fullName>
                <isActive>false</isActive>
                <label>SD Fora de Venda</label>
            </value>
            <value>
                <fullName>Venda Integrada</fullName>
                <isActive>false</isActive>
                <label>Venda Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Reportase__c.field-meta.xml
<CustomField>
    <fullName>Reportase__c</fullName>
    <label>Reporta-se à</label>
    <relationshipName>HierarquiaCargo</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/NotificacaoHelper.cls
public class NotificacaoHelper {
    public static void notificacaoEquipeVendas(List<Product2> produtos) {
        Set<Id> idProduto = new Set<Id>();
        List<Opportunity> listaOportunidades = new List<Opportunity>();
    
        if (!produtos.isEmpty()) {
            
            for (Product2 produto : produtos) {
                idProduto.add(produto.Id);
            }
    
            listaOportunidades = OpportunityDA.obterOportunidadePorIdProduto(idProduto);
        }
    
        if (!listaOportunidades.isEmpty()) {

            buscarEquipeVendas(listaOportunidades);
        }
    }


    public static void buscarEquipeVendas(List<Opportunity> listaOportunidades) {
        List<User> usuarios = UserSelector.obterUsuarios();
        Set<String> emailsEquipeVendas = new Set<String>();
        Set<Id> supervisoresProcessados = new Set<Id>();
        Id idReporte;

        for (Opportunity opp : listaOportunidades) {
            for (User user : usuarios) {
                
                if (opp.Corretor__r.UsuarioCorretor__c == user.Id) {
                   idReporte = user.Reportase__c;
                    
                    emailsEquipeVendas.add(user.Email);
    
                    buscarSupervisores(idReporte, user, emailsEquipeVendas, listaOportunidades, supervisoresProcessados);
                }
            }
        }
    
    }
    
    public static void buscarSupervisores(Id idReporte, User user, Set<String> emailsEquipeVendas, List<Opportunity> listaOportunidades, Set<Id> supervisoresProcessados) {
        
        if (idReporte != null && user.Reportase__r.Email != null && !supervisoresProcessados.contains(user.Reportase__c)) {
            
            emailsEquipeVendas.add(user.Reportase__r.Email);
            supervisoresProcessados.add(user.Reportase__c);
            
            User supervisor = [SELECT Id, Email, Reportase__c, Reportase__r.Email FROM User WHERE Id = :idReporte LIMIT 1];
            
            buscarSupervisores(idReporte, supervisor, emailsEquipeVendas, listaOportunidades, supervisoresProcessados);
        }
    
        if (!emailsEquipeVendas.isEmpty()) {
            List<String> listaEmailsEquipeVendas = new List<String>(emailsEquipeVendas);
    
            mandarEmailEquipeVendas(listaEmailsEquipeVendas, listaOportunidades);
        }
    }

    public static void mandarEmailEquipeVendas(List<String> listaEmailsEquipeVendas, List<Opportunity> listaOportunidades) {
        List<Contact> contatos = [SELECT Id, Name, Email, UsuarioCorretor__r.Email FROM Contact WHERE RecordType.Name = 'Corretor'];
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        EmailTemplate template = [SELECT Id, DeveloperName, Name FROM EmailTemplate WHERE Name = 'Template de email para a equipe de vendas' LIMIT 1];

        if (!listaOportunidades.isEmpty()) {
            
          Id produtoId = listaOportunidades[0].Unidade__r.Id;
          String nomeUnidade = listaOportunidades[0].Unidade__r.Name;
          String statusUnidade = listaOportunidades[0].Unidade__r.Status__c;
    
            for (Contact contato : contatos) {
                if (listaEmailsEquipeVendas.contains(contato.UsuarioCorretor__r.Email)) {
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    email.setTemplateId(template.Id);  
                    email.setTargetObjectId(contato.Id); 
                    email.setWhatId(produtoId);  
                    email.setToAddresses(new String[] { contato.UsuarioCorretor__r.Email});  
                    
                    emails.add(email);
                }

            }

            if (!emails.isEmpty()) {
                Messaging.sendEmail(emails);
            }
        }
    }

    public static void notificacaoCliente(List<Product2> produtos) {
        Set<Id> idProduto = new Set<Id>();
        List<Opportunity> listaEmailCliente = new List<Opportunity>();
        String nomeUnidade;
        String statusUnidade;
        String emailCliente;
        Id idContato;

        if(!produtos.isEmpty()){

            for (Product2 produto : produtos) {
                idProduto.add(produto.id);
            }

            listaEmailCliente = OpportunityDA.obterOportunidadePorIdProduto(idProduto);
        }

        if(!listaEmailCliente.isEmpty()){
            nomeUnidade = listaEmailCliente[0].Unidade__r.Name;
            statusUnidade = listaEmailCliente[0].Unidade__r.Status__c;
            emailCliente = listaEmailCliente[0].Account.PersonEmail;
            idContato = listaEmailCliente[0].Account.id;

            mandarEmailCliente(idContato, emailCliente, nomeUnidade, statusUnidade, idProduto);
        }
    }


    public static void mandarEmailCliente(Id idContato, String emailCliente, String nomeUnidade, String statusUnidade, Set<id> setIdProduto){
        EmailTemplate template = [SELECT Id, DeveloperName, Name FROM EmailTemplate WHERE Name = 'Template de notifcação para o cliente' LIMIT 1];
        Product2 produto = ProdutoSelector.buscarUnidadePorSetId(setIdProduto);
        Account idCliente = [SELECT Id, PersonContact.Id FROM Account WHERE Id = :idContato];
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        

        if(statusUnidade == 'Disponivel'){

            email.setTemplateId(template.Id);  
            email.setTargetObjectId(idCliente.PersonContact.Id); 
            email.setWhatId(produto.Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }else if(statusUnidade == 'Reservada'){
            email.setTemplateId(template.Id);  
            email.setTargetObjectId(idCliente.PersonContact.Id); 
            email.setWhatId(produto.Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }else{

            email.setTemplateId(template.Id);  
            email.setTargetObjectId(idCliente.PersonContact.Id); 
            email.setWhatId(produto.Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }
    }
}