force-app/main/default/objects/Contact/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Selecionar se for corretor.</description>
    <label>Corretor</label>
    <type>Checkbox</type>
</CustomField>

you/force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do contato.</description>
    <inlineHelpText>Verifique se o CPF está no formato correto: de 11 dígitos corridos</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DatadeVencimento__c.field-meta.xml
<CustomField>
    <fullName>DatadeVencimento__c</fullName>
    <description>Deve ser preenchido
com a data de vencimento do
CRECI.</description>
    <label>Data de Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Equipe__c/Equipe__c.object-meta.xml
<CustomObject>
    <description>Agrupa os responsáveis pelo atendimento dos leads distribuídos por
        roleta</description>
    <label>Equipe</label>
    <nameField>
        <label>Nome da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica o corretor responsável pelo lead.</description>
    <inlineHelpText>Indique o corretor responsável pelo lead.</inlineHelpText>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O corretor deve pertencer à roleta do lead.</errorMessage>
        <filterItems>
            <field>ParticipanteRoleta__c.RoletaLeads__c</field>
            <operation>equals</operation>
            <valueField>$Source.RoletaLeads__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ParticipanteRoleta__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a roleta de leads para onde o lead foi distribuído.</description>
    <inlineHelpText>Indica a roleta de leads para onde o lead foi distribuído.</inlineHelpText>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/MembroEquipe__c.object-meta.xml
<CustomObject>
    <description>Vincula um usuário responsável pelo atendimento dos leads a uma equipe de roleta de
        leads</description>
    <label>Membro da equipe</label>
    <nameField>
        <label>Nome do membro da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros da equipe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

you/force-app/main/default/objects/MembroEquipe__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipLabel>Membros da equipe</relationshipLabel>
    <relationshipName>MembrosEquipe</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

you/force-app/main/default/objects/MembroEquipe__c/fields/ExigeValidacaoCoordenador__c.field-meta.xml
<CustomField>
    <fullName>ExigeValidacaoCoordenador__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica necessidade de validação de presença do corretor pelo coordenador para recepção de novos leads.</description>
    <inlineHelpText>Indica necessidade de validação de presença do corretor pelo coordenador para recepção de novos leads.</inlineHelpText>
    <label>Exige validação do coordenador?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MembrosEquipe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/CargaRestante__c.field-meta.xml
<CustomField>
    <fullName>CargaRestante__c</fullName>
    <formula>MembroEquipe__r.Equipe__r.CargaMaxima__c - OcupacaoAtual__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Carga restante</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Entrada__c.field-meta.xml
<CustomField>
    <fullName>Entrada__c</fullName>
    <description>Indica o momento de entrada do participante da roleta.</description>
    <label>Entrada</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/MembroEquipe__c.field-meta.xml
<CustomField>
    <fullName>MembroEquipe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica qual membro da equipe participou da roleta.</description>
    <label>Membro da equipe</label>
    <referenceTo>MembroEquipe__c</referenceTo>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/PausarDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>PausarDistribuicao__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se a distribuição de leads está pausada para este participante ou não.</description>
    <inlineHelpText>Indique se a distribuição de leads está pausada para este participante ou não.</inlineHelpText>
    <label>Pausar distribuição</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/PresencaValidada__c.field-meta.xml
<CustomField>
    <fullName>PresencaValidada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se a presença do corretor foi validada pelo coordenador para recepção de leads.</description>
    <inlineHelpText>Indica se a presença do corretor foi validada pelo coordenador para recepção de leads.</inlineHelpText>
    <label>Presença validada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <description>Indica a situação do usuário no Omnichannel.</description>
    <formula>TEXT(MembroEquipe__r.Usuario__r.Situacao__c)</formula>
    <inlineHelpText>Indica a situação do usuário no Omnichannel.</inlineHelpText>
    <label>Situação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/Ativa__c.field-meta.xml
<CustomField>
    <fullName>Ativa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/DiasSemana__c.field-meta.xml
<CustomField>
    <fullName>DiasSemana__c</fullName>
    <description>Indica em quais dias da semana podem ser realizadas distribuições de lead para a
        roleta</description>
    <inlineHelpText>Selecione os dias da semana para a distribuição de leads na roleta.</inlineHelpText>
    <label>Dias da semana</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DiasSemana</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Indica a equipe responsável pelo atendimento dos leads distribuídos para a roleta.</description>
    <label>Equipe</label>
    <referenceTo>Equipe__c</referenceTo>
    <relationshipName>RoletasLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/fields/HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>HoraInicio__c</fullName>
    <description>Indica o horário de início para as distribuições de lead para a roleta.</description>
    <label>Hora de início</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/User/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <defaultValue>&apos;Offline&apos;</defaultValue>
    <label>Situação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SituacoesParticipantes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CanaisAtendimento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fale conosco</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Telefone</fullName>
    </customValue>
    <customValue>
        <fullName>Loja</fullName>
    </customValue>
    <customValue>
        <fullName>Stand</fullName>
    </customValue>
    <masterLabel>Canais de atendimento</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DiasSemana.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domingo</fullName>
    </customValue>
    <customValue>
        <fullName>Segunda-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Terça-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quarta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Quinta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sexta-feira</fullName>
    </customValue>
    <customValue>
        <fullName>Sábado</fullName>
    </customValue>
    <masterLabel>Dias da semana</masterLabel>
</GlobalValueSet>

you/force-app/main/default/globalValueSets/SituacoesParticipantes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Indisponível</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Situações dos participantes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DistribuirLeadsServiceTest.cls
@isTest
private class DistribuirLeadsServiceTest {
    private static final String ALIAS_USUARIO_1 = 'standt';
    private static final String ALIAS_USUARIO_2 = 'teste';
    private static final String EMAIL_USUARIO_1 = 'standarduser@testorg.com';
    private static final String EMAIL_USUARIO_2 = 'teste@testorg.com';
    private static final String LAST_NAME_USUARIO_1 = 'Testing';
    private static final String LAST_NAME_USUARIO_2 = 'Testing1';
    private static final String USERNAME_USUARIO_1 = 'ksaoidsjadosajoidasjiokdaso@rsis.com';
    private static final String USERNAME_USUARIO_2 = 'a28301@rsis.com';

    @TestSetup
    static void makeData() {
        //TriggerHandler.bypass('LeadTriggerHandler');

        RecordType recordTypeCorretor = [SELECT Id, Name FROM RecordType WHERE Name = 'Corretor' LIMIT 1];

        Id perfilAdministradorSistema = [SELECT Id FROM Profile WHERE Name = 'Administrador do sistema' OR Name = 'System Administrator'].id;
		
        Contact ctt = new Contact(LastName = 'jorge',DatadeVencimento__c = Date.Today() , Cpf__c = '18875199043' , RecordTypeId = recordTypeCorretor.Id);
        insert ctt;
        
        update ctt;
        
        List<User> usuarios = new List<User>{
            new User(
                Alias = ALIAS_USUARIO_1,
                Email = EMAIL_USUARIO_1,
                EmailEncodingKey = 'UTF-8',
                LastName = LAST_NAME_USUARIO_1,
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = USERNAME_USUARIO_1,
                ProfileId = perfilAdministradorSistema,
                Situacao__c = 'Online'
            ),
            new User(
                Alias = ALIAS_USUARIO_2,
                Email = EMAIL_USUARIO_2,
                EmailEncodingKey = 'UTF-8',
                LastName = LAST_NAME_USUARIO_2,
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = USERNAME_USUARIO_2,
                ProfileId = perfilAdministradorSistema,
                Situacao__c = 'Online'
            )
        };
        insert usuarios;

        Equipe__c equipe = new Equipe__c();

        insert equipe;

        List<MembroEquipe__c> membrosEquipes = new List<MembroEquipe__c>{
            new MembroEquipe__c(
                Name = 'Equipe a' ,
                Equipe__c = equipe.Id,
                Usuario__c = usuarios.get(0).Id
            ),
            new MembroEquipe__c(
                Name = 'Equipe b' ,
                Equipe__c = equipe.Id,
                Usuario__c = usuarios.get(1).Id
            )
        };
        insert membrosEquipes;

        RoletaLeads__c roletaLeads = new RoletaLeads__c(
            Name = 'Roleta - Equipe 0',
            Ativa__c = true,
            HoraInicio__c = Datetime.now().time(),
            CanaisAtendimento__c = 'WhatsApp',
            Equipe__c = equipe.Id,
            DiasSemana__c = 'Domingo;Segunda-feira;Terça-feira;Quarta-feira;Quinta-feira;Sexta-feira;Sábado'
        );
        insert roletaLeads;

        ParticipanteRoleta__c participante = new ParticipanteRoleta__c(
            Entrada__c = System.now(),
            MembroEquipe__c = membrosEquipes.get(0).Id,
            RoletaLeads__c = roletaLeads.Id
        );
        insert participante;

        Lead lead = new Lead(
            OwnerId = usuarios.get(1).Id,
            LastName = 'Raposo',
            Company = 'porao',
            Status = 'Novo',
            CanalAtendimento__c = 'Whatsapp',
            Email = 'e@gmail.com'
        );
        insert lead;
    }

    @isTest
    static void testarDistribuirLeads() {
        Lead lead = [SELECT CanalAtendimento__c, RoletaLeads__c, Corretor__c FROM Lead LIMIT 1];

        DistribuirLeadsService.distribuirLeads(new List<Lead>{ lead });
        
        User usuario = [SELECT Id FROM User WHERE Username = 'ksaoidsjadosajoidasjiokdaso@rsis.com'];
        
        
        List<ParticipanteRoleta__c> participantes = [Select id,Situacao__c,RoletaLeads__c,CargaRestante__c,PausarDistribuicao__c,MembroEquipe__r.ExigeValidacaoCoordenador__c,PresencaValidada__c,MembroEquipe__r.Usuario__r.CanaisAtendimento__c from ParticipanteRoleta__c];
        List<RoletaLeads__c> roleta = [Select id,CanaisAtendimento__c from RoletaLeads__c];
        
        DistribuirLeadsService.obterParticipantesOnline(participantes);
        DistribuirLeadsService.distribuirLeadsAsync(new Set<Id>{lead.Id});
        DistribuirLeadsService.reordenarParticipantesRoletasLeads(participantes);
        DistribuirLeadsService.distribuirLeadsComRoleta(new List<Lead>{lead}, roleta);
        DistribuirLeadsService.distribuirLeads(new List<Lead>{lead}, roleta);
        DistribuirLeadsService.distribuirLeads(participantes);
        DistribuirLeadsService.distribuirLeadEntreParticipantes(lead, roleta[0]);
        DistribuirLeadsService.obterLeadsParaDistribuir(new List<Lead>{lead});

        DistribuirLeadsService.notifyUsers(new Set<String>{usuario.Id}, lead.Id);

        LeadSelector.obterLeadsParaDistribuir(); 
        LeadSelector.obterLeadsPorIdsProprietarios(new Set<Id>{usuario.Id}); 
        LeadSelector.obterLeadsPorIdsUsuarios(new Set<Id>{usuario.Id}); 
        LeadSelector.obterLeadsPorIds(new Set<Id>{lead.Id}); 
        LeadSelector.obterLeadsPorChavesExternasClientes(new Set<String>{'199931148623'});
        LeadSelector.obterLeadsPorInformacoesConcierge('raposo', '', 'e@gmail.com'); 
        LeadSelector.obterLeadsPorInformacoesConcierge('', 'e@gmail.com', false, ''); 
        LeadSelector.obterInfosTemplatePadrao(lead.Id); 
        
        RoletaLeadsSelector.obterRoletasLeadsPorIdsMembros(new Set<Id>{usuario.Id});
        RoletaLeadsSelector.obterRoletasLeadsPorIdsUsuarios(new Set<Id>{usuario.Id});
        RoletaLeadsSelector.obterRoletasLeadsVigentes();
        
        
        ParticipanteRoletaDomain.obterParticipantesPorIdMembro(participantes);
        ParticipanteRoletaDomain.obterParticipantesPorIdRoleta(participantes);
        
        ParticipanteRoletaSelector.obterParticipantesPorIdsMembros(new Set<Id>{usuario.Id});
        ParticipanteRoletaSelector.obterParticipantesPorUserID(usuario.Id);
        ParticipanteRoletaSelector.obterParticipantesPorIdsRoleta(new Set<Id>{roleta[0].Id});
        
        MembroEquipeSelector.obterMembrosPorId(new Set<Id>{lead.Id});

        // Assert.areEqual(lead.Corretor__c, usuario.Id, 'Lead distribuído corretamente');
    }

    // @isTest
    // static void canalConfiguradoTest() {
    //     Test.startTest();
    //     Lead lead = [SELECT CanalAtendimento__c FROM Lead WHERE CanalAtendimento__c = 'Whatsapp' LIMIT 1];
    //     ParticipanteRoleta__c participante = [SELECT MembroEquipe__r.Usuario__r.CanaisAtendimento__c FROM ParticipanteRoleta__c LIMIT 1];

    //     Boolean resultado = DistribuirLeadsService.canalConfigurado(lead, participante);
        
       
    //     participante.MembroEquipe__r.Usuario__r.CanaisAtendimento__c = 'Telegram';  // Mudando para outro canal
    //     update participante;
        
    //     resultado = DistribuirLeadsService.canalConfigurado(lead, participante);

    //     Test.stopTest();
        
    //  }
    

     @isTest 
     static void canalBypassTest(){
        Lead lead = [SELECT Id  , CanalAtendimento__c FROM Lead LIMIT 1];

        DistribuirLeadsService.canalBypass(lead);
     }

    //  @isTest 
    //  static void possuiCapacidadeAtendimentoTest(){
    //     Lead lead = [SELECT Id ,CanalAtendimento__c FROM Lead LIMIT 1];
        
    //     ParticipanteRoleta__c participantes = [SELECT Id , CargaRestante__c FROM ParticipanteRoleta__c LIMIT 1];

    //     DistribuirLeadsService.possuiCapacidadeAtendimento(lead , participantes);
    
    //  }

     @isTest
     static void distribuirLeadTest(){
         // Busca o primeiro Lead na base
         Lead lead = [SELECT Id FROM Lead LIMIT 1];
     
         // Busca o primeiro Contact com o RecordType 'Corretor'
         Id corretor = [SELECT Id FROM Contact WHERE RecordType.Name = 'Corretor' LIMIT 1].Id;
     
         // Busca a primeira RoletaLeads__c
         Id listaRoletas = [SELECT Id FROM RoletaLeads__c LIMIT 1].Id;
     
         // Chama o método distribuirLead passando os IDs corretamente
         DistribuirLeadsService.distribuirLead(lead, corretor, listaRoletas);
     }

     //  distribuirLeadEntreParticipantes(Lead lead, RoletaLeads__c roletaLeads)

     @isTest
static void distribuirLeadEntreParticipantesTest() {
    // Obtém um lead de teste
    Lead lead = [SELECT Id , CanalAtendimento__c FROM Lead LIMIT 1];
    
    // Consulta a roleta incluindo os campos necessários do objeto User
    RoletaLeads__c roleta = [
        SELECT Id,
               (SELECT Id, MembroEquipe__r.Id, MembroEquipe__r.Usuario__r.Id, MembroEquipe__r.Usuario__r.CanaisAtendimento__c 
                FROM ParticipantesRoleta__r)
        FROM RoletaLeads__c
        LIMIT 1
    ];

    // Chama o serviço para distribuir o lead entre os participantes
    Map<Id, List<ParticipanteRoleta__c>> result = DistribuirLeadsService.distribuirLeadEntreParticipantes(lead, roleta);
    
}
@isTest 
static void testReordenarParticipantesRoletasLeads() {
    // Realizando consultas para buscar as roletas e participantes já existentes
    List<RoletaLeads__c> roletas = [SELECT Id FROM RoletaLeads__c LIMIT 2];
    List<ParticipanteRoleta__c> participantes = [SELECT Id, RoletaLeads__c FROM ParticipanteRoleta__c WHERE RoletaLeads__c IN :roletas];

    Map<Id, List<ParticipanteRoleta__c>> participantesPorIdRoleta = new Map<Id, List<ParticipanteRoleta__c>>();
    
    for (ParticipanteRoleta__c participante : participantes) {
        if (!participantesPorIdRoleta.containsKey(participante.RoletaLeads__c)) {
            participantesPorIdRoleta.put(participante.RoletaLeads__c, new List<ParticipanteRoleta__c>());
        }
        participantesPorIdRoleta.get(participante.RoletaLeads__c).add(participante);
    }

    List<ParticipanteRoleta__c> participantesReordenados = DistribuirLeadsService.reordenarParticipantesRoletasLeads(participantesPorIdRoleta);

  
}

     
     
     
}