force-app/main/default/objects/AnaliseCredito__c/AnaliseCredito__c.object-meta.xml
<CustomObject>
    <label>Análise de Crédito</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Análises de Crédito</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AnaliseCredito__c/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AnaliseCredito__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Análises de Crédito</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AnaliseCredito__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reprovada</fullName>
            </value>
            <value>
                <fullName>Vencida</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/Checklist_de_Documentos__c.object-meta.xml
<CustomObject>
    <label>Checklist de Documentos</label>
    <nameField>
        <label>Nome de Checklist de Documentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Documenta_o__c.field-meta.xml
<CustomField>
    <fullName>Documenta_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documentação</label>
    <referenceTo>Documentacao__c</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_de_Documentos__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contato.recordType-meta.xml
<RecordType>
    <fullName>Contato</fullName>
    <active>true</active>
    <label>Contato</label>
</RecordType>

force-app/main/default/objects/Documentacao__c/Documentacao__c.object-meta.xml
<CustomObject>
    <description>Documentação de contato</description>
    <label>Documentação</label>
    <nameField>
        <label>Nome de Documentação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Documentacao__c/fields/AnaliseCredito__c.field-meta.xml
<CustomField>
    <fullName>AnaliseCredito__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Análise de Crédito</label>
    <referenceTo>AnaliseCredito__c</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documenta_es</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Documentações</relationshipLabel>
    <relationshipName>Documentacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/ContentDocumentId_c__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId_c__c</fullName>
    <label>ContentDocumentId__c</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/DataEntrega__c.field-meta.xml
<CustomField>
    <fullName>DataEntrega__c</fullName>
    <description>Data de Entrega do documento</description>
    <label>Data Entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Entregue__c.field-meta.xml
<CustomField>
    <fullName>Entregue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entregue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documentacao__c/fields/Validado__c.field-meta.xml
<CustomField>
    <fullName>Validado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Descreve se o documento foi ou está validado ou não.</description>
    <label>Validado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__mdt/Documento__mdt.object-meta.xml
<CustomObject>
    <label>Documento (Configuracao)</label>
    <pluralLabel>Documentacao</pluralLabel>
</CustomObject>

force-app/main/default/objects/Documento__mdt/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatorio</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor (Contato)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordType.Id</field>
            <operation>equals</operation>
            <value>012bL0000003bkfQAA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo De Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Negócio existente</fullName>
                <default>true</default>
                <label>Negócio existente</label>
            </value>
            <value>
                <fullName>Negócio novo</fullName>
            </value>
            <value>
                <fullName>Financiamento Bancário</fullName>
                <isActive>false</isActive>
                <label>Financiamento Bancário</label>
            </value>
            <value>
                <fullName>Financiamento Direto</fullName>
                <isActive>false</isActive>
                <label>Financiamento Direto</label>
            </value>
            <value>
                <fullName>Venda a Vista</fullName>
                <isActive>false</isActive>
                <label>Venda a Vista</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentacaoHelperTest.cls
@isTest
public with sharing class DocumentacaoHelperTest {
    
    @TestSetup
    static void setup() {        
        Opportunity opp = new Opportunity();
        opp.Name = 'Teste';
        opp.Amount = 1000;
        opp.CanalAtendimento__c = 'WhatsApp';
        opp.Probability = 20;
        opp.TipoVenda__c = 'Negócio novo';
        opp.CloseDate = System.today().addDays(15);
        opp.StageName = 'Pré-análise';
        insert opp;

        Contact ctt = new Contact();
        ctt.FirstName = 'Elera';
        ctt.LastName = 'Teste';
        ctt.Email = 'teste.dev@elera.io';
        insert ctt;

        OpportunityContactRole contactRole = new OpportunityContactRole(
            OpportunityId = opp.Id,
            ContactId = ctt.Id,
            Role = 'Comprador'
        );
        insert contactRole;
        
        AnaliseCredito__c analise = new AnaliseCredito__c();
        analise.Name = 'Teste';
        analise.Status__c = 'Em Análise';
        analise.Opportunity__c = opp.Id;
        analise.DataVencimento__c = Date.today();

        insert analise;

        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'RG';
        contentVersion.PathOnClient = 'image/jpeg';
        contentVersion.VersionData = EncodingUtil.base64Decode('This is version data');
        insert contentVersion;

        ContentVersion cv = [
            SELECT ContentDocumentId 
            FROM ContentVersion 
            WHERE Id = :contentVersion.Id
        ];

        ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
        contentDocumentLink.ContentDocumentId = cv.ContentDocumentId;
        contentDocumentLink.LinkedEntityId = opp.Id;
        contentDocumentLink.ShareType = 'I'; 
        contentDocumentLink.Visibility = 'AllUsers';
        insert contentDocumentLink;

        Documentacao__c doc = new Documentacao__c(
            Obrigatorio__c = true,
            Entregue__c = true,
            Name = 'RG',
            ContentDocumentId_c__c = cv.ContentDocumentId,
            DataEntrega__c = Date.today(),
            Contato__c = ctt.Id,
            Validado__c = false
        );

        insert doc;
        
        Checklist_de_Documentos__c checklist = new Checklist_de_Documentos__c();
        checklist.Oportunidade__c = opp.Id;
        checklist.Documenta_o__c = doc.Id;
        checklist.Contato__c = ctt.Id;
        insert checklist;
    }
    
    @IsTest
    static void testCriarDocumentacao() {
        String nomeDocumento = 'Dock Test';
        
        Test.startTest();
        DocumentacaoHelper.criarDocumentacao(nomeDocumento);
        Test.stopTest();
        
        Documentacao__c doc = [
            SELECT Id, Name
            FROM Documentacao__c
            WHERE Name = 'Dock Test'
        ];
        
        System.assertNotEquals(null, doc, 'Deveria existir um Documento salvo.');
        System.assertEquals(nomeDocumento, doc.Name, 'Deveria existir uma Documentação com o nome "Dock Test".');
    }

    @IsTest
    static void testCreate() {
        String base64 = EncodingUtil.base64Encode(Blob.valueOf('Test File Content'));
        String title = 'RG';
        Documento__mdt docMdt = DocumentacaoDA.getMetadasByName(new Set<String>{title})[0];
        Opportunity opportunity = [SELECT Id FROM Opportunity LIMIT 1];
        Contact contato = [SELECT Id FROM Contact LIMIT 1];

        Test.startTest();
            Documentacao__c doc = DocumentacaoHelper.create(contato.Id, opportunity.Id, true, base64, title, 'Rg_template.jpeg', 'image/jpeg');
        Test.stopTest();

        System.assert(doc.Name == 'RG', 'Documento RG Criado');
    }
    
    @IsTest
    static void testGetByAnaliseCreditoValidate() {
        AnaliseCredito__c analise = [
            SELECT Id
            FROM AnaliseCredito__c
        ];
        
        Test.startTest();
        List<Documentacao__c> docs = DocumentacaoHelper.getByAnaliseCredito(analise.Id);
        Test.stopTest();
        
        List<Documentacao__c> expected = [
            SELECT Id, Name, Validado__c, Obrigatorio__c, Entregue__c 
        	FROM Documentacao__c
        ];
        
        System.assertEquals(expected, docs, 'Deveria retornar uma lista de Documentos.');
    }
    
    @IsTest
    static void testValidateDocuments() {
        Documentacao__c doc = [
            SELECT Id, Validado__c
            FROM Documentacao__c
        ];
        doc.Validado__c = false;
        update doc;
        
        Test.startTest();
        List<Documentacao__c> docs = DocumentacaoHelper.validateDocuments(new Set<Id>{ doc.Id });
        Test.stopTest();
        
        List<Documentacao__c> expected = [
            SELECT Id, Name, Contato__c, ContentDocumentId_c__c, Entregue__c, Validado__c
        	FROM Documentacao__c
        ];
        
        System.assertEquals(expected, docs, 'Deveria retornar uma lista de Documentos válidos.');
    }
    
    @IsTest
    static void testInvalidateDocuments() {
        Documentacao__c doc = [
            SELECT Id, Validado__c
            FROM Documentacao__c
        ];
        doc.Validado__c = true;
        update doc;
        
        Test.startTest();
        List<Documentacao__c> docs = DocumentacaoHelper.invalidateDocuments(new Set<Id>{ doc.Id });
        Test.stopTest();
        
        List<Documentacao__c> expected = [
            SELECT Id, Name, Contato__c, ContentDocumentId_c__c, Entregue__c, Validado__c
        	FROM Documentacao__c
        ];
        
        System.assertEquals(expected, docs, 'Deveria retornar uma lista de Documentos inválidos.');
    }
    
    @IsTest
    static void testDeleteById() {
        Documentacao__c doc = [SELECT Id FROM Documentacao__c LIMIT 1];
        
        Test.startTest();
            DocumentacaoHelper.deleteById(doc.Id);
        Test.stopTest();

        System.assert(doc.Id != null || doc.Id != '', 'Documento deve conter um ID');
    }
    
    

    @IsTest
    static void testGetDocumentsFromOppToContactRoles() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        System.debug(opp);

        Test.startTest();
            List<Map<String, Object>> docForEachContact = DocumentacaoHelper.getDocumentsFromOppToContactRoles(opp.Id);
        Test.stopTest();

        System.debug(docForEachContact);

        System.assert(!docForEachContact.isEmpty(), 'Encontrado documentos da oportunidade'); 
    }
    

    @IsTest
    static void testGetByOpportunityId() {
        Opportunity opps = [SELECT Id FROM Opportunity];

        Set<Id> oppsIds = new Set<Id>();
        oppsIds.add(opps.Id);

        Test.startTest();
            List<Documentacao__c> docs = DocumentacaoHelper.getByOpportunityId(oppsIds);
        Test.stopTest();

        System.assert(!docs.isEmpty(), 'Encontrado documentos das oportunidades');

    }

    @IsTest
    static void testGetMetadasByPapers() {
        Test.startTest();
            List<Documento__mdt> docs = DocumentacaoHelper.getMetadasByPaper('Comprador');
        Test.stopTest();
        System.assert(!docs.isEmpty(), 'Documentos pelo papel de contato');
    }

    @IsTest 
    static void testGetByOpportunityIdFilteredByRole() {
        Opportunity opps = [SELECT Id FROM Opportunity LIMIT 1];

        Set<Id> oppsIds = new Set<Id>();
        oppsIds.add(opps.Id);

        Test.startTest();
        List<Documentacao__c> docs = DocumentacaoHelper.getByOpportunityIdFilteredByRole(oppsIds);
        Test.stopTest();


        System.assert(!docs.isEmpty(), 'Encontrado documentos da oportunidade'); 
    }
    
    
}