force-app/main/default/objects/ConfiguracaoCanalAtendimento__mdt/ConfiguracaoCanalAtendimento__mdt.object-meta.xml
<CustomObject>
    <label>Configuração de canal de atendimento</label>
    <pluralLabel>Configurações de canais de atendimento</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoCanalAtendimento__mdt/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <description>Indica o canal de atendimento a ser configurado.</description>
    <inlineHelpText>Indique o canal de atendimento a ser configurado.</inlineHelpText>
    <label>Canal de atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
                <default>true</default>
                <label>Fale conosco</label>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <inlineHelpText>Indica o canal ou meio que o lead utilizou para se conectar com a empresa.</inlineHelpText>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fale conosco</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
            <value>
                <fullName>Loja</fullName>
            </value>
            <value>
                <fullName>Stand</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Cadastro Manual</fullName>
            </value>
            <value>
                <fullName>Oferta Corretor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica o corretor responsável pelo lead.</description>
    <inlineHelpText>Indique o corretor responsável pelo lead.</inlineHelpText>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>O corretor deve pertencer à roleta do lead.</errorMessage>
        <filterItems>
            <field>ParticipanteRoleta__c.RoletaLeads__c</field>
            <operation>equals</operation>
            <valueField>$Source.RoletaLeads__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ParticipanteRoleta__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica a roleta de leads para onde o lead foi distribuído.</description>
    <inlineHelpText>Indica a roleta de leads para onde o lead foi distribuído.</inlineHelpText>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MembroEquipe__c/MembroEquipe__c.object-meta.xml
<CustomObject>
    <description>Vincula um usuário responsável pelo atendimento dos leads a uma equipe de roleta de
        leads</description>
    <label>Membro da equipe</label>
    <nameField>
        <label>Nome do membro da equipe</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Membros da equipe</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MembroEquipe__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>MembrosEquipe</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/ParticipanteRoleta__c.object-meta.xml
<CustomObject>
    <description>Registra quais usuários participaram da distribuição de leads por roleta.</description>
    <label>Participante da roleta</label>
    <nameField>
        <label>Nome de participante da roleta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participantes da roleta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ParticipanteRoleta__c/fields/MembroEquipe__c.field-meta.xml
<CustomField>
    <fullName>MembroEquipe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indica qual membro da equipe participou da roleta.</description>
    <label>Membro da equipe</label>
    <referenceTo>MembroEquipe__c</referenceTo>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/ParticipanteRoleta__c/fields/Posicao__c.field-meta.xml
<CustomField>
    <fullName>Posicao__c</fullName>
    <description>Indica a posição do participante na fila para distribuição de leads.</description>
    <inlineHelpText>Indica a posição do participante na fila para distribuição de leads.</inlineHelpText>
    <label>Posição</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

you/force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsChat__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsChat__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Chat&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Chat&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Chat&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsFaleConosco__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsFaleConosco__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Fale
        conosco&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Fale
        conosco&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Fale conosco&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsLoja__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsLoja__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Loja&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Loja&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Loja&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsStand__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsStand__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Stand&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Stand&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Stand&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsTelefone__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsTelefone__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;Telefone&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;Telefone&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;Telefone&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

you/force-app/main/default/objects/ParticipanteRoleta__c/fields/QuantidadeLeadsWhatsApp__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeLeadsWhatsApp__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Quantidade de leads em atendimento pelo participante no canal &quot;WhatsApp&quot;.</description>
    <inlineHelpText>Quantidade de leads em atendimento pelo participante no canal &quot;WhatsApp&quot;.</inlineHelpText>
    <label>Quantidade de leads em &quot;WhatsApp&quot;</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/RoletaLeads__c.field-meta.xml
<CustomField>
    <fullName>RoletaLeads__c</fullName>
    <label>Roleta de leads</label>
    <referenceTo>RoletaLeads__c</referenceTo>
    <relationshipLabel>Participantes da roleta</relationshipLabel>
    <relationshipName>ParticipantesRoleta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ParticipanteRoleta__c/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <description>Indica a situação do usuário no Omnichannel.</description>
    <formula>TEXT(MembroEquipe__r.Usuario__r.Situacao__c)</formula>
    <inlineHelpText>Indica a situação do usuário no Omnichannel.</inlineHelpText>
    <label>Situação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RoletaLeads__c/RoletaLeads__c.object-meta.xml
<CustomObject>
    <description>Responsável pela distribuição de leads por equipe de vendas.</description>
    <label>Roleta de leads</label>
    <nameField>
        <label>Nome da roleta de leads</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roletas de leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RoletaLeads__c/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CanaisAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanaisAtendimento__c</fullName>
    <description>Filtra os leads por canal de atendimento para distribuição na roleta.</description>
    <label>Canais de atendimento</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CanaisAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <defaultValue>&apos;Offline&apos;</defaultValue>
    <label>Situação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SituacoesParticipantes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/CanaisAtendimento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Fale conosco</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Telefone</fullName>
    </customValue>
    <customValue>
        <fullName>Loja</fullName>
    </customValue>
    <customValue>
        <fullName>Stand</fullName>
    </customValue>
    <masterLabel>Canais de atendimento</masterLabel>
</GlobalValueSet>

you/force-app/main/default/globalValueSets/SituacoesParticipantes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Indisponível</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <masterLabel>Situações dos participantes</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OmnichannelService.cls
public without sharing class OmnichannelService {
        private static final Map<String, ConfiguracaoCanalAtendimento__mdt> CONFIGURACOES_POR_CANAL = new Map<String, ConfiguracaoCanalAtendimento__mdt>();
    
        /**
         * Método responsável pela seleção de canais de atendimento no usuário para
         * recepção de leads dos respectivos canais.
         */
        public static String selecionarCanais(List<String> canaisAtendimento) {
            Database.update(new User(Id = UserInfo.getUserId(), CanaisAtendimento__c = String.join(canaisAtendimento, ';')));
    
            return obterUsuario();
        }
    
        /**
         * Método responsável pela aceitação do lead atribuído ao corretor, definindo
         * o corretor como proprietário.
         */
        public static String aceitarLead(Id idLead) {
            Database.update(new Lead(Id = idLead, OwnerId = UserInfo.getUserId()));
    
            adicionarLeadAoParticipante(idLead);
    
            return obterLeadsEmNovo();
        }
    
        private static void adicionarLeadAoParticipante(Id idLead) {
            Lead lead = LeadDomain.obterLeadPorId(idLead);

            System.debug('Lead ' + lead);
    
            adicionarLeadAoParticipante(lead);
    
            Database.update(lead.Corretor__r);
    
            setParticipantePosition(lead.Corretor__c, lead.RoletaLeads__c);
        }
    
        private static void setParticipantePosition(Id membro, Id roletaId) {
            List<ParticipanteRoleta__c> participantes = [
                SELECT Id, Posicao__c, MembroEquipe__c
                FROM ParticipanteRoleta__c
                WHERE RoletaLeads__c = :roletaId
                ORDER BY Posicao__c ASC
            ];
        
            ParticipanteRoleta__c participanteMovido;
        
            for (ParticipanteRoleta__c participante : participantes) {
                if (participante.MembroEquipe__c == membro) {
                    participanteMovido = participante;
                    break;
                }
            }
        
            Integer novaPosicao = 1;
            for (ParticipanteRoleta__c participante : participantes) {
                if (participante != participanteMovido) {
                    participante.Posicao__c = novaPosicao;
                    novaPosicao++;
                }
            }
        
            if (participanteMovido != null) {
                participanteMovido.Posicao__c = novaPosicao;
            }
        
            Database.update(participantes);
        }
        
        
    
        private static void adicionarLeadAoParticipante(Lead lead) {
            switch on lead.CanalAtendimento__c {
                when 'Fale conosco' {
                    lead.Corretor__r.QuantidadeLeadsFaleConosco__c = (lead.Corretor__r.QuantidadeLeadsFaleConosco__c <> null ? 0 : lead.Corretor__r.QuantidadeLeadsFaleConosco__c) + 1;
                }
                when 'Chat' {
                    lead.Corretor__r.QuantidadeLeadsChat__c = (lead.Corretor__r.QuantidadeLeadsChat__c <> null ? 0 : lead.Corretor__r.QuantidadeLeadsChat__c) + 1;
                }
                when 'WhatsApp' {
                    lead.Corretor__r.QuantidadeLeadsWhatsApp__c = (lead.Corretor__r.QuantidadeLeadsWhatsApp__c <> null ? 0 : lead.Corretor__r.QuantidadeLeadsWhatsApp__c) + 1;
                }
                when 'Telefone' {
                    System.debug('lead.Corretor__r.QuantidadeLeadsTelefone__c'+lead.Corretor__c);
                    System.debug('lead.Corretor__r.QuantidadeLeadsTelefone__c'+lead.Corretor__r.QuantidadeLeadsTelefone__c);
                    lead.Corretor__r.QuantidadeLeadsTelefone__c = (lead.Corretor__r.QuantidadeLeadsTelefone__c <> null ? 0 : lead.Corretor__r.QuantidadeLeadsTelefone__c) + 1;
                }
                when 'Loja' {
                    lead.Corretor__r.QuantidadeLeadsLoja__c = (lead.Corretor__r.QuantidadeLeadsLoja__c <> null ? 0 : lead.Corretor__r.QuantidadeLeadsLoja__c) + 1;
                }
                when 'Stand' {
                    lead.Corretor__r.QuantidadeLeadsStand__c = (lead.Corretor__r.QuantidadeLeadsStand__c <> null ? 0 : lead.Corretor__r.QuantidadeLeadsStand__c) + 1;
                }
                when else {
                    
                }
            }
        }
    
        /**
         * Método responsável pela rejeição do lead atribuído ao corretor, limpando a
         * roleta e corretor escolhidos.
         */
       /* public static String rejeitarLead(Id idLead) {
            Database.update(new Lead(Id = idLead, RoletaLeads__c = null, Corretor__c = null));
    
            return obterLeadsEmNovo();
        }*/
    
        public static String rejeitarLead(Id idLead) {
            // Obter o lead pelo Id
            Lead lead = LeadDomain.obterLeadPorId(idLead);
            Id roletaId = lead.RoletaLeads__c;
            
            // Obter todos os participantes da roleta que estão online, ordenados por posição
            List<ParticipanteRoleta__c> participantes = [
                SELECT Id, 
                       MembroEquipe__c,
                       MembroEquipe__r.Usuario__c,
                       Posicao__c,
                       RoletaLeads__c
                FROM ParticipanteRoleta__c 
                WHERE RoletaLeads__c = :roletaId 
                    AND MembroEquipe__r.Usuario__r.Situacao__c = 'Online'  // Verifica se o usuário está online
                ORDER BY Posicao__c ASC
            ];
            
            // Inicializa variáveis para encontrar o próximo membro disponível
            Boolean currentMemberFound = false;
            Id nextMemberUserId = null;
            
            // Percorre os participantes para encontrar o próximo corretor
            for (ParticipanteRoleta__c participante : participantes) {
                if (currentMemberFound) {
                    nextMemberUserId = participante.MembroEquipe__r.Usuario__c;
                    break;
                }
                if (participante.MembroEquipe__r.Usuario__c == lead.Corretor__c) {
                    currentMemberFound = true;
                }
            }
            
            // Se não encontrou o próximo membro ou chegou ao fim da lista, retorna ao primeiro participante
            if (nextMemberUserId == null && !participantes.isEmpty()) {
                nextMemberUserId = participantes[0].MembroEquipe__r.Usuario__c;
            }
            
            // Atualizar o lead para remover a associação com o corretor atual
            lead.Corretor__c = null;
        
            // Atualiza o lead no Salesforce
            update lead;
            
            // Notificar o novo corretor se houver (opcional, conforme sua lógica de negócios)
            if (nextMemberUserId != null) {
                notificarPeloChatter(lead.Id, nextMemberUserId);
                enviarEmailLeadsEmTrabalho(nextMemberUserId, new List<LeadDTO>{new LeadDTO(lead)});
            }
        
            // Retorna os leads que estão em estado "Novo"
            return obterLeadsEmNovo();
        }
        
        /**
         * Método responsável pela alteração da situação do corretor para atualização ou 
         * criação de novos participantes, caso não hajam.
         */
        public static String alterarSituacao(String novaSituacao) {
            Database.update(new User(Id = UserInfo.getUserId(), Situacao__c = novaSituacao));
    
            return obterUsuario();
        }
    
        /**
         * Método responsável pela obtenção de leads atribuídos e aceitos pelo corretor.
         */
        public static String obterLeadsEmTrabalho() {
            List<LeadDTO> leadsDTO = new List<LeadDTO>();
            for(Lead lead : LeadSelector.obterLeadsPorIdsProprietarios(new Set<Id>{ UserInfo.getUserId() })) {
                leadsDTO.add(new LeadDTO(lead));
            }
    
            return JSON.serialize(leadsDTO);
        }
    
        /**
         * Método responsável pela obtenção do usuário para apresentação da situação e
         * canais de atendimento selecionados.
         */
        public static String obterUsuario() {
            User usuario = UserDomain.obterUsuarioPorId(UserInfo.getUserId());
        
            if (String.isBlank(usuario.Situacao__c)) {
                usuario.Situacao__c = 'Offline'; 
                update usuario;
            }
        
            return JSON.serialize(new UserDTO(usuario));
        }
        
        
        /**
         * Método responsável pela obtenção das situações disponíveis para o usuário atual.
         */
        public static Map<String, String> obterSituacoes() {
            Map<String, String> situacoesPorValor = new Map<String, String>();
            for(Schema.PicklistEntry opcaoSituacao : User.Situacao__c.getDescribe().getPicklistValues()) {
                situacoesPorValor.put(opcaoSituacao.getValue(), opcaoSituacao.getLabel());
            }
    
            return situacoesPorValor;
        }
    
        /**
         * Método responsável pela obtenção dos canais de atendimento relacionados às
         * roletas que o corretor é membro.
         */
        public static Map<String, String> obterCanaisAtendimento() {
            List<RoletaLeads__c> roletasLeads = RoletaLeadsSelector.obterRoletasLeadsPorIdsUsuarios(new Set<Id>{ UserInfo.getUserId() });
            Set<String> canaisAtendimento = RoletaLeadsDomain.obterCanaisAtendimento(roletasLeads);
    
            Map<String, String> canaisAtendimentoPorValor = new Map<String, String>();
            for(Schema.PicklistEntry opcaoCanalAtendimento : User.CanaisAtendimento__c.getDescribe().getPicklistValues()) {
                if(!canaisAtendimento.contains(opcaoCanalAtendimento.getValue())) { continue; }
    
                canaisAtendimentoPorValor.put(opcaoCanalAtendimento.getValue(), opcaoCanalAtendimento.getLabel());
            }
    
            return canaisAtendimentoPorValor;
        }
    
            public static String definirStatusInicial() {
                User usuario = [SELECT Id, Situacao__c FROM User WHERE Id = :UserInfo.getUserId()];
                if (usuario.Situacao__c == null) {
                    usuario.Situacao__c = 'Offline';
                    update usuario;
                }
                return JSON.serialize(usuario);
            }
    
    
            public static String obterLeadsEmNovo() {
                CONFIGURACOES_POR_CANAL.putAll(CustomMetadataTypeDomain.obterConfiguracoesPorCanalAntendimento());
                List<LeadDTO> leadsDTO = new List<LeadDTO>();
                for(Lead lead : LeadSelector.obterLeadsPorIdsUsuarios(new Set<Id>{ UserInfo.getUserId() })) {
                    leadsDTO.add(new LeadDTO(lead, CONFIGURACOES_POR_CANAL.get(lead.CanalAtendimento__c)));
                    notificarPeloChatter(lead.Id, UserInfo.getUserId());
                }
                enviarEmailLeadsEmTrabalho(UserInfo.getUserId(), leadsDTO);
                return JSON.serialize(leadsDTO);
            }
        
        public static void enviarEmailLeadsEmTrabalho(Id userId, List<LeadDTO> leads) {
            User recipient = [SELECT Id, Email FROM User WHERE Id = :userId];
            List<String> leadDetails = new List<String>();
            for (LeadDTO lead : leads) {
                leadDetails.add('Lead: ' + User.FirstName + ' ' + User.LastName);
            }
            String subject = 'Detalhes dos Leads em Trabalho';
            String body = 'Olá,\n\nSegue abaixo os detalhes dos leads em trabalho:\n\n';
            body += String.join(leadDetails, '\n');
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(new List<String>{ recipient.Email });
            email.setSubject(subject);
            email.setPlainTextBody(body);
           // Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ email });
        }
           
            public static void notificarPeloChatter(Id leadId, Id userId) {
                Lead lead = [SELECT Id, FirstName, LastName FROM Lead WHERE Id = :leadId];
                System.debug('Lead no metodo notificarPeloChatter' +lead );
                User user = [SELECT Id, Name FROM User WHERE Id = :userId];
                System.debug('User no metodo notificarPeloChatter' + user);
                System.debug('User' + user);
                FeedItem post = new FeedItem();
                post.ParentId = lead.Id;
                post.Body = user.Name + ' aceitou o lead ' + lead.FirstName + ' ' + lead.LastName + '.';
                post.Type = 'LinkPost';	
                insert post;
            }
            
    }