force-app/main/default/objects/ConfiguracaoCanalAtendimento__mdt/ConfiguracaoCanalAtendimento__mdt.object-meta.xml
<CustomObject>
    <label>Configuração de canal de atendimento</label>
    <pluralLabel>Configurações de canais de atendimento</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoCanalAtendimento__mdt/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Um canal marcado como &quot;Bypass&quot; ignora a carga restante do corretor, tornando todos os atendimentos (leads) prioritários, sendo distribuídos imediatamente.</inlineHelpText>
    <label>Bypass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoCanalAtendimento__mdt/fields/Carga__c.field-meta.xml
<CustomField>
    <fullName>Carga__c</fullName>
    <inlineHelpText>Valor atribuído ao canal que será utilizado no cálculo da carga restante de atendimento do corretor.</inlineHelpText>
    <label>Carga</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ChaveExternaWhatsApp__c.field-meta.xml
<CustomField>
    <fullName>ChaveExternaWhatsApp__c</fullName>
    <description>Identificador deste lead no WhatsApp.</description>
    <externalId>true</externalId>
    <inlineHelpText>Indique o identificador deste lead no WhatsApp.</inlineHelpText>
    <label>Chave externa (WhatsApp)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FimDialogo__c.field-meta.xml
<CustomField>
    <fullName>FimDialogo__c</fullName>
    <description>Indica a data e hora de fim do diálogo via serviço externo de mensagens.</description>
    <inlineHelpText>Indica a data e hora de fim do diálogo via serviço externo de mensagens.</inlineHelpText>
    <label>Fim do diálogo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/InicioDialogo__c.field-meta.xml
<CustomField>
    <fullName>InicioDialogo__c</fullName>
    <description>Indica a data e hora de início do diálogo via serviço externo de mensagens.</description>
    <inlineHelpText>Indica a data e hora de início do diálogo via serviço externo de mensagens.</inlineHelpText>
    <label>Início do diálogo</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UltimaMensagem__c.field-meta.xml
<CustomField>
    <fullName>UltimaMensagem__c</fullName>
    <description>Indica a data e hora da última mensagem recebida em conversa via serviço externo de mensagens.</description>
    <inlineHelpText>Indica a data e hora da última mensagem recebida em conversa via serviço externo de mensagens.</inlineHelpText>
    <label>Última mensagem</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LeadDTOTest.cls
@isTest
private class LeadDTOTest {
    @isTest
    static void testLeadDTO() {
        Lead lead = new Lead(
            LastName = 'Teste',
            FirstName = 'Nome',
            Email = 'teste@exemplo.com',
            MobilePhone = '11999999999',
            Status = 'Novo',
            ChaveExternaWhatsApp__c = '123456',
            InicioDialogo__c = DateTime.now(),
            FimDialogo__c = DateTime.now().addHours(1),
            UltimaMensagem__c = DateTime.now(),
            Phone = '11222222222',
            OwnerId = UserInfo.getUserId()
        );
        insert lead;

        LeadDTO leadDTO = new LeadDTO(lead);

        System.assertEquals(lead.Id, leadDTO.id);
        System.assertEquals(lead.ChaveExternaWhatsApp__c, leadDTO.chaveExternaWhatsApp);
        System.assertEquals(lead.Name, leadDTO.nome);
        System.assertEquals(lead.FirstName, leadDTO.primeiroNome);
        System.assertEquals(lead.LastName, leadDTO.sobrenome);
        System.assertEquals(lead.Email, leadDTO.email);
        System.assertEquals(lead.MobilePhone, leadDTO.celular);
        System.assertEquals(lead.Status, leadDTO.status);
        System.assertEquals(lead.Owner.Name, leadDTO.proprietario);
        System.assertEquals(lead.InicioDialogo__c, leadDTO.inicioDialogo);
        System.assertEquals(lead.FimDialogo__c, leadDTO.fimDialogo);
        System.assertEquals(lead.UltimaMensagem__c, leadDTO.ultimaMensagem);
        System.assertEquals(lead.CreatedDate, leadDTO.CreatedDate);
        System.assertEquals(lead.Phone, leadDTO.telefone);
    }

    @isTest
    static void testLeadDTOWithConfiguracaoCanalAtendimento() {
        Lead lead = new Lead(
            LastName = 'Teste',
            FirstName = 'Nome',
            Email = 'teste@exemplo.com',
            MobilePhone = '11999999999',
            Status = 'Novo',
            ChaveExternaWhatsApp__c = '123456',
            InicioDialogo__c = DateTime.now(),
            FimDialogo__c = DateTime.now().addHours(1),
            UltimaMensagem__c = DateTime.now(),
            Phone = '11222222222',
            OwnerId = UserInfo.getUserId()
        );
        insert lead;

        ConfiguracaoCanalAtendimento__mdt configuracao = new ConfiguracaoCanalAtendimento__mdt(
            Label = 'Config',
            Carga__c = 100,
            Bypass__c = false
        );

        LeadDTO leadDTO = new LeadDTO(lead, configuracao);

        System.assertEquals(100, leadDTO.carga);
        System.assertEquals(null, leadDTO.cargaRestante); // Altere conforme a lógica desejada
        System.assertEquals(false, leadDTO.naoPodeAceitar);
    }
}