you/force-app/main/default/objects/SeriePagamentos__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>SeriesPagamentos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

you/force-app/main/default/objects/SeriePagamentos__c/fields/TipoCondicao__c.field-meta.xml
<CustomField>
    <fullName>TipoCondicao__c</fullName>
    <label>Tipo de Condição</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TiposCondicoes</valueSetName>
    </valueSet>
</CustomField>

you/force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor total (%)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcela__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcela__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcelaPos__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcelaPos__c</fullName>
    <defaultValue>1</defaultValue>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela POS</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/comissaoControllerTest.cls
@isTest
public class comissaoControllerTest {
    @TestSetup
    static void makeData(){
        // Criando TabelaVendas
        TabelaVendas__c tabela = new TabelaVendas__c();
        tabela.Name = 'Teste';
        tabela.PeriodicidadeParcelaPos__c = 1;
        tabela.PeriodicidadeParcela__c = 1;
        insert tabela;

        // Criando SeriePagamentos
        SeriePagamentos__c serie = new SeriePagamentos__c();
        serie.Name = 'Teste';
        serie.InicioPagamento__c = 1;
        serie.QuantidadeParcelas__c = 1;
        serie.ValorTotal__c = 1;
        serie.TabelaVenda__c = tabela.Id;
        serie.TipoCondicao__c = 'Ato';
        serie.AposHabiteSe__c = false;
        insert serie;

        SeriePagamentos__c serie2 = new SeriePagamentos__c();
        serie2.Name = 'Teste2';
        serie2.InicioPagamento__c = 1;
        serie2.QuantidadeParcelas__c = 1;
        serie2.ValorTotal__c = 1;
        serie2.TabelaVenda__c = tabela.Id;
        serie2.TipoCondicao__c = 'Mensais';
        serie2.AposHabiteSe__c = false;
        insert serie2;
    }

    @isTest
    public static void testAnalisarProposta(){
        List<SeriePagamentos__c> series = [SELECT Id, Name, InicioPagamento__c, QuantidadeParcelas__c, ValorTotal__c, TabelaVenda__c, TipoCondicao__c, AposHabiteSe__c FROM SeriePagamentos__c];
        TabelaVendas__c tabela = [SELECT Id, Name FROM TabelaVendas__c LIMIT 1];
        Map<String, Object> valoresMatriz = new Map<String, Object> {
            'nominalProposta' => 100000, 
            'nominalTabela' => 200000, 
            'valorVplProposta' => 80000, 
            'valorVplTabela' => 160000
        };

        Test.startTest();
        List<Object> retorno = comissaoController.analisarProposta(tabela.id, series, valoresMatriz);
        Test.stopTest();

        Assert.areEqual(true, (retorno.size() > 0), 'A lista não pode estar vazia');
    }
}